### ISSUE TITLE
trials mode error

### ISSUE THREAD

**Issue by multiplatformsgamer** [mob-sakai/ParticleEffectForUGUI#100]
when i use trails mode,and open world space. ps simulationSpace used local
the particlesystem show error.
![Snipaste_2020-09-23_17-52-03](https://user-images.githubusercontent.com/6984321/93997157-a82b0e00-fdc5-11ea-9b7a-e3586aab0641.png)
![Snipaste_2020-09-23_17-52-15](https://user-images.githubusercontent.com/6984321/93997170-ab25fe80-fdc5-11ea-84c3-a0864f55cd8f.png)

unity 2019.3.2f1
particleEffectForUGui-3.0-preview 34
urp 7.3.1

**Comment by mob-sakai** [comment]
@multiplatformsgamer 
Thank you for reporting.
I would like to know more about this issue. 
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

**Comment by multiplatformsgamer** [comment]
@mob-sakai i use the ParticleEffectForUGUI demo by this step:
1.change the UIParticle_Demo_Effect_Root.prefab /trials world space √
![Snipaste_2020-09-25_10-40-33](https://user-images.githubusercontent.com/6984321/94223849-834cad00-ff23-11ea-9e63-0280e0b99552.png)

2. open mask
![Snipaste_2020-09-25_10-40-50](https://user-images.githubusercontent.com/6984321/94223855-86479d80-ff23-11ea-99f2-3faf480f9eef.png)

you can use this project.
[ParticleEffectForUGUI-worldspace-trails.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/5280276/ParticleEffectForUGUI-worldspace-trails.zip)

**Comment by mob-sakai** [comment]
Thanks!

**Comment by mob-sakai** [comment]
@multiplatformsgamer 
(If possible,) could you please attach a "complete" minimal project (included Assets, Packages and ProjectSettings directories) that reproduces the issue?

**Comment by mob-sakai** [comment]
@multiplatformsgamer 
The issue is reproduced on my environment.

**Comment by multiplatformsgamer** [comment]
ok, This design is still very common. 
hope it can be repaired as soon as possible.
thanks

**Comment by mob-sakai** [comment]
@multiplatformsgamer 
Hmm, this issue seems to be caused by `MashTrailBake` API.
When `main.simulationSpace = Local` and `trails.worldSimulation`, the baked trails is incorrect.
![](https://user-images.githubusercontent.com/12690315/94279232-cd1aaf00-ff86-11ea-9099-3aaace3f4a41.gif)

[MashTrailBakeIssue.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/5283492/MashTrailBakeIssue.zip)

This bug has been reported to Unity.
http://fogbugz.unity3d.com/default.asp?1280356_4elslk9gr84ju6qu

**Comment by multiplatformsgamer** [comment]
@mob-sakai ok ,I also want to pay attention to this issue. Can you send the address?
thanks.

**Comment by mob-sakai** [comment]
@multiplatformsgamer 
https://fogbugz.unity3d.com/default.asp?1280621_iiqdj8jfaqjqtc0t

**Comment by multiplatformsgamer** [comment]
thanks!

**Comment by mob-sakai** [comment]
@multiplatformsgamer 
That report has been closed. We are discussing it here.
https://fogbugz.unity3d.com/default.asp?1280356_4elslk9gr84ju6qu

**Comment by mob-sakai** [comment]
It was added to issue tracker.
https://issuetracker.unity3d.com/product/unity/issues/guid/1280356
