### ISSUE TITLE
GetComponentInParent null error, UIParticle.cs

### ISSUE THREAD

**Issue by npicouet** [mob-sakai/ParticleEffectForUGUI#101]
Got this issue after updating to latest preview version.
Unity 2019.4.3f1.

This error happens when I'm loading into a scene with Unity SceneManager.

`NullReferenceException: Object reference not set to an instance of an object
UnityEngine.Component.GetComponentInParent (System.Type t) (at /Users/builduser/buildslave/unity/build/Runtime/Export/Scripting/Component.bindings.cs:121)
UnityEngine.Component.GetComponentInParent[T] () (at /Users/builduser/buildslave/unity/build/Runtime/Export/Scripting/Component.bindings.cs:126)
Coffee.UIExtensions.UIParticle.InitializeIfNeeded () (at Library/PackageCache/com.coffee.ui-particle@bda77ab039/Scripts/UIParticle.cs:391)
Coffee.UIExtensions.UIParticle.<UnityEngine.ISerializationCallbackReceiver.OnAfterDeserialize>b__53_0 () (at Library/PackageCache/com.coffee.ui-particle@bda77ab039/Scripts/UIParticle.cs:426)
UnityEditor.EditorApplication.Internal_CallDelayFunctions () (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorApplication.cs:322)`

**Comment by mob-sakai** [comment]
@npicouet 
Thank you for reporting.
