### ISSUE TITLE
Display material properties in inspector

### ISSUE THREAD

**Issue by gabry90** [mob-sakai/ParticleEffectForUGUI#104]
![Cattura](https://user-images.githubusercontent.com/13331266/94788217-9227d980-03d3-11eb-8c74-c462bff7e4e8.PNG)

The material property input is missing on latest preview package. How to set now the material?

OS: Windows 10 x64
Unity version: 2019.4.9f1

**Comment by mob-sakai** [comment]
@gabry90 

You can set them up from **Particle System inspector**.

1. Select a ParticleSystem object.
2. Enable `Renderer` module.
3. Set the material to `Material` and `Trail Material` properties.

![image](https://user-images.githubusercontent.com/12690315/94790632-81965400-0411-11eb-9ea7-96bb16bb5d38.png)


However, as you said, I think it would be more useful to be able to set it up from UIParticle inspector. :+1:

**Comment by gabry90** [comment]
But the Renderer panel will disable each time add UIParticle component

**Comment by mob-sakai** [comment]
Exactly.

I will release the following UI.
![image](https://user-images.githubusercontent.com/12690315/94885383-04b7b880-04ab-11eb-9de3-b256501dabe7.png)

**Comment by gabry90** [comment]
thank you, it's better 👍
