### ISSUE TITLE
Support 3D scaling

### ISSUE THREAD

**Issue by gabry90** [mob-sakai/ParticleEffectForUGUI#105]
Can you restore previous scaling mode with X,Y,Z input instead a single value? I've tried this in previous version and is better have more scaling options then one

**Comment by mob-sakai** [comment]
@gabry90 
Thank you for the feature request!

**Comment by mob-sakai** [comment]
![](https://user-images.githubusercontent.com/12690315/95017591-3b512700-0695-11eb-864e-04166ea1809a.png)
![demo-2](https://user-images.githubusercontent.com/12690315/95017806-83bd1480-0696-11eb-8c24-c56f45ab1ac2.png)
