### ISSUE TITLE
Dynamic add effect not can good work

### ISSUE THREAD

**Issue by yanghu28** [mob-sakai/ParticleEffectForUGUI#107]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Version [e.g. 1.0.0]
 - Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL]
 - Unity version: [e.g. 2018.2.8f1]
 - Build options: [e.g. IL2CPP, .Net 4.x, LWRP]

**Additional context**

**Comment by mob-sakai** [comment]
@yanghu28 
I would like to know more about this issue. ..
What do you mean by "dynamic add effect"?

**Comment by yanghu28** [comment]
for example ，I dynamic add effect  prefab at a same transform，add one effect ，I need “UIParticle.RefreshParticles”，if I add 
a UIParticle.cs at parent transform,all effect replay, is very strange. if i add "UIParticle" for every effect prefab. this is issue "Cannot combine Mesh",

**Comment by mob-sakai** [comment]
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

**Comment by yanghu28** [comment]
&nbsp; &nbsp; &nbsp; &nbsp; public static CombineInstance[] Get(List<CombineInstance&gt; src)
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var dst = new CombineInstance[src.Count];
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; for (var i = 0; i < src.Count; i++)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; dst[i].mesh = src[i].mesh;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; dst[i].transform = src[i].transform;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return dst;
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; public static CombineInstance[] Get(List<CombineInstanceEx&gt; src,int count)
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; count = Mathf.Min(count,src.Count);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var dst = new CombineInstance[count];
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; for (var i = 0; i < count; i++)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; dst[i].mesh = src[i].mesh;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; dst[i].transform = src[i].transform;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return dst;
&nbsp; &nbsp; &nbsp; &nbsp; }



I change this method;because this just 1,2,...32 Lenght array。 if one UIParticle GameObject have some ParticleSystem,it is issuse;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mob-sakai/ParticleEffectForUGUI"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月22日(星期四) 下午5:02
收件人:&nbsp;"mob-sakai/ParticleEffectForUGUI"<ParticleEffectForUGUI@noreply.github.com&gt;;
抄送:&nbsp;"tiger"<1002378395@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [mob-sakai/ParticleEffectForUGUI] Dynamic add effect not can good work (#107)





 
Could you please attach a minimal project (included Assets, Packages and ProjectSettings directories) that reproduces the issue?

**Comment by yanghu28** [comment]
MeshHelper limit mesh count is too little

**Comment by mob-sakai** [comment]
OK, I understand what you mean.

**Comment by yanghu28** [comment]
private Material GetModifiedMaterial(Material baseMaterial, Texture2D texture)
        {
            /*********2020.9.4*新增 动态修改shader UIMask效果*************/
            if(IsUseMask)
            if (baseMaterial.shader != Shader.Find("UI/Additive"))
            {
                var maskShader = Shader.Find("UI/Additive");
                baseMaterial.shader = (maskShader == null ? baseMaterial.shader : maskShader);
            }
            /**************************************************************/
            if (0 < m_StencilValue)
            {
                baseMaterial = StencilMaterial.Add(baseMaterial, (1 << m_StencilValue) - 1, StencilOp.Keep, CompareFunction.Equal, ColorWriteMask.All, (1 << m_StencilValue) - 1, 0);
                _maskMaterials.Add(baseMaterial);
            }

            if (texture == null && m_AnimatableProperties.Length == 0) return baseMaterial;

            baseMaterial = new Material(baseMaterial);
            _modifiedMaterials.Add(baseMaterial);
            if (texture)
                baseMaterial.mainTexture = texture;

            return baseMaterial;
        }

I add  dynamic support Mask or Mask2D in UIParticle.cs , so  I need not change my effect prefab,

**Comment by yanghu28** [comment]
I want reduce Batches ,so I add Same Effect Dynamic to a parent, batches is ok,but  this effect is not ok,

1、 all effect add a UIParticle.cs alone, batches is 56, show  is ok,
![image](https://user-images.githubusercontent.com/19767759/96947407-b596fd80-1515-11eb-923a-aa5010764f9d.png)

![image](https://user-images.githubusercontent.com/19767759/96947348-87b1b900-1515-11eb-8ea3-a9c2ce6bbff0.png)

2、all same effect parent add  a UIParticle.cs ,batches reduce,but show is error, this effect is amplifying,
![image](https://user-images.githubusercontent.com/19767759/96947510-f68f1200-1515-11eb-84ac-6ba1abc0a4a6.png)

![image](https://user-images.githubusercontent.com/19767759/96947128-e3c80d80-1514-11eb-9185-5a50fe324f86.png)

1、2 is same ，
![image](https://user-images.githubusercontent.com/19767759/96947585-29390a80-1516-11eb-81ed-cb3e2f11fc92.png)

**Comment by yanghu28** [comment]
![image](https://user-images.githubusercontent.com/19767759/96947748-8cc33800-1516-11eb-8293-5744202b5b83.png)


effect is amplifying，

**Comment by yanghu28** [comment]
![image](https://user-images.githubusercontent.com/19767759/96956568-0cf39880-152b-11eb-95b1-89aa0210bd70.png)

 i find if you add UiParticle.cs to a GameObject ,but no add ParticleSystem to  child ,. now   you  can not change "Ignore Canvas Scaler" int editor inspector, is very troublesome；

**Comment by yanghu28** [comment]
![Uploading image.png…]()

**Comment by yanghu28** [comment]
![image](https://user-images.githubusercontent.com/19767759/96956794-9d31dd80-152b-11eb-8379-e585fdfe7db4.png)

**Comment by mob-sakai** [comment]
I see.

### Mesh limitation

✅  Fix to unlimited.

### Dynamic support Mask or Mask2D

https://github.com/mob-sakai/ParticleEffectForUGUI/issues/107#issuecomment-714850496

❌  Rejected: Not all particles need Mask/Mask2D support


### Batching

✅  Reduce batches with material caching

### Ignore Canvas Scaler

✅  Remove `m_IgnoreCanvasScaler = true` in `InitializeIfNeeded`

**Comment by yanghu28** [comment]
I just add a bool "IsUseMask" to control shader , default IsUseMask  is false , so  if I need Mask ,I not need to change Effect Prefab defalut shader. I think this  is ok,

**Comment by yanghu28** [comment]
@mob-sakai  when you update github ,I look forward to new

**Comment by mob-sakai** [comment]
`v3.0.0` has been released!
Please try it :)

**Comment by yanghu28** [comment]
it see very well, thank for you very much
