### ISSUE TITLE
Maskable option to ignore masking

### ISSUE THREAD

**Issue by yanghu28** [mob-sakai/ParticleEffectForUGUI#109]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Version [e.g. 1.0.0]
 - Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL]
 - Unity version: [e.g. 2018.2.8f1]
 - Build options: [e.g. IL2CPP, .Net 4.x, LWRP]

**Additional context**

**Comment by yanghu28** [comment]
![image](https://user-images.githubusercontent.com/19767759/97406980-0010e380-1935-11eb-860d-877d775093d4.png)
![image](https://user-images.githubusercontent.com/19767759/97407007-08691e80-1935-11eb-9f91-6fa002266a82.png)

it just show a particle ,this is two particleSystem in a parent

**Comment by yanghu28** [comment]
![image](https://user-images.githubusercontent.com/19767759/97407205-5120d780-1935-11eb-8b91-457b5193a566.png)
![image](https://user-images.githubusercontent.com/19767759/97407246-60078a00-1935-11eb-8470-83001b957ecc.png)

**Comment by mob-sakai** [comment]
@yanghu28 
You want `Maskable` option, right?
![image](https://user-images.githubusercontent.com/12690315/97409331-c2b25300-1940-11eb-8ffa-d7d5817bfae9.png)

**Comment by yanghu28** [comment]
yes







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "mob-sakai"<notifications@github.com&gt;; 
发送时间: 2020年10月28日(星期三) 下午4:15
收件人: "mob-sakai/ParticleEffectForUGUI"<ParticleEffectForUGUI@noreply.github.com&gt;; 
抄送: "tiger"<1002378395@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [mob-sakai/ParticleEffectForUGUI] Rendering Order is a issue, this is a particleSystem is not show, (#109)





 
@yanghu28
 You want Maskable option, right?

**Comment by yanghu28** [comment]
![image](https://user-images.githubusercontent.com/19767759/97409820-32244480-1939-11eb-8687-7bb9b3dec940.png)

**Comment by yanghu28** [comment]
show is ok,but mask function is useless

**Comment by yanghu28** [comment]
I see "Mask.cs" change to "Rect mask 2D" is Ok;
![image](https://user-images.githubusercontent.com/19767759/97410249-cb535b00-1939-11eb-83c4-380f34965910.png)
