### ISSUE TITLE
I find this Tool is bother to Screen adaptation，for example ，I use 1080*1920,then mobile is 1125*2436, if I not change UICamera Size,this effect is amplification

### ISSUE THREAD

**Issue by yanghu28** [mob-sakai/ParticleEffectForUGUI#110]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yanghu28** [comment]
![image](https://user-images.githubusercontent.com/19767759/97574709-94a73e80-1a26-11eb-9229-3b8952601c54.png)
![image](https://user-images.githubusercontent.com/19767759/97574747-a4bf1e00-1a26-11eb-85f6-e1aef3b5310f.png)

**Comment by yanghu28** [comment]
![image](https://user-images.githubusercontent.com/19767759/97574806-baccde80-1a26-11eb-8208-377d395837db.png)

**Comment by mob-sakai** [comment]
@yanghu28
Could you please attach **a minimal project** (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

**Comment by mob-sakai** [comment]
In this case, please attach a minimal project that includes the following.
* A "ball"
* A ParticleSystem to be rendered the same size as the ball
* A scene with the same problem occurs (when you change the screen resolution.)

**Comment by yanghu28** [comment]
I‘ve solved it，I didn't do it right myself, I set "Ignore Canvas Scale "=false,so it see is error  to Screen adaptation.
thank you so  much,
