### ISSUE TITLE
sub emitter particle not displayed

### ISSUE THREAD

**Issue by agrobost** [mob-sakai/ParticleEffectForUGUI#112]
**Describe the bug**
I have a bug with sub emitters. In prefab editing it works well, but when is launch the game, my sub emitters aren't displayed. When I change the sub emitters position, they are displayed.

**To Reproduce**
1/ Create material Shader: mobile/particles/alpha blended
2/ Create UI/Particle system in the scene
3/ Adding sub emitter triggered by particule death
4/ Start the game
(I am using a canvas overlay)
![GIF 01-11-2020 19-53-26](https://user-images.githubusercontent.com/14184466/97811602-fca29280-1c7b-11eb-92e5-989b4b6fb257.gif)

**Environment (please complete the following information):**
 - Version 3.1.0
 - Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac)
 - Unity version: 2019.4.0f1
 - Build options:  EDITOR

**Comment by mob-sakai** [comment]
@agrobost 
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

**Comment by yanghu28** [comment]
I see same issue, today  I  test the new Tools, it need change effect  and image position, it seem to be work

**Comment by agrobost** [comment]
In fact it's a bug on my side, because I modify the anchors (animation purpose) of my prefab just after having instantiated it. It works if I start the animation after the OnStart method.
