### ISSUE TITLE
look at picture

### ISSUE THREAD

**Issue by yanghu28** [mob-sakai/ParticleEffectForUGUI#113]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yanghu28** [comment]
![image](https://user-images.githubusercontent.com/19767759/98317694-f44dad00-2017-11eb-878d-e8bc76e93d0f.png)
![image](https://user-images.githubusercontent.com/19767759/98317729-04658c80-2018-11eb-8a61-584838533224.png)

**Comment by yanghu28** [comment]
![image](https://user-images.githubusercontent.com/19767759/98317885-5c9c8e80-2018-11eb-9b9a-58149ad02dad.png)

**Comment by mob-sakai** [comment]
Yes, CanvasRenderer supports **up to 8 submeshes (i.e. 8 materials).**
If you need more submeshes than that, you can split them into multiple UIParticle.

**Comment by mob-sakai** [comment]
If you need more help, please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue.

**Comment by yanghu28** [comment]
![image](https://user-images.githubusercontent.com/19767759/98356618-d35c7a80-205e-11eb-898d-b2e626df1563.png)
this is 6 same materials。total is 36

**Comment by mob-sakai** [comment]
Let me again.
**Please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue.**
Your issues do not have enough information to fix.

**Comment by sp-alberto-uriarte** [comment]
I had the same issue and I solve it by splitting into multiple UIParticle as you suggested.
But I think @yanghu28 has a point, even if in the Rendering Order we have more than 8 submeshes some of them can use the same material (as in his last screenshot). So maybe the submeshes can be merged by material?

**Comment by mob-sakai** [comment]
Fixed in v3.3.0.
Use `Shrink By Material` option and call `UIParticle.RefreshParticles()` after adding ParticleSystem.
