### ISSUE TITLE
Error on build in Unity 2019.3.11-15

### ISSUE THREAD

**Issue by korober** [mob-sakai/ParticleEffectForUGUI#114]
Hello, I get error on project build:

> The same field name is serialized multiple times in the class or its parent class. This is not supported: Base(MonoBehaviour) m_Maskable
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

I think the problem in UIParticle.cs, line 41-45:

`#if !UNITY_2019_4_OR_NEWER`
`        [SerializeField]`
`        private bool m_Maskable = true;`
`#endif`

**To Reproduce**
1) Install plugin on empty project (unity 2019.3.15f1)
2) build it for Android. 

**Expected behavior**
No error messages on build 

**Screenshots**
![ugui_bug](https://user-images.githubusercontent.com/12730722/98520052-24a97b80-22a4-11eb-89c5-5bff3072c8b9.png)

**Environment (please complete the following information):**
 - Unity version: **2019.3.15f1**
 - Build Platform: Android (ios not tested)
 - Build options: [IL2CPP, .Net standard 2.0]

**Comment by mob-sakai** [comment]
Hi @korober 
Thank you for your reporting!

**Comment by mob-sakai** [comment]
In Unity 2019.3.11, the `SerializeField` attribute was added to this field.
https://unity3d.com/jp/unity/whats-new/2019.3.11
