### ISSUE TITLE
Compatibility with other components that implement <IMaterialModifier>

### ISSUE THREAD

**Issue by ltccss** [mob-sakai/ParticleEffectForUGUI#115]
https://github.com/mob-sakai/ParticleEffectForUGUI/blob/06d8fae58ffc165299b7a6b32c181b2c19fae1ae/Scripts/UIParticle.cs#L220

Currently `UIParticle` overrides the method `UpdateMaterial`, but dose not handle the property `materialForRendering` as the super class does, which leads to that those who implement the interface `IMaterialModifier` don't work

**Comment by mob-sakai** [comment]
@ltccss 
Thank you for the feature request!
