### ISSUE TITLE
probelm when use this component with SoftMask

### ISSUE THREAD

**Issue by ltccss** [mob-sakai/ParticleEffectForUGUI#116]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Describe the bug**
When there is a nested Particle, only one particle will be displayed if I make it softmaskable

**To Reproduce**
Here is the sample project
[UIParticleTest.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/5545511/UIParticleTest.zip)
When you open it, then
1. Open the `SampleScene`
2. Select the `Particle System` node ( the parent one), and play it

**Expected behavior**
Both 2 particle (red and white) should be displayed in the screen, and be clipped well

**Screenshots**

**Environment (please complete the following information):**
 - Platform: windows 7
 - Unity version: 2018.4.21f1

**Comment by mob-sakai** [comment]
Try to use `SoftMask 1.0.0-preview.14`.

```
{
  "dependencies": {
    "com.coffee.softmask-for-ugui": "https://github.com/mob-sakai/SoftMaskForUGUI.git#1.0.0-preview.14",
    ...
  },
}
```

![](https://user-images.githubusercontent.com/12690315/99324874-7495cd00-28b8-11eb-83dd-cfa9bc5cd68e.gif)

**Comment by mob-sakai** [comment]
Yes.
SoftMask does not support multiple materials...

**Comment by ltccss** [comment]
I've seen.... 

In SoftMaskable, it releases the cached material at once when receive a new material during `GetModifiedMaterial`o((⊙﹏⊙))o.

The true problem may be it's hard to know if the cached material should be replaced or appended?

**Comment by mob-sakai** [comment]
NOTE: It may be supported by my new Mask package which will be released soon. :)

**Comment by mob-sakai** [comment]
Now supported by [SoftMask v2](https://github.com/mob-sakai/SoftMaskForUGUI)!

[UIAdditive (SoftMaskable).shader.zip](https://github.com/user-attachments/files/16359244/UIAdditive.SoftMaskable.shader.zip)
