### ISSUE TITLE
Spawning Particle Prefabs. Rendering stops on older ones after 4+.

### ISSUE THREAD

**Issue by npicouet** [mob-sakai/ParticleEffectForUGUI#117]
**Describe the bug**
Spawning multiple particle prefabs. Each have their own UI Particle renderer. 
Each system destroys itself when complete.
Each system is a texture sheet animation using a multiple mode packed image.
After spawning 4-5+, the rendering on older ones starts failing.

**To Reproduce**
1. Spawn particle prefabs from code.
2. Each prefab should have a particlesystem and uiparticle, and callback on done to destroy, as well as set up to be a texture sheet animation with multiple mode packed image.
3. After spawning multiple, rendering fails randomly.

**Expected behavior**
Rendering should be self contained on each prefab and never fail when others are destroying.

**Environment (please complete the following information):**
Unity 2019.4.12f1, Mac OSX, Editor
IL2CPP, .Net 4, Standard Pipeline
Latest release (3.2.0)

**Comment by mob-sakai** [comment]
@npicouet 
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

**Comment by npicouet** [comment]
Here is a minimal project, I was able to recreate it in here.
[Download Link](https://gofile.io/d/ynwt9h)

**Comment by mob-sakai** [comment]
Fixed in `v3.3.0`
