### ISSUE TITLE
Particles sort not correct if it is multiple children

### ISSUE THREAD

**Issue by LacusCon** [mob-sakai/ParticleEffectForUGUI#119]
**Describe the bug**
Top Uiparticle's Refresh can't set correct sort if have multiple children

**To Reproduce**
Example: 
particles_structure(same renderQueue&sortingLayerID&sortingOrder):
root_particleSystem--sub01--- sub_011
......................................|................|---sub_012
......................................|--sub02--- sub_021 
.......................................................|--- sub_022
              
**Expected behavior**
   need top uiparticle rendering order sort:
       root->sub01->sub_011->sub_012->sub02->sub021->sub022
   current sort:
      root->sub021->sub022->sub01->sub011->sub012->sub02

**Screenshots**

**Environment (please complete the following information):**
 - Platform: [e.g. Editor(Windows/Mac), Android]
 - Unity version: [e.g. 2019.4.9f1]

**Comment by mob-sakai** [comment]
@LacusCon 
Thank you for your reporting!
