### ISSUE TITLE
_cachedPosition defaults to localPosition

### ISSUE THREAD

**Issue by danhines** [mob-sakai/ParticleEffectForUGUI#121]
I noticed that UIParticle._cachedPosition is being set to transform.localPosition inside UIParticle.OnEnable, whereas inside UIParticleUpdater.BakeMesh it is compared (& then set) to particle.transform.position. This seems to sometimes manifest as particles temporarily appearing at the wrong position if a particle system is moved while inactive and then re-enabled (I only saw this when m_IgnoreCanvasScaler was true).

**Comment by mob-sakai** [comment]
@danhines 
Thank you for your reporting!
