### ISSUE TITLE
Submeshes can't over 8

### ISSUE THREAD

**Issue by LacusCon** [mob-sakai/ParticleEffectForUGUI#122]
NOTE: 
Now version(3.3.0) Just use root uiparticle.  
but Unity be warning[Mesh '' has more than the 8 submeshes. Extra submeshes will be ignored.] if prefab is huge.

**Environment (please complete the following information):**
 - Unity version: [e.g. 2019.4.9f1]

**Comment by mob-sakai** [comment]
@LacusCon 
Thank you for your reporting!

**Comment by adamsw** [comment]
This issue has not been resolved in version 3.3.2 and version 3.3.9
Now version(3.3.2) Just use root uiparticle.
but Unity be warning
Mesh '' has more than the 8 submeshes. Extra submeshes will be ignored.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Coffee.UIExtensions.UIParticleUpdater:Refresh (Coffee.UIExtensions.UIParticle) (at Assets/ThirdParty/UIParticle/Scripts/UIParticleUpdater.cs:80)
Coffee.UIExtensions.UIParticleUpdater:Refresh () (at Assets/ThirdParty/UIParticle/Scripts/UIParticleUpdater.cs:49)
UnityEngine.Canvas:SendWillRenderCanvases ()

**Comment by LaoLeo** [comment]
Version 3.3.10 also has this issue.I had write code to test it. And found that the Warning is the limit of Unity.
```
using UnityEngine;
using UnityEngine.UI;

public class MeshCombineForCanvas : Graphic 
{
    private CanvasRenderer m_canvasRenderer ;
    private Mesh m_mesh ;

    protected override void Start()
    {
        if (!m_canvasRenderer) {
            m_canvasRenderer = gameObject.GetComponent<CanvasRenderer>() ?? gameObject.AddComponent<CanvasRenderer>();
        }
        m_mesh = CreateMesh();
        // CombineMeshes(m_mesh, 8);
        CombineMeshes(m_mesh, 10);
        m_canvasRenderer.SetMesh(m_mesh);
    }

    private Mesh CreateMesh()
    {
        Vector3[] vertices = new Vector3[4];
        vertices[0] = new Vector3(0,0,0);
        vertices[1] = new Vector3(0,0,1);
        vertices[2] = new Vector3(1,0,1);
        vertices[3] = new Vector3(1,0,0);
        int[] triangles = new int[6];
        triangles[0] = 0;
        triangles[1] = 1;
        triangles[2] = 2;
        triangles[3] = 2;
        triangles[4] = 3;
        triangles[5] = 0;
        Mesh mesh = new Mesh();
        mesh.vertices = vertices;
        mesh.triangles = triangles;
        return mesh;
    }

    private void CombineMeshes(Mesh meshContainer, int count)
    {
        CombineInstance[] src = new CombineInstance[count];
        for (int i=0; i<count; i++)
        {
            Mesh mesh = CreateMesh();
            CombineInstance inst = new CombineInstance{ mesh = mesh };
            src[i] = inst;
        }
        meshContainer.CombineMeshes(src, false, false) ;
    }
}
```
warning of unity:
```
Mesh '' has more than the 8 submeshes. Extra submeshes will be ignored.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
```

**Comment by zyowo** [comment]
+1 when use `Sword slashes PRO 2.1.0` with UIParticle, Unity warns `Mesh '' has more than the 8 submeshes. Extra submeshes will be ignored.` when particles play.

**Comment by mob-sakai** [comment]
ref: #152
