### ISSUE TITLE
UIParticles working on Android but not on iOS

### ISSUE THREAD

**Issue by Dakshesh10** [mob-sakai/ParticleEffectForUGUI#123]
There are two sets of particles (one in splash screen and one in main menu) I have used in Canvas with UIParticles component. Both of them work fine on editor (on both Windows editor and Mac), but in the iOS build, particles on Splash are never visible, and the one on Main menu which also has trail component enabled on it, doesn't render correctly on iOS. The trails of this particle is missing. And the most weird part is that these particles work fine on iPhone 5 but any iOS device later than that, doesn't work. I cant' seem to wrap my head around this, as I have tried all possible permutations of the UIParticles script settings, but nothing changes. What could be the issue here? It would be very helpful if someone can point me in the right direction.

**Comment by iancummingsglu** [comment]
Same thing happening for me...

**Comment by mob-sakai** [comment]
@Dakshesh10 @iancummingsglu 
Thank you for your reporting.
I would like to know more about this issue.

**Environment (please complete the following information):**
 - Version [e.g. 3.3.0]
 - Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL]
 - Unity version: [e.g. 2018.2.8f1]
 - Build options: [e.g. IL2CPP, .Net 4.x, URP, XCode 12, ...]

Could you please attach **a minimal project** *(included `Assets`, `Packages` and `ProjectSettings` directories)* that reproduces the issue?

**Comment by topher-mcbearslayer** [comment]
I'm also having the same issue, but only with two (2) of the eight (8) Particle Systems (prefabs) I use.  Works in Unity Editor + Android, doesn't work on modern iPhone.

**Comment by mob-sakai** [comment]
@topher-mcbearslayer 
Thank you for your reporting.
I would like to know more about this issue.

**Environment (please complete the following information):**
 - Version [e.g. 3.3.0]
 - Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL]
 - Unity version: [e.g. 2018.2.8f1]
 - Build options: [e.g. IL2CPP, .Net 4.x, URP, XCode 12, ...]

Could you please attach **a minimal project** *(included `Assets`, `Packages` and `ProjectSettings` directories)* that reproduces the issue?

**Comment by nj20** [comment]
Same here. Facing the same issue.

**Comment by mob-sakai** [comment]
@nj20 
Thank you for your reporting.
I would like to know more about this issue.

Environment (please complete the following information):

Version [e.g. 3.3.0]
Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL]
Unity version: [e.g. 2018.2.8f1]
Build options: [e.g. IL2CPP, .Net 4.x, URP, XCode 12, ...]
Could you please attach a minimal project (included Assets, Packages and ProjectSettings directories) that reproduces the issue?

**Comment by nj20** [comment]
Platform: IOS
Unity Version: 2019.4.11f1
Build Options: URP
Version: 3.3.0

**Comment by mob-sakai** [comment]
@nj20 
Thanks.
Please attach a minimal project (included Assets, Packages and ProjectSettings directories) that reproduces the issue.
It will help to solve the issue.

**Comment by mob-sakai** [comment]
Since there has been no new discussion for a long time, this issue was closed.
 If the same issue arises, please re-open this issue.

**Comment by CodeMasterYi** [comment]
[SimpleProject.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/7034075/SimpleProject.zip)
Emmm...Maybe I'm facing the same issue. This is what I use in my project.

Version: 3.3.8
Platform: iOS
Unity version: 2018.4.21f1
Build options: IL2CPP, .Net 4.x, Default Render Pipeline, XCode 12

I would like to re-open the issue.~ Is it OK?

**Comment by CodeMasterYi** [comment]
@mob-sakai 
The same fx works well on Android, but not on iOS.

**Comment by mob-sakai** [comment]
@CodeMasterYi 
I would like to know more about this issue.
I do not know how to use your FX and your project settings.
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by CodeMasterYi** [comment]
I'm sorry for disturbing you. We find that the component `UIParticle` is stripped on iOS(because managed-stripping-code is enabled when use IL2CPP). We fix it now. @mob-sakai

**Comment by mob-sakai** [comment]
👍
