### ISSUE TITLE
Custom Vertex Streams not working

### ISSUE THREAD

**Issue by w963963555577** [mob-sakai/ParticleEffectForUGUI#124]
I write customized shader, and enable particlesystem of "Custom Vertex Streams", but the Particle model vertex data is not updated.

 - Unity version: [e.g. 2019.4.10f1]

**Comment by mob-sakai** [comment]
@w963963555577 
Thank you for your reporting!
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

**Comment by w963963555577** [comment]
@mob-sakai 
OKay, please wait for me.

**Comment by w963963555577** [comment]
Here's a repo project
https://drive.google.com/u/1/uc?id=1PdWl64bcy9WVMALAhngwlnMu2hd7B3JJ&export=download

And a little screenshot in scene.
![image](https://user-images.githubusercontent.com/17163906/104994782-17f19280-5a60-11eb-8f97-cf82db2bdf84.png)

I create 【ParticleVelocityColor_Original】 object, and clone to 【UIParticle/ParticleVelocityColor_UI】, but looks different.

Should be unsupported 【Custom Vertex Streams】
![image](https://user-images.githubusercontent.com/17163906/104995257-f513ae00-5a60-11eb-8149-996ee5fecfdb.png)

Thank you.

**Comment by mob-sakai** [comment]
@w963963555577 
Set `Canvas.AdditionalshaderChannels` to `TexCoord1` instead of `Nothing`.

![image](https://user-images.githubusercontent.com/12690315/105930718-5e14aa80-608d-11eb-8677-96608617993c.png)
![image](https://user-images.githubusercontent.com/12690315/105930821-7e446980-608d-11eb-8969-7e94e2f52a62.png)

**Comment by w963963555577** [comment]
Oh...
It’s my mistake, thanks!
