### ISSUE TITLE
Particles hole-y with post processing

### ISSUE THREAD

**Issue by delgelato** [mob-sakai/ParticleEffectForUGUI#126]
**Describe the bug**
With post processing enabled in the camera, the particles get hole-y

**To Reproduce**
1. Add UIParticle
2. Get the PostProcessing from UPM
3. Attach PostProcessing layer to the camera
4. Play

**Screenshots**
![image](https://user-images.githubusercontent.com/9655759/104878434-e9f44b80-5996-11eb-8ce7-bc2786a0ec6c.png)

**Environment (please complete the following information):**
 - 3.3.0
 - Unity version: 2020.1.17f1
 - Build options: Standard RP

**Additional context**
Happens only in play mode. In edit mode, in the game window, things look normal

**Comment by mob-sakai** [comment]
@delgelato 
Thank you for your reporting!
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

**Comment by delgelato** [comment]
Here's a repro project

I noticed that the DefaultParticle material works fine, but a material with Particle/StandardUnlit is not (and many other shaders)

https://drive.google.com/file/d/1utjsIMhA7-KnkzRNvftY37rZAbhYqQ4C/view?usp=sharing

**Comment by mob-sakai** [comment]
#56
> This only happens when Canvas.RenderMode = Screen Space - Overlay.
Maybe, Default-ParticleSystem material and Particle/Standard Unlit shader do not support Screen Space - Overlay.

It looks like `z-buffer` is the cause. Other UI elements have the same problem.
