### ISSUE TITLE
consumption is too high，this is 15 Effects in one UIParticle.cs

### ISSUE THREAD

**Issue by yanghu28** [mob-sakai/ParticleEffectForUGUI#129]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yanghu28** [comment]
![image](https://user-images.githubusercontent.com/19767759/105956631-10ab3400-60b3-11eb-87f3-ad14965da46c.png)

**Comment by yanghu28** [comment]
![Uploading image.png…]()

**Comment by yanghu28** [comment]
![image](https://user-images.githubusercontent.com/19767759/105956883-68499f80-60b3-11eb-9197-6b38482fbd20.png)

**Comment by yanghu28** [comment]
![image](https://user-images.githubusercontent.com/19767759/105956935-77c8e880-60b3-11eb-8e15-97d5f925e3a8.png)

**Comment by yanghu28** [comment]
this is my setting.
![image](https://user-images.githubusercontent.com/19767759/105957187-d5f5cb80-60b3-11eb-9286-5331bc267575.png)

**Comment by mob-sakai** [comment]
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

**Comment by mob-sakai** [comment]
@yanghu28

**Comment by mob-sakai** [comment]
@yanghu28 
It will help to solve the issue.

**Comment by mob-sakai** [comment]
Since there has been no new discussion for a long time, this issue was closed.
 If the same issue arises, please re-open this issue.

**Comment by Diamond91** [comment]
![profile](https://user-images.githubusercontent.com/61910437/115524681-fa330400-a2c0-11eb-9fc7-e2453059b60c.png)

![demo](https://user-images.githubusercontent.com/61910437/115524925-349ca100-a2c1-11eb-96c5-d71ff3b140d1.png)

import sample demo,With UIParticle keep enabled,copy multiple UIParticle_Demo_Effect_Root.

Thank you for visiting my problem

**Comment by mob-sakai** [comment]
@Diamond91 
Thank you for your cooperation!

**Comment by mob-sakai** [comment]
2 improvements on next release:
- Removed the color space modifier. This process is too heavy.
- Instead of `Stack.Contains`, use `HashSet.Contains`.

**Comment by mob-sakai** [comment]
Please try to use `3.3.8` :smile:

**Comment by Diamond91** [comment]
Thanks for fix. I used 3.3.8 in my project now. I have many different UI effects in the scene.

Now the problem is Bake Mesh cost too much time.

![image](https://user-images.githubusercontent.com/61910437/123782174-9d2e7c80-d907-11eb-8682-eb389204d70c.png)

Thanks

**Comment by smallrainf** [comment]
邮件已经收到......谢谢
