### ISSUE TITLE
v1.1.0 Texture Sheet Animation scaling problem 

### ISSUE THREAD

**Issue by soimy** [mob-sakai/ParticleEffectForUGUI#14]
env: Unity 2018.2.17f1
When using `Screen Space - Overlay` mode, any `Grid` mode texture sheet animation is extremely small and need `UISprite.scale` set to over 40 to get almost the same size.

**Comment by mob-sakai** [comment]
Hi @soimy 
Thank you for your report!

**Comment by mob-sakai** [comment]
I would like to know more information on this issue.
Can you submit a reproducible project for this issue?

**Comment by soimy** [comment]
Thanks for the quick feed back. I'll post more info after a deadline run :)
