### ISSUE TITLE
Particle Material/Color not visible in Play mode

### ISSUE THREAD

**Issue by amitsri20** [mob-sakai/ParticleEffectForUGUI#146]
I have added the UI particle as instructed. I can see particles behaving fine in editor view but when I play it color becomes black. Can you please suggest?

<img width="861" alt="Screenshot 2021-02-06 at 11 51 47 PM" src="https://user-images.githubusercontent.com/4771159/107126639-11c03a80-68d7-11eb-9945-adde7b5528af.png">

<img width="553" alt="Screenshot 2021-02-06 at 11 52 01 PM" src="https://user-images.githubusercontent.com/4771159/107126646-1684ee80-68d7-11eb-9c2e-d628fe0b0b9b.png">

**Comment by mob-sakai** [comment]
@amitsri20 
https://github.com/mob-sakai/ParticleEffectForUGUI/discussions/133

> This only happens when Canvas.RenderMode = Screen Space - Overlay.
> Maybe, Default-ParticleSystem material and Particle/Standard Unlit shader do not support Screen Space - Overlay.

**Comment by mob-sakai** [comment]
Since there has been no new discussion for a long time, this issue was closed.
 If the same issue arises, please re-open this issue.

**Comment by amitsri20** [comment]
Yes, changing to Screen Space - Camera did work. Thanks!

**Comment by mob-sakai** [comment]
:smile: :+1:
