### ISSUE TITLE
3.3.3 - ParticleSystem creates Particles in wrong position during prewarm or ParticleSystem.Simulate() if UIParticle Component scale is changed at runtime

### ISSUE THREAD

**Issue by topher-mcbearslayer** [mob-sakai/ParticleEffectForUGUI#147]
**Describe the bug**
Particles are drawn in the wrong position during prewarm / ParticleSystem.Simulate() if the UIParticle component scale is changed at runtime.  

If UIParticle component scale is not changed, prewarm / ParticleSystem.Simulate() functions correctly.

Only prewarm / ParticleSystem.Simulate() is affected. Normal particle emission is not affected even if UIParticle component scale is changed at runtime.

**To Reproduce**
1. At runtime, instantiate two (2) Particle Systems of the same type at different coordinates, ensuring that the Particle System prefab has "Prewarm" enabled
2. Change the scale of one (1) of the Particle Systems to 2x
3. The scaled Particle System will create its prewarm Particles in the incorrect position, the unscaled Particle System will correctly create its Particles in the correct position, and both Particle Systems will function normally after prewarm is complete 

**Expected behavior**
Scaled Particle Systems should prewarm correctly.

**Screenshots**
Here is a scene in my game where two (2) Particle Systems of the same type are instantiated at runtime (smoke coming out of vent on street).  The Particle System on left at runtime is scaled to 2x, the Particle System on right is untouched.  Left Particle System scales up but draws its prewarm Particles offscreen above (bad/incorrect), Particle System on right creates its prewarm Particles correctly.

After prewarm, BOTH Particle Systems (scaled and unscaled) function normally and as expected. Only prewarm is affected.

Link to screenshots, first screenshot is prewarm (shows bad behaviour), second screenshot is post-prewarm (all is working/expected).
https://imgur.com/a/v3AYLUf

**Environment (please complete the following information):**
 - Version 3.3.3
 - Platform: Editor, Windows 10
 - Unity version: 2019.4.19f
 - Build options: N/A (Editor)
 
Images also attached, first image shows prewarm (shows bad behaviour), second image shows post-prewarm (all is working):

![AfterScale_Prewarm](https://user-images.githubusercontent.com/54777304/107403678-67613680-6ad3-11eb-8c0a-3faba2478f52.jpg)

![AfterScale_Normal](https://user-images.githubusercontent.com/54777304/107403676-66c8a000-6ad3-11eb-931e-214e2a453a34.jpg)

**Comment by mob-sakai** [comment]
@topher-mcbearslayer 
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

**Comment by mob-sakai** [comment]
@topher-mcbearslayer
It will help to solve the issue.

**Comment by topher-mcbearslayer** [comment]
Still an issue in 3.3.4.  Working on making you a project now.

ONLY occurs on Particle Systems that have their scale changed.

**Comment by topher-mcbearslayer** [comment]
Sorry for how long this took. First time I've had to share a Unity project.  Made project as small as I can.  Simply run and use the two buttons.

Button 1: Makes a pre-warmed vent smoke particle at coordinates 300x, 300y, at scale 1.0f.  This works as expected.
Button 2: Makes a pre-warmed vent smoke particle at coordinates 300x, 300y, at scale 2.0f.  This does NOT work.  It scales to 2.0f but the pre-warmed particles are emitted far above where they are supposed to. 

Please let me know if I did not package the project correctly.

https://www.firerabbit.com/ParticleTest.zip

**Comment by mob-sakai** [comment]
@topher-mcbearslayer 
Thank you for your cooperation :smile: :+1:

**Comment by mob-sakai** [comment]
I have implemented a draft of the fix.

@topher-mcbearslayer
Could you try this?
Find the manifest.json file in the Packages folder of your project and add a line to dependencies field to install.

"com.coffee.ui-particle": "https://github.com/mob-sakai/ParticleEffectForUGUI.git#develop",
If it works well, it will be released soon. 👍

**Comment by mob-sakai** [comment]
Oh, I forgot.
Please enable ParticleSystem.prewar in the prefab.

**Comment by topher-mcbearslayer** [comment]
Ooh, closer!  I turned prewarm on the prefab itself again, removed the code to manually prewarm, and updated to your latest development release.  The pre-instantiated Particle Systems are working again! Unfortunately if the Particle Systems are cleared and recycled the same issue happens again to scaled Particle Systems.

I've updated the Test project with the scenario that shows the problem.

1. Create 3 Particle Systems (scaled or unscaled, doesn't matter)

2. Clear Particle Systems using the new button
 
3. Create a scaled Particle

4. Scaled Particle is prewarming in the wrong position again :(

Link to updated Test project: [Particle Test Project #2](https://www.firerabbit.com/ParticleTest2.zip)

I -really- appreciate you looking into this.  If there's anything I can do to help please let me know.

**Comment by mob-sakai** [comment]
👍

**Comment by mob-sakai** [comment]
I fixed it again. Please try this:
`"com.coffee.ui-particle": "https://github.com/mob-sakai/ParticleEffectForUGUI.git#e3f42d747a7fd973b5813cc72a9444943a6c3ad0",`

**Comment by topher-mcbearslayer** [comment]
Everything is working in Editor!  Tested in the Test Project and also my game.  I will confirm that it is working on Android and iOS devices by tomorrow.  THANK YOU @mob-sakai !

**Comment by mob-sakai** [comment]
@topher-mcbearslayer 
Does it work on Android and iOS devices?

**Comment by topher-mcbearslayer** [comment]
> @topher-mcbearslayer
> Does it work on Android and iOS devices?

Sorry, I confirmed working on iOS yesterday but was having issues with Android build pipeline.  Just confirmed Android works.  So working on device for both!

Thanks so much again, @mob-sakai .  I'm pretty to release now :)
