### ISSUE TITLE
Canvas.scaleFactor not take into account

### ISSUE THREAD

**Issue by soimy** [mob-sakai/ParticleEffectForUGUI#15]
env: Unity 2018.2.17f1
When using `Screen space - Overlay` and UI scale Mode `Scale with screen size`, `Canvas.scaleFactor` should take into account inside `UpdateMesh()`

**Comment by mob-sakai** [comment]
Hi @soimy 
Thank you for your report!

**Comment by mob-sakai** [comment]
I will fix this issue in the next release.

**Before:**
![](https://user-images.githubusercontent.com/12690315/49732148-f8081600-fcc0-11e8-8a35-ee71fa62e06f.gif)

**After:**
![](https://user-images.githubusercontent.com/12690315/49732152-fa6a7000-fcc0-11e8-9f6b-62acb4157c2c.gif)

**Comment by mob-sakai** [comment]
When I test it, it does not work well if ParticleSystem.ScalingMode is set to ”Hierarchy".
This is because it is affected by the scale of Canvas.

**Comment by mob-sakai** [comment]
I found a way to scale well in most cases!
It scales well even if you change the following parameters:
* Camera.FieldOfView
* CanvasScaler.MatchWidthOrHeight
* Canvas.PlaneDistance
![](https://user-images.githubusercontent.com/12690315/49866926-6c22f500-fe4c-11e8-8393-d5a546e9e2d3.gif)

**Comment by mob-sakai** [comment]
The issue will be fixed in the next release:)
