### ISSUE TITLE
Particles overlap in the end of ps duration

### ISSUE THREAD

**Issue by momonkey18** [mob-sakai/ParticleEffectForUGUI#151]
Hi!

For some reason particles overlap for a frame in the end of Particle System duration. It's noticeable with both AB and Additive materials in game mode but not in editor mode.

For example, here: It supposed to be a looping particle with duration 2.5 seconds and the same 2.5 seconds lifetime

https://user-images.githubusercontent.com/79794749/109420643-a99bda80-79e4-11eb-80b0-4dd6f74b98d0.mp4

I tried to make lifetime 2.49 seconds, but now it disappears for a frame

https://user-images.githubusercontent.com/79794749/109420720-03040980-79e5-11eb-8ae5-c48127daba31.mp4

And here's an example for additive shader

https://user-images.githubusercontent.com/79794749/109420872-c1c02980-79e5-11eb-9c51-91bbc0f99297.mp4

My version of Unity is 2019.4.1f1

Thank you!

**Comment by mob-sakai** [comment]
I would like to know more about this issue.

**Environment (please complete the following information):**
 - Version [e.g. 1.0.0]
 - Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL]
 - Unity version: [e.g. 2018.2.8f1]
 - Build options: [e.g. IL2CPP, .Net 4.x, LWRP]

Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

**Comment by mob-sakai** [comment]
Since there has been no new discussion for a long time, this issue was closed.
 If the same issue arises, please re-open this issue.
