### ISSUE TITLE
display is a ALPHA, normal is block color

### ISSUE THREAD

**Issue by yingnierxiao** [mob-sakai/ParticleEffectForUGUI#153]
**Describe the bug**

**To Reproduce**
1.create a particle
2.change start color  rgba 0,0,0,255
3.display is a ALPHA, normal is block color

![image](https://user-images.githubusercontent.com/3435706/111134974-1acbb800-85b7-11eb-8fbb-2963c4dd3711.png)

normal
![image](https://user-images.githubusercontent.com/3435706/111135179-4f3f7400-85b7-11eb-84a2-1e5ca9992c1c.png)

**Environment (please complete the following information):**
 - Version [e.g. 1.0.0]
 - Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL]
 - Unity version: [e.g. 2019.4.12f1]
 - Build options: [e.g. IL2CPP, .Net 4.x, LWRP]

**Additional context**

**Comment by mob-sakai** [comment]
@yingnierxiao 
This is correct behavior.
A additive shader (eg. `UI/Additive`) outputs the color of the background when `src.rgb = (0,0,0)`.

`out.rgb = src.rgb * src.a + dst.rgb`

On the other hand, a blend shader (eg. `Legacy Shaders/Particles/Alpha Blended`) outputs:

`out.rgb = src.rgb * src.a + dst.rgb * (1 - src.a)`
