### ISSUE TITLE
why is sortingfudge descended?

### ISSUE THREAD

**Issue by PhilianZ** [mob-sakai/ParticleEffectForUGUI#154]
` // Z position & sortingFudge: descending
                var aTransform = a.transform;
                var bTransform = b.transform;
                var aPos = tr.InverseTransformPoint(aTransform.position).z + aRenderer.sortingFudge;
                var bPos = tr.InverseTransformPoint(bTransform.position).z + bRenderer.sortingFudge;
                if (!Mathf.Approximately(aPos, bPos))
                    return (int) Mathf.Sign(bPos - aPos);`
This piece seems order-reversal. As I know, the smaller the sortingFudge, the further the particle is from the camera, so the frontier in the rendering queue. Then, why use bPos minus aPos?

**Comment by mob-sakai** [comment]
The smaller `Sorting Fudge`, the more it will be displayed in front. (blue particles)

![Sep-03-2021 09-39-40](https://user-images.githubusercontent.com/12690315/131933436-3fe43707-4e95-44c6-be90-9bcf834adf4c.gif)
