### ISSUE TITLE
"Ignore Canvas Scaler" is confusing.

### ISSUE THREAD

**Issue by jungsooPark-dev** [mob-sakai/ParticleEffectForUGUI#156]
the field "Ignore Canvas Scaler" seems like it ignores canvas scale when enabled, but it works the opposite.
it applies canvas scale to particle mesh, so it's more like "Apply Canvas Scaler"
https://github.com/mob-sakai/ParticleEffectForUGUI/blob/24d32d8441eb27da88e462a44935ab78e9172dbb/Scripts/UIParticleUpdater.cs#L143-L145

but it does the opposite in transform scale.
I assume that it is meant to ensure "Apply Canvas Scaler" work properly when particle scale is set to hierachy mode.
(because scale will be applied in `BakeMesh`)
https://github.com/mob-sakai/ParticleEffectForUGUI/blob/24d32d8441eb27da88e462a44935ab78e9172dbb/Scripts/UIParticleUpdater.cs#L90-L97

how can i use "Ignore Canvas Scaler" option correctly?
is it meant to be enabled when i want to apply canvas scale to my particle?

**Comment by mob-sakai** [comment]
@jungsooPark-dev 
Sorry for my late reply.
However, I forgot what I created this feature for. lol

**Comment by mob-sakai** [comment]
Note: This option will be removed in the next major version.
