### ISSUE TITLE
[RESOLVED] Problem with Unity 2021

### ISSUE THREAD

**Issue by omid3098** [mob-sakai/ParticleEffectForUGUI#159]
Having multiple particles as child of another particle system works fine on Unity 2020 but when I try to use this on 2021 (tested on 2021.1.3f1, 2021.1.7f1) results are not the same with world particles:
![image](https://user-images.githubusercontent.com/6388730/119258380-32f32100-bb7e-11eb-8c34-4c4aa41e1247.png)

I've noticed these misbehaviors:
 - Texture sheet grid does not work
 - All child particle systems will have the parent shader

Hierarchy example:
![image](https://user-images.githubusercontent.com/6388730/119258500-bb71c180-bb7e-11eb-947f-2d359d03d3d3.png)

**To Reproduce**
1. Create a particle system with multiple child particle systems
2. Convert to UiParticle
3. Play

**Screenshots**

**Environment (please complete the following information):**
 - Version 3.3.6
 - Platform: Editor(Windows)
 - Unity version: 2021.1.7f1
 - Build options: [Mono, .Net Standard2.x, Builtin RP]

The exact same particle system setup in a same environment (Version, Platform and Build options) works fine in Editor 2020.3.6f1

**Comment by davislin** [comment]
I have the same problem, I guess it should be related to "Texture sheet Animation", all of them have problems

**Comment by davislin** [comment]
![image](https://user-images.githubusercontent.com/9277287/120262994-65fb8a00-c2cd-11eb-9287-2fcce22c6cb2.png)
![image](https://user-images.githubusercontent.com/9277287/120263015-73b10f80-c2cd-11eb-84bf-5025f43924d5.png)
![image](https://user-images.githubusercontent.com/9277287/120263036-81ff2b80-c2cd-11eb-92f2-0e9107bf66ac.png)
I distributed the UIParticle component to all the child objects and it returned to normal. The parent object does not control all particles.

**Comment by mob-sakai** [comment]
@omid3098 @davislin 
Sorry for my late reply.
I would like to know more about this issue.
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

**Comment by davislin** [comment]
> @omid3098 @davislin
> Sorry for my late reply.
> I would like to know more about this issue.
> Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

[ParticleEffectForUGUI.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/6613255/ParticleEffectForUGUI.zip)

there are 2 scenes in project, 3D is default, 2D is Apply UIParticle.

**Comment by mob-sakai** [comment]
This is a bug in Unity.
I have sent a bug report. 😄

**Comment by mob-sakai** [comment]
IssueTracker: https://issuetracker.unity3d.com/issues/the-first-submesh-texture-is-overridden-for-all-other-submeshes-in-the-canvasrenderer-even-when-multiple-materials-are-assigned

**Comment by mob-sakai** [comment]
> IssueTracker: https://issuetracker.unity3d.com/issues/the-first-submesh-texture-is-overridden-for-all-other-submeshes-in-the-canvasrenderer-even-when-multiple-materials-are-assigned

Update: The issue has been fixed in 2022.1.X and planned for 2021.1.X, 2021.2.X.

**Comment by mob-sakai** [comment]
> IssueTracker: https://issuetracker.unity3d.com/issues/the-first-submesh-texture-is-overridden-for-all-other-submeshes-in-the-canvasrenderer-even-when-multiple-materials-are-assigned

Update: 
- Fixed in 2022.1.X
- Fixed in 2021.2.X
- Planned for 2020.3.X, 2021.1.X

**Comment by mob-sakai** [comment]
> IssueTracker: https://issuetracker.unity3d.com/issues/the-first-submesh-texture-is-overridden-for-all-other-submeshes-in-the-canvasrenderer-even-when-multiple-materials-are-assigned

Update: 
- Fixed in 2022.1.X, 2021.2.X, 2021.1.X
- Planned for 2020.3.X,

**Comment by MelihPampalBigger** [comment]
Hi, when are you planning to release bug fix for 2020.3.X? Thanks for helps :)

**Comment by mob-sakai** [comment]
@MelihPampalBigger 
This is a bug in Unity.
I just checked and found that "Planned for 2020.3.X" has been removed.
Instead, it says "Not reproducible with: 2019.4.27f1, 2020.2.0a21, 2020.3.12f1".

**Comment by mob-sakai** [comment]
> IssueTracker: https://issuetracker.unity3d.com/issues/the-first-submesh-texture-is-overridden-for-all-other-submeshes-in-the-canvasrenderer-even-when-multiple-materials-are-assigned

Update: 
- Fixed in 2022.1.X, 2021.2.X, 2021.1.X
