### ISSUE TITLE
Using prefab view will cause a lot of errors

### ISSUE THREAD

**Issue by drallcom3** [mob-sakai/ParticleEffectForUGUI#16]
Great assets, works well.

Just one minor issue:
When using the new prefab system from 2018 I get a massive error spam.
Probably because there's no real camera when editing the prefab in the new prefab view.

**Comment by mob-sakai** [comment]
Hi @drallcom3 
Thank you for reporting!

**Comment by mob-sakai** [comment]
I will fix this issue in the next release:)
