### ISSUE TITLE
Particles are half erased (only on play mode)

### ISSUE THREAD

**Issue by cursan-a** [mob-sakai/ParticleEffectForUGUI#161]
Hello everyone and a big thank you especially for your incredible work @mob-sakai.

I have a Particle System who is supposed to display a hundred of gold coin. As you can see everything work perfectly in editor mode : 

https://user-images.githubusercontent.com/4057582/120906634-f27cb400-c60f-11eb-8420-870888fd7a49.mov

But when i tried to trigger it on play mode i have this strange behaviour :

https://user-images.githubusercontent.com/4057582/120906636-f577a480-c60f-11eb-9733-b06a545e0257.mov

Any idea why ? 

 - Platform: Mac OS 11.2.3 (Apple M1)
 - Unity version: 2020.3.8f1

**Comment by mob-sakai** [comment]
@cursan-a 
#133

> This only happens when `Canvas.RenderMode = Screen Space - Overlay`.
> Maybe, `Default-ParticleSystem` material and `Particle/Standard Unlit` shader do not support `Screen Space - Overlay`.

## Solution 1

Use `Canvas.RenderMode = Screen Space - Camera`.

## Solution 2

Use the `UI/Default` shader for the material.

**Comment by cursan-a** [comment]
Thank you ! You're the best
