### ISSUE TITLE
Manually disabling color space conversion

### ISSUE THREAD

**Issue by kroer** [mob-sakai/ParticleEffectForUGUI#162]
Can you add a checkbox in the UIParticles component to disable color space conversion? It takes too much time (up to 75%) for complex particles (ex. if using the trails module). Or maybe there exists another way to reduce time spending on color space conversion.

Simple example.
![photo_2021-06-07_13-08-46](https://user-images.githubusercontent.com/10652194/121008372-36e48d00-c793-11eb-9e3e-84d2ef134565.jpg)

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by mob-sakai** [comment]
Please try to use `3.3.8` :smile:
