### ISSUE TITLE
Rect mask 2D doesn't work

### ISSUE THREAD

**Issue by andrew-chewie** [mob-sakai/ParticleEffectForUGUI#17]
First of all, **thank you** for this amazing asset!

Regular mask component works just fine, but Rect mask 2D doesn't work as intended.

**Comment by mob-sakai** [comment]
Hi @andrew-chewie 
Thank you for reporting!

**Comment by mob-sakai** [comment]
The issue will be fixed in the next release:)

![](https://user-images.githubusercontent.com/12690315/49870033-7eedf780-fe55-11e8-8c55-5092ccaa44b6.gif)

**Comment by andrew-chewie** [comment]
Thank you @mob-sakai ! You're super fast
