### ISSUE TITLE
The UI got a twinkle irregularly

### ISSUE THREAD

**Issue by zengskryan** [mob-sakai/ParticleEffectForUGUI#170]
When i add UIParticle to a effect, the ui that contains the effect will twinkle irregularly. 
The twinkle will last like 0.2s. 
When the twinkle happens, it's look like all the UI is been hide or the uicamera is not woking. I can see the background sceen.
My English is bad, i hope you can understand what i am saying  and i hope you can help me solve this problem.  
Thank You!

**Comment by zengskryan** [comment]
The Unity Version Is 2019.3.7f1

**Comment by mob-sakai** [comment]
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

**Comment by mob-sakai** [comment]
Since there has been no new discussion for a long time, this issue was closed.
 If the same issue arises, please re-open this issue.
