### ISSUE TITLE
不支持Mask

### ISSUE THREAD

**Issue by ph1024** [mob-sakai/ParticleEffectForUGUI#171]
在ScrollView 下使用UiParticle,Mask 没有遮住粒子
![image](https://user-images.githubusercontent.com/77137045/128597351-4e39257d-a9a6-4215-93c9-6978430feb47.png)

**Comment by mob-sakai** [comment]
@ph1024 
https://github.com/mob-sakai/ParticleEffectForUGUI#with-mask-or-maskrect2d-component

> ### With Mask or MaskRect2D component
> If you want to mask particles, set a stencil supported shader (such as UI/UIAdditive) to material for ParticleSystem.
> ![](https://user-images.githubusercontent.com/12690315/95017591-3b512700-0695-11eb-864e-04166ea1809a.png)

`Default-Particle System` material and `Particles/Standard Unlit` shader do not support `Mask` and `MaskRect2D`.
Instead, use a shader that supports them (such as `UI/UIAdditive`, `UI/UIAdditive`, or your custom shader)

**Comment by ph1024** [comment]
ok ,thank you
