### ISSUE TITLE
Drawcall raised using UIParticle component

### ISSUE THREAD

**Issue by Bruce-DC** [mob-sakai/ParticleEffectForUGUI#174]
Hi, I'm investigating whether the ParticleEffectForUGUI plugin solves a problem we encountered in our project.  As we all know, we can use multiple Canvas components to flexibly adjust UI and particle system Sort.  But too many Canvas components make it impossible for UI elements to merge batches.  To try to solve this problem, I used your plug-in, but found that the same interface produced a higher number of drawcalls than the previous solution.  I think there may be something wrong with me, because this plug-in is highly appraised on the Internet, so I would like to ask you if there is something wrong with me?  I have uploaded the demo I made to Git, and I hope you can spare your precious time to help me analyze it.  Thank you very much!
[https://github.com/Bruce-DC/UIParticleTest.git](url)

**Comment by Bruce-DC** [comment]
Sorry, I filled in the wrong URL, the following can be directly reversed:
[Demo](https://github.com/Bruce-DC/UIParticleTest.git)

**Comment by Bruce-DC** [comment]
By the way, I'm using the Unity version of Unity 2020.3.11f1c1.

**Comment by mob-sakai** [comment]
Your demo contains a lot of "missing".

Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by Bruce-DC** [comment]
Hi，I have uploaded the zip to Git.

**Comment by mob-sakai** [comment]
Your project still contains missing materials, but that is not the essence of the problem.

- In the demo project, canvas batching is not working properly.
  - Flame particles are overlapping with other BG
  - Smoke particles has z-width
- Change `UIParticle` settings for canvas batching.
  - Set `Scale.z` to `0.001`
  - Set `Scale.y` to `60` (for flame particle overlapping)
  - Set `Shrink by Material` and click `Refresh` to order the materials

### Before modification: 20 items = 181 batches
![](https://user-images.githubusercontent.com/12690315/134091466-0d0255a0-dd39-40ea-bdc1-ccaacca023bc.png)

### After modification: 20 items = 8 batches
![](https://user-images.githubusercontent.com/12690315/134091475-d0cb435f-ebcf-4011-9dbf-15da1df1b68c.png)

[UI Particle.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/7199242/UI.Particle.zip)

**Comment by mob-sakai** [comment]
I will be adding two features based on these results:
  - Force 2D Mode: Set z-scale to 0 and keep properly canvas batches.
  - Enable shrink by material as default: It is effective in most cases and can be reordered manually.

**Comment by Bruce-DC** [comment]
Hello!
I'm sorry for replying to you so late for some reason.
Thank you for your reply. I understood the problem after I saw your reply.
I'd like to discuss another issue with you. You have noticed that the CPU usage increases dramatically and the frame rate drops significantly after using your plugin, in my case.
I want to know whether this problem is caused by my wrong operation.

**Comment by mob-sakai** [comment]
@Bruce-DC 

Please close this issue and create new issue, and attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the new issue.
