### ISSUE TITLE
crash on android phone when show android native alert box 

### ISSUE THREAD

**Issue by minjoy77** [mob-sakai/ParticleEffectForUGUI#179]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Describe the bug**
crash on android phone when show android native alert box ,wait for serveral minutes, the app crash. 
unity version: 2018.4.36f1    build with IL2CPP, BuildIn pipeline 

logcat info:
![58c72b6d685f4dc3ebb26b618d1dfec](https://user-images.githubusercontent.com/8529276/143846695-5b34b2e3-0577-46c5-9ba4-18de576934c6.png)

![e43c98d63cf4fb7117165faf79a8dbb](https://user-images.githubusercontent.com/8529276/143846784-be229b6f-8fb2-46e6-ad73-c47932a651f6.png)

test code:

` public void ShowAlert(string title, string content) {
#if UNITY_ANDROID
        AndroidJavaObject activity = null;
        using (var unityPlayer = new AndroidJavaClass("com.unity3d.player.UnityPlayer")) 
        {
            activity = unityPlayer.GetStatic<AndroidJavaObject>("currentActivity");
            activity.Call("runOnUiThread", new AndroidJavaRunnable(() => {
            AndroidJavaObject dialog = null;
            using (AndroidJavaObject builder = new AndroidJavaObject("android.app.AlertDialog$Builder", activity)) {
                builder.Call<AndroidJavaObject>("setTitle", title).Dispose();
                builder.Call<AndroidJavaObject>("setMessage", content).Dispose();
                // builder.Call<AndroidJavaObject>("setPositiveButton", "OK", new OnClickListener(() => {
                //     Debug.Log("Button pressed");
                // })).Dispose();
                dialog = builder.Call<AndroidJavaObject>("create");
            }
            dialog.Call("show");
            dialog.Dispose();
            }));
        }
        
#endif
    }`
![20211129180056](https://user-images.githubusercontent.com/8529276/143847276-05663752-f9a7-4556-b7f0-246af50f7ac7.png)

**Comment by minjoy77** [comment]
I finally found the crash reason is the same as https://github.com/mob-sakai/ParticleEffectForUGUI/discussions/132

**Comment by mob-sakai** [comment]
> I may have found the cause.
> It works well if you use `Default-Particle` instead of `Default-ParticleSystem` for the particle's material.
