### ISSUE TITLE
Annoying warning for [ExecuteInEditMode]

### ISSUE THREAD

**Issue by Smileynator** [mob-sakai/ParticleEffectForUGUI#180]
If you have UI particles in a prefab, and have the prefab open when going into playmode (so the editor is in prefab edit mode) it will pop up warning called "Risk of Unwanted modifications", warning how having it open might cause issues.

The solution, is to either fix the code to be ok with it, or let unity know that prefab mode is fine (nothing breaks) by using [ExecuteAlways] instead. This in turn will make the warning go away.

**Comment by Tyrannicus100BC** [comment]
Huge +1 for this one and seems like a pretty simple change. We're considering bring this package into our project as source just so we can make this one line change.

Is there a drawback to just replacing the annotation with [ExecuteAlways]?

**Comment by Smileynator** [comment]
> Is there a drawback to just replacing the annotation with [ExecuteAlways]?

It depends on the editor only code. It might cause unexpected behavior (like saving state of the particle system that is not intended to save because of prefab mode) details are not privy to me though. Totally depends on this package's codebase.
