### ISSUE TITLE
Mesh '' has more than the 8 submeshes. Extra submeshes will be ignored.

### ISSUE THREAD

**Issue by adamsw** [mob-sakai/ParticleEffectForUGUI#186]
NOTE:
Now version(3.3.9) Just use root uiparticle.
but Unity be warning[Mesh '' has more than the 8 submeshes. Extra submeshes will be ignored.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Coffee.UIExtensions.UIParticleUpdater:Refresh (Coffee.UIExtensions.UIParticle) (at Assets/ThirdParty/UIParticle/Scripts/UIParticleUpdater.cs:85)
Coffee.UIExtensions.UIParticleUpdater:Refresh () (at Assets/ThirdParty/UIParticle/Scripts/UIParticleUpdater.cs:54)
UnityEngine.Canvas:SendWillRenderCanvases ()] if prefab is huge.

Environment (please complete the following information):

Unity version: [e.g. 2020.3.23f1c1]

**Comment by mob-sakai** [comment]
ref: #152
