### ISSUE TITLE
Performance problem exploration for  UIParticle plugin

### ISSUE THREAD

**Issue by Bruce-DC** [mob-sakai/ParticleEffectForUGUI#193]
Hello!
After a period of familiarity, we would like to apply your UIParticle plugin to our project to solve the problem of using too many Canvas components for UI particle effects in our project. However, during this time we also discovered a problem: when using THE UIParticle component to manage multiple particle effects in the UI, does it cause performance problems?
We downloaded your demo for research. Here we only compare UIParticle and SortingOrder, so the Hierarchy panel looks like this:
![1644309436613-4f901e58-7e7c-43bb-8cf6-f842af1e4aa4](https://user-images.githubusercontent.com/48212965/152952914-e0a25b66-e6af-4006-80ab-d326b6e16f6b.png)
When we used only one UIParticle, the average frame rate was around 550 frames:   
![1644309586228-2f4be0c7-5e49-4f52-a18c-ccfcc0f80cf5](https://user-images.githubusercontent.com/48212965/152953328-38a6af07-ddc9-41ac-a4ce-9ae36d470605.png)
When we use only one SortingOrder, the average frame rate is around 600 frames: 
![1644309659997-be743c7a-b2d0-49b5-a34c-32f374198518](https://user-images.githubusercontent.com/48212965/152953443-4c8c9abf-961c-4d84-bad9-00d5b6a602d2.png)
It's not a big difference, but let's increase the number to 10.  
When showing 10 UIParticles, the average frame rate is 270 frames:  
![1644309764563-8164c52e-e18f-4976-8f46-191feaf778ff](https://user-images.githubusercontent.com/48212965/152953611-86350a43-eebc-4f86-adbc-184e93c00c59.png)
When we show 10 sortingOrders, the average frame rate is still around 450:  
![1644309853882-ece7c104-beb3-4929-a751-c413bd95273d](https://user-images.githubusercontent.com/48212965/152953725-cb8d87d4-1db4-4501-8379-3adc03671d98.png)

At the same time, we can see that SortingOrder performs better in CPU usage, batch processing and other data.  
Because there is a problem in our project that a page uses more than ten Canvas components to control the level of effects, we compare the experiment in this way.  
Is it right to draw this conclusion?  Or is it unscientific for us to compare?  
We look forward to hearing from you.  
Thank you very much!

**Comment by ifshuaishuai** [comment]
Yes, I also found that UIParticle performance badly, correct me if i am wrong.
So I recommend check out [UIParticleSystem](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/wiki/Controls/UIParticleSystem).

**Comment by midiphony** [comment]
In the README.md, the developer compared its approach with the aforementioned [UIParticleSystem](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/wiki/Controls/UIParticleSystem).

The issue author should maybe try this other system and compare.

Also, profiler data investigation might be more relevant !

**Comment by mob-sakai** [comment]
Sorry for my late reply.
SortingOrder approach is the fastest and most efficient way to operate.
Its approach works without any extra processes.
However, it requires some canvases with sorting order before and after the particle system.

**Comment by mob-sakai** [comment]
@Bruce-DC @ifshuaishuai @midiphony 
Sorry for my late reply.

I test these approaches with a performance-test project.
"Mesh Sharing Group" feature, added in v4.0.0, performs better than "Sorting By Canvas" approach.
[PerformanceTest.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/8937994/PerformanceTest.zip)

It displays 300 "flame and spread effect (with Unity-chan)".

![](https://user-images.githubusercontent.com/12690315/174537997-b225e85b-658b-4391-bd75-aa6983c9e952.png)

### Particle System (default)

![](https://user-images.githubusercontent.com/12690315/174528070-91e13103-4560-4942-9a6c-910751950906.png)

### UIParticleSystem

NOTE: UIParticleSystem does not support trail and texture animation

![](https://user-images.githubusercontent.com/12690315/174529970-00fe6c41-30cd-4691-ae35-4db0e28f8376.png)

### Sorting By Canvas

![](https://user-images.githubusercontent.com/12690315/174528066-f1f23cc4-52d8-4148-bc36-5a6869a49c54.png)

### UIParticle (v3.3.12)

![](https://user-images.githubusercontent.com/12690315/174528613-5c4fa669-3bf9-4148-b0e1-95036f05cb6a.png)

### UIParticle (v4.0.0, without mesh sharing)

![](https://user-images.githubusercontent.com/12690315/174528061-03f04a32-2d09-4265-89a5-abdd6700ff96.png)

### UIParticle (v4.0.0, with mesh sharing, 5 groups)

NOTE: The mesh sharing feature improves performance by sharing "particle simulation", "mesh baking", and "mesh combining".

![](https://user-images.githubusercontent.com/12690315/174528052-c53914e5-d4af-42d3-876c-62564e0953bd.png)

**Comment by mob-sakai** [comment]
Since there has been no new discussion for a long time, this issue was closed.
 If the same issue arises, please re-open this issue.

**Comment by luxuia** [comment]
mesh share with auto mode seams not implemented? should i do it?
