### ISSUE TITLE
Some resources are missing on Demo

### ISSUE THREAD

**Issue by Cova8bitdots** [mob-sakai/ParticleEffectForUGUI#195]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Describe the bug**
In the latest demo on UPM, there are lack of resources for demo.
Most of UI resources are not in demo.

JP:
UMP経由でDemoを導入した場合、Demo用のSceneで利用されているUIリソースが
Demoに含まれてないためImage Component でMissing が発生しています

**To Reproduce**
1. Import all demo via UnityPackageManager Window
2. Open `Assets/Samples/UI Particle/3.3.10/Cartoon FX & War FX Demo/CFX Free Demo.unity`
3. Check Game View & Inspector

**Expected behavior**
- no missing resources
- same view to WebGL Demo (https://mob-sakai.github.io/Demos/ParticleEffectForUGUI_CFX/ )

**Screenshots**
<img width="857" alt="スクリーンショット 2022-04-14 15 18 17" src="https://user-images.githubusercontent.com/4001760/163325645-40b05991-253c-4e2d-83d3-c4181594e367.png">
<img width="928" alt="スクリーンショット 2022-04-14 15 18 43" src="https://user-images.githubusercontent.com/4001760/163325649-784690f7-c511-4761-802d-b9bbebcafe57.png">

**Environment (please complete the following information):**
 - Version 3.3.10
 - Platform:  WebGL
 - Unity version: Unity2020.3.32f1
 - Build options: IL2CPP, .Net 4.x

**Additional context**
nothing

**Comment by mob-sakai** [comment]
It requires free assets ([Cartoon FX Free][CFX] & [War FX][WFX]) by [Jean Moreno (JMO)][JMO].
Please install the assets with asset store.

[CFX]: https://assetstore.unity.com/packages/vfx/particles/cartoon-fx-free-109565
[WFX]: https://assetstore.unity.com/packages/vfx/particles/war-fx-5669
[JMO]: https://assetstore.unity.com/publishers/1669
