### ISSUE TITLE
A simple solution about Mask

### ISSUE THREAD

**Issue by dreamCirno** [mob-sakai/ParticleEffectForUGUI#198]
### Problem Background
> My background (the multi points) is a particle system component. It's material is a animation by shader. I have a ScrollView in my scene. When I drag the content, it's a bug like below image.

### Bug

![image](https://user-images.githubusercontent.com/24387058/164189675-e025f8be-8277-47ff-92c2-7cb437b68735.png)

### Solve Process
> I found a solution about mask in doc. The solution needs me change such as 'UI/UIAdditive' shader. This solution doesn't work for my case. Because my paritcle system component has a shader need to play a shader animation.

### Solution
> I try to replaced the Mask component with a Rect Mask 2D component. （Mask -> Rect 2D Mask）It's works.

### Finally

![image](https://user-images.githubusercontent.com/24387058/164191608-24bd58b6-fabc-425d-8a15-4eb3693f3708.png)

**Comment by mob-sakai** [comment]
I will describe in the README "how to make a custom shader that support the Mask component".
