### ISSUE TITLE
DeltaTime Unscaleは対応していませんか？

### ISSUE THREAD

**Issue by sr4dev** [mob-sakai/ParticleEffectForUGUI#202]
ParticleSystemをDeltaTime：UnscaleにしてUIParticleをつけて見ましたが、反映されないみたいです。
UIParticleをUnscaleで再生できる方法はありませんか？

**Comment by mob-sakai** [comment]
I tested it in my environment.
- UIPartilce version: 3.3.10
- Platform:
  - Editor(Mac)
  - Standalone(Mac)
- Unity version: 2021.2.19f1
- Build options: default

![](https://user-images.githubusercontent.com/12690315/172830879-cd2d62e8-2d1e-40f5-93ae-35feeaa25044.gif)

Unscaled time seems to be supported.

---

私の環境でテストしてみましたが、正常に動作しているようです...

**Comment by sr4dev** [comment]
大変失礼しました… 新規プロジェクトを作って試してみた結果、自分のテスト環境が悪かったみたいです。
こちらのIssueはクロースさせていただければと思います。
