### ISSUE TITLE
Trailing transparency

### ISSUE THREAD

**Issue by AnYueBoy** [mob-sakai/ParticleEffectForUGUI#204]
I found that when I hang a trailing component on a particle system, the trailing is transparent on an interface with a picture background.
like that.
![image](https://user-images.githubusercontent.com/40288423/174923943-99e6dc9c-667c-4b9a-988c-667af7d436fa.png)

**Comment by mob-sakai** [comment]
@AnYueBoy 
I would like to know more about this issue.
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by mob-sakai** [comment]
As the demo shows, UIParticle supports trail modules.
<img width="497" alt="image" src="https://user-images.githubusercontent.com/12690315/174930809-4921527b-605b-42cc-8d69-b581b8dc53aa.png">


Check the materials and shaders of the background and particle system.
- Are the render queue in materials set to 3000 (=Transparent)?
- Are `ZTest` and `ZWrite` in shaders proper?

**Comment by AnYueBoy** [comment]
![1655866620226_E4662423-FAE5-41fd-935C-828B86BC747F](https://user-images.githubusercontent.com/40288423/174934028-4e4094a1-fa63-4294-829d-e7237580c763.png)
[UIParticleTest.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/8954063/UIParticleTest.zip)

I built a scenario to reproduce this problem

**Comment by mob-sakai** [comment]
Ah, I understood.
By "Trail" you mean "`Trail Renderer` Component", not "`Trails` Module (in ParticleSystem)", right?

UIParticle does not support "Trail Renderer Component".
Use "Trails Module (in ParticleSystem)" instead.

As someone said before, we think there is a demand for a package that displays the `Trail Renderer` or `Line Renderer` as a UI.

**Comment by AnYueBoy** [comment]
Alright. Thank you very much for your help

**Comment by mob-sakai** [comment]
Perhaps what you wanted to do:
![](https://user-images.githubusercontent.com/12690315/174941858-dc9d10c9-f855-4e5b-a5f8-ab8cdb738d03.gif)

[Trails.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/8954346/Trails.zip)

**Comment by AnYueBoy** [comment]
Hi , I found another problem.

In my original particle, two particles kept a certain distance from the central particle.  Like first.
![image](https://user-images.githubusercontent.com/40288423/174965132-93bda88f-9dee-47a5-af77-d4b234ee5d7b.png)

However, when I drag original particle under UIParticle Component and click the refresh button, the position and center distance of the two particles changed. Like second 

This situation exists in version 4.0.0, but not in 3.3.10.






[UIParticleTest.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/8955207/UIParticleTest.zip)

**Comment by mob-sakai** [comment]
Will this be reproduced during play mode?

**Comment by AnYueBoy** [comment]
I found that the problem was caused by scaling.
in version 3.3.10 like that 
![first](https://user-images.githubusercontent.com/40288423/174978608-e4084639-336e-4ea1-9bb1-f96fe76eb250.gif)
however, in version 4.0.0 
![second](https://user-images.githubusercontent.com/40288423/174978691-dd287e16-4c02-4dd7-b2c5-8a1b28dc928c.gif)

**Comment by mob-sakai** [comment]
Umm, I forgot to check the use case!

**Comment by AnYueBoy** [comment]
ok , I will resubmit an issue later.
