### ISSUE TITLE
Particle position change caused by scaling

### ISSUE THREAD

**Issue by AnYueBoy** [mob-sakai/ParticleEffectForUGUI#205]
Hi , I found another problem.

In my original particle, two particles kept a certain distance from the central particle.  Like first.
![image](https://user-images.githubusercontent.com/40288423/174965132-93bda88f-9dee-47a5-af77-d4b234ee5d7b.png)

However, when I drag original particle under UIParticle Component and click the refresh button, the position and center distance of the two particles changed. Like second 

This situation exists in version 4.0.0, but not in 3.3.10.

[UIParticleTest.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/8955207/UIParticleTest.zip)

_Originally posted by @AnYueBoy in https://github.com/mob-sakai/ParticleEffectForUGUI/issues/204#issuecomment-1162732310_

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by mob-sakai** [comment]
WIP
![](https://user-images.githubusercontent.com/12690315/175563778-1ab689fb-1c3d-4641-adf5-066857da9985.gif)
