### ISSUE TITLE
Trail not display

### ISSUE THREAD

**Issue by AnYueBoy** [mob-sakai/ParticleEffectForUGUI#206]
Hi , I found a problem in the old version (v3.3.12).

I put a particle effect with four tails in UIParticle Component.

However, the fourth trailing effect is not displayed.  Like that.

![image](https://user-images.githubusercontent.com/40288423/175187979-bc72aa0c-88f8-415d-9ece-0c69318ffec3.png)

And when I hide any other trailer, the fourth trailer is displayed. Like that.
![image](https://user-images.githubusercontent.com/40288423/175188153-c74832c6-8181-4641-8983-f8b9c0372a2c.png)

The specific operations are as follows.

![UIParticle](https://user-images.githubusercontent.com/40288423/175188221-47351eb5-516c-4c0b-b456-d48efa799421.gif)

[UIParticleTest.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/8962890/UIParticleTest.zip)

UIParticle Version 3.3.12

**Comment by AnYueBoy** [comment]
It looks like there can only be three trailing components at most.

**Comment by mob-sakai** [comment]
@AnYueBoy 
This is due to the limited number of materials that UIParticle v3 has.
UIParticle v3 supports up to 8 materials.
(UIParticle v4 supports more than 8 materials)

Same issues:
#186
#122
