### ISSUE TITLE
Abnormal position of trailing particles

### ISSUE THREAD

**Issue by AnYueBoy** [mob-sakai/ParticleEffectForUGUI#209]
The position of my trailing particles in version 3.3.12 is normal, but when I upgrade to 4.1.1, the position of trailing particles and particles are separated.

v3.3.12
![UIParticle3 3 12](https://user-images.githubusercontent.com/40288423/175851698-e6f6fb8b-59b5-4af4-b9df-97a6f48a66cf.gif)

v4.1.1
![UIParticle4 1 1](https://user-images.githubusercontent.com/40288423/175851753-f1898460-488c-40ac-85a6-d5a1a9569b6e.gif)

![1656298263750_6BE091E2-B63C-446c-ADA2-2F94542EA14C](https://user-images.githubusercontent.com/40288423/175851764-985183f3-f38f-4206-b747-72e374daf52c.png)
[UIParticleTest.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/8988357/UIParticleTest.zip)

**Comment by mob-sakai** [comment]
Thank you for your reporting!
