### ISSUE TITLE
Abnormal error

### ISSUE THREAD

**Issue by AnYueBoy** [mob-sakai/ParticleEffectForUGUI#210]
Whenever I enter the prefabrication of trailing particles, the console will report an error and return to the main scene to generate some nodes.

![UIParticleTest](https://user-images.githubusercontent.com/40288423/175852142-2df145db-39bb-41ce-bd60-17308aae100b.gif)

![1656298456885_1AC7FD9D-2E14-47c4-998B-AAF63F686F87](https://user-images.githubusercontent.com/40288423/175852264-5227d916-2c8a-4bd6-b435-ab2aa515eaae.png)

**Comment by mob-sakai** [comment]
Thank you for your reporting!
