### ISSUE TITLE
Drag prefabrication error

### ISSUE THREAD

**Issue by AnYueBoy** [mob-sakai/ParticleEffectForUGUI#211]
![UIParticle](https://user-images.githubusercontent.com/40288423/176066874-0527802b-343f-4119-b64b-9bf721a1bf39.gif)

It seems that the parent node of transform is missing a non empty judgment.

![image](https://user-images.githubusercontent.com/40288423/176067009-ee6b4503-6d6d-460d-8f05-3f83fe4bff6c.png)

I added a non empty judgment, but I don't know whether it is appropriate.

![image](https://user-images.githubusercontent.com/40288423/176067099-cf8e2d72-abc5-4e59-9b8f-eeb65795e629.png)

**Comment by mob-sakai** [comment]
Thank you for your reporting!
