### ISSUE TITLE
Cannot align particle with parent rotation

### ISSUE THREAD

**Issue by sunwangshu** [mob-sakai/ParticleEffectForUGUI#212]
https://answers.unity.com/questions/219565/how-to-orient-particles-to-direction-they-are-movi.html

Hello! The use case is as described in the above link. Basically, there are cases when we have to use UI Particle, but then we lost the ability to set "render alignment" to local as the default renderer does. 

I would like something similar in the UI Particle package if possible. Thanks!.

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by mob-sakai** [comment]
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by mob-sakai** [comment]
The issue is not reproduced on my environment.
I do not know what you want to do.
If you want to rotate particles relative to the direction of movement, you have the following options:
- Render Mode: Stretched Billboard
- Length Scale: 1

![](https://user-images.githubusercontent.com/12690315/176830320-56a31972-fccc-4de9-9928-264c7e317d5b.png)
![](https://user-images.githubusercontent.com/12690315/176830329-37d8e890-fda8-4082-9fe2-d7ee10d636a6.png)
![](https://user-images.githubusercontent.com/12690315/176830858-c6eb8ca4-56b4-411c-87ff-d2545f91d7ee.gif)

**Comment by mob-sakai** [comment]
Since there has been no new discussion for a long time, this issue was closed.
 If the same issue arises, please re-open this issue.

**Comment by sunwangshu** [comment]
Thanks for taking the time to look into this issue, it was finally resolved by changing the `Render Alignment` of the `Renderer` component from `View` to `Local`.  

So no need to reopen this issue. 

<img width="461" alt="Screen Shot 2022-08-10 at 7 36 30 PM" src="https://user-images.githubusercontent.com/14167797/184058375-b9d1cf87-1926-41f1-a850-a07f8450cce9.png">


I didn't know that `Renderer` of the ParticleSystem can still affect the UI Particle, because every time I attach the UIParticle componenet, the Renderer is turned off. 

The problem was like this: bascially the blue particle is sandwiched between magenta and yellow, but it doesn't rotate with other UIs under the same parent.

![gif1](https://user-images.githubusercontent.com/14167797/184057860-555445e1-bc49-4376-8440-d9ce9c0743c3.gif)

The fix I want is like this:

![gif2](https://user-images.githubusercontent.com/14167797/184058042-ccb82e4e-6877-4545-9ab1-ff14f416592e.gif)

If you're curious, here is the project:
[ReproducedProject.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/9305806/ReproducedProject.zip)

(Sorry for taking so long to respond, I was worried about the minimal project because I wasn't supposed to include any company asset in it, and I was sick from covid for a while. )
