### ISSUE TITLE
Abnormal error

### ISSUE THREAD

**Issue by AnYueBoy** [mob-sakai/ParticleEffectForUGUI#214]
When I click prefabrication or drag prefabrication to the scene, an error will be reported.
![UIParticle](https://user-images.githubusercontent.com/40288423/176583976-44741e52-0947-4cf0-8e2c-f21639d181ab.gif)
[UIParticleTest.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/9016102/UIParticleTest.zip)

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by mob-sakai** [comment]
If `m_Particles` contains null, this error occurs.

**Comment by AnYueBoy** [comment]
Emm, When I click the refresh button, the material list is updated to the correct status, but when I re-enter the prefabrication, the material list is empty again.

![UIParticle](https://user-images.githubusercontent.com/40288423/176805887-0238c140-e621-4fa5-ada1-5564011a5751.gif)

**Comment by AnYueBoy** [comment]
Emm,I deleted an empty uiparticlerenderer, and the prefabrication seems to be back to normal.
