### ISSUE TITLE
Assertion failed on expression: 'IsNormalized(normal, 0.001f)'

### ISSUE THREAD

**Issue by tracer8** [mob-sakai/ParticleEffectForUGUI#22]
![bandicam 2018-12-18 21-09-43-523](https://user-images.githubusercontent.com/15725821/50159458-53fa1c80-0309-11e9-8518-2ce7fceeb4d9.jpg)

Hi, when i use UIParticle with menu canvas, my menu have ScaleOut(Panel contain Particle scale to 0) animation transition, it's make UIParticle firing above error.

**Comment by mob-sakai** [comment]
Hi @tracer8
Thank you for reporting!

I would like to know more information on this issue.
Can you submit a reproducible project for this issue?

**Comment by tracer8** [comment]
I'm try to produce it on new project but can't make it happen, but still on my current project, maybe i do something wrong with this. I will try to research more then upload project later.

Thank you!

**Comment by linboboo** [comment]
> I'm try to produce it on new project but can't make it happen, but still on my current project, maybe i do something wrong with this. I will try to research more then upload project later.
> 
> Thank you!

hi,How did you solve this problem? I also encountered this error, but I couldn't find the reason
