### ISSUE TITLE
How to Migrate from 3.3.12 to 4.0

### ISSUE THREAD

**Issue by ghost** [mob-sakai/ParticleEffectForUGUI#221]
I have tried migrating from 3.3.12 to 4.0 but all my UI Particles looked total off (They are in Screen Space - Camera). Changing the scale doesn't work as expected, instead of getting as before, the particles are far more apart and smaller than before. Is there a guide for the migration? Or how would you migrate this?

**Comment by mob-sakai** [comment]
I would like to know more about this issue.
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by Nyankoo** [comment]
I have the same issue, but only a big project this happens in.
Additionally, after updating, some particles throw a "NullReferenceException" after disabling and enabling the GameObject:
```
NullReferenceException: Object reference not set to an instance of an object
Coffee.UIExtensions.UIParticleRenderer.GetModifiedMaterial (UnityEngine.Material baseMaterial) (at Library/PackageCache/com.coffee.ui-particle@5e6da2e158/Scripts/UIParticleRenderer.cs:121)
UnityEngine.UI.Graphic.get_materialForRendering () (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Graphic.cs:497)
UnityEngine.UI.Graphic.UpdateMaterial () (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Graphic.cs:658)
UnityEngine.UI.Graphic.Rebuild (UnityEngine.UI.CanvasUpdate update) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Graphic.cs:636)
UnityEngine.UI.CanvasUpdateRegistry.PerformUpdate () (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/CanvasUpdateRegistry.cs:215)
UnityEngine.UI.ScrollRect:LateUpdate() (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/ScrollRect.cs:834)
```

**Comment by Lemonua** [comment]
![image](https://user-images.githubusercontent.com/21081988/190126647-bc6fa60d-4922-46b8-8b6d-8f368b37a894.png)
Hi! Same problem. UI particle overrides scale parameters in whole project, scale at Rect Transform component becomes inactive and i don't have Ignore Canvas Scale property
[prefabtest.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/9565383/prefabtest.zip)

**Comment by SporeProductions** [comment]
I see a new option there called "Absolute Mode". Is that maybe the cause of the problem reported here?

**Comment by SporeProductions** [comment]
Could we PLEASE get an answer to this?

**Comment by suoluosl** [comment]
Same problem!

**Comment by RobinHood119** [comment]
Same problem!

**Comment by mob-sakai** [comment]
Please try v4.2.0
