### ISSUE TITLE
Sub Emitters option is not work in editor playing

### ISSUE THREAD

**Issue by GouDanYuan** [mob-sakai/ParticleEffectForUGUI#231]
**Describe the bug**
when i use the partical system to make a firework partical, used the Sub Emitters option, the effect is different in editor playing and not playing.the sub partical is not born in the correct position when the main partical death.the sub partical seem faster in playing.

![image](https://user-images.githubusercontent.com/27915116/196911422-a8c443c8-f5b8-4644-b6f1-71ba9af56dea.png) editor not playing

![image](https://user-images.githubusercontent.com/27915116/196911671-d62a4790-e34f-420a-9d06-3c913f51f6c0.png) 
editor playing

**To Reproduce**
[sub_emitter_bug.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/9828433/sub_emitter_bug.zip)
Import the sub_emitter_bug.unity package to unity and play

**Environment (please complete the following information):**
 - Version [4.1.7]
 - Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac)]
 - Unity version: [e.g. 2021.3.9f1]
 - Build options: [e.g. IL2CPP, .Net 4.x, URP]

**Comment by mob-sakai** [comment]
Sorry for my late reply.
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by GouDanYuan** [comment]
[SubPartical.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/10302268/SubPartical.zip)
the minimal project  project is upload.

**Comment by Skyfro19** [comment]
I also had the same problem when I used the Sub Emitters option and the particle effects were not positioned correctly.

**Comment by JonathanVorich** [comment]
Same Issue! The solution of @Dongurea fixed my problem, but broke some particles in other places, so its not for any use for me. Will there be a fix soon @mob-sakai ??? Would be really really helpful.

**Comment by JonathanVorich** [comment]
Same Issue! Will there be any fix soon @mob-sakai ??? Would be really really helpful.
