### ISSUE TITLE
my particle is incorrect when i use "Screen Space - Camera"

### ISSUE THREAD

**Issue by haomingge** [mob-sakai/ParticleEffectForUGUI#232]
[fx.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/9929640/fx.zip)

v:4.0.0
unity:2020.3.35

**Comment by mob-sakai** [comment]
Sorry for my late reply.
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by L10330** [comment]
[New Unity Project.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/10123638/New.Unity.Project.zip)
thanks

**Comment by JerryLetehen** [comment]
a heads up
@mob-sakai

**Comment by mob-sakai** [comment]
Try this:
<img width="421" alt="image" src="https://github.com/mob-sakai/ParticleEffectForUGUI/assets/12690315/3939e4c8-0f51-4493-852f-706302fd8558">
<img width="201" alt="image" src="https://github.com/mob-sakai/ParticleEffectForUGUI/assets/12690315/104b860e-39c3-4fbb-ae03-75e7bf828c56">
<img width="401" alt="image" src="https://github.com/mob-sakai/ParticleEffectForUGUI/assets/12690315/d654feb3-4ac9-4b7a-97f2-db1b5f314597">
<img width="414" alt="image" src="https://github.com/mob-sakai/ParticleEffectForUGUI/assets/12690315/572fc298-9655-4e93-b545-0ff987e00aad">

enjoy!
