### ISSUE TITLE
Didn't work OnParticleSystemStopped Callback

### ISSUE THREAD

**Issue by githysm** [mob-sakai/ParticleEffectForUGUI#24]
private void Start()
    {
        ParticleSystem.MainModule main = _ps.main;
        main.stopAction = ParticleSystemStopAction.Callback;
    }

    private void OnParticleSystemStopped()
    {
        CObjectPool._pInstance.PoolObject(gameObject);
    }
Callback not working when use UIParticle

**Comment by mob-sakai** [comment]
Hi @githysm 
Thank you for reporing!

**Comment by githysm** [comment]
oh, sry my mistake
i didnt attach script on particle object
XD

**Comment by asdfer-1234** [comment]
How can i attach a script to a particle?
