### ISSUE TITLE
My particle system cannot be displayed in the game window

### ISSUE THREAD

**Issue by YangShader** [mob-sakai/ParticleEffectForUGUI#244]
My particle system cannot be displayed in the game window. I set the simulation space of the particle system from local to world. The particle system can be displayed on the screen normally. But move the particle system components. The particle effect moves with it. Not the effect I want. However, if the simulation space is set local, it cannot be displayed normally. Is there any good solution? My English is not good, please forgive me.
![image](https://user-images.githubusercontent.com/66364764/210478187-5dd56cc4-771c-46a7-a97d-5fe3d2449304.png)

**Comment by YangShader** [comment]
I want to set the simulation space of the particle system to be local, so that the effect of my particle effect is displayed correctly, but it cannot be displayed on the screen in the end.

**Comment by mob-sakai** [comment]
Use `Absolute Mode` option in inspector.
