### ISSUE TITLE
Nullptr exceptions when using nested UIParticle components in hierarchy

### ISSUE THREAD

**Issue by pak762** [mob-sakai/ParticleEffectForUGUI#246]
We recently updated the package in our project from version 3.3.10 to 4.1.7.

Problem is that we are having nested UIParticle components in our hierarchy meaning that a GameObject with a UIParticle component can have child GameObjects with more UIParticle components.

![ChildUIParticlesInHierarchy](https://user-images.githubusercontent.com/6782881/215032902-72c52f4b-0e49-403f-a249-0e40494ebc53.PNG)

This leads to the UIParticleRenderer of the child UIParticle components to get cleared by the `RefreshParticles()` method which gets all child UIParticleRenderers by calling `GetComponentsInChildren(m_Renderers)` which also returns all UIParticleRenderes of all other UIParticle components down in the hierarchy. These then get wrongly reset at the end of the `RefreshParticles()` function.
This then leads to _parent being set to null causing nullptr exceptions when accessing functions of the wrongly cleared UIParticleRenderers.

I had to change the `RefreshParticles(List<ParticleSystem> particles)` function to only get the UIParticleRenderers of the first hierarchy depth. 

`GetComponentsInChildren(m_Renderers)`
to
`        
    
    m_Renderers.Clear();
            
    foreach (Transform child in transform)
    {
        UIParticleRenderer uiParticleRenderer = child.GetComponent<UIParticleRenderer>();

        if (uiParticleRenderer != null)
        {
            m_Renderers.Add(uiParticleRenderer);
        }
    }`

 - Version 4.1.7
 - Platform: Editor(Windows/Mac)
 - Unity version: 2021.3.11f1

I could not find anything regarding nested UIParticle components inside the documentation. Changing all affected places in all our prefabs would be another fix of cause to not have nested UIParticle components at all, but this worked fine in the previous version we where using.

**Comment by RobinHood119** [comment]
> We recently updated the package in our project from version 3.3.10 to 4.1.7.
> 
> Problem is that we are having nested UIParticle components in our hierarchy meaning that a GameObject with a UIParticle component can have child GameObjects with more UIParticle components.
> 
> ![ChildUIParticlesInHierarchy](https://user-images.githubusercontent.com/6782881/215032902-72c52f4b-0e49-403f-a249-0e40494ebc53.PNG)
> 
> This leads to the UIParticleRenderer of the child UIParticle components to get cleared by the `RefreshParticles()` method which gets all child UIParticleRenderers by calling `GetComponentsInChildren(m_Renderers)` which also returns all UIParticleRenderes of all other UIParticle components down in the hierarchy. These then get wrongly reset at the end of the `RefreshParticles()` function. This then leads to _parent being set to null causing nullptr exceptions when accessing functions of the wrongly cleared UIParticleRenderers.
> 
> I had to change the `RefreshParticles(List<ParticleSystem> particles)` function to only get the UIParticleRenderers of the first hierarchy depth.
> 
> `GetComponentsInChildren(m_Renderers)` to `
> 
> ```
> m_Renderers.Clear();
>         
> foreach (Transform child in transform)
> {
>     UIParticleRenderer uiParticleRenderer = child.GetComponent<UIParticleRenderer>();
> 
>     if (uiParticleRenderer != null)
>     {
>         m_Renderers.Add(uiParticleRenderer);
>     }
> }`
> ```
> 
> * Version 4.1.7
> * Platform: Editor(Windows/Mac)
> * Unity version: 2021.3.11f1
> 
> I could not find anything regarding nested UIParticle components inside the documentation. Changing all affected places in all our prefabs would be another fix of cause to not have nested UIParticle components at all, but this worked fine in the previous version we where using.

dear sir, we also updated the package in our project from version 3.3.10 to 4.1.7. but some scale and particle system performance is not correct, do you also have this problem?
