### ISSUE TITLE
Material color is more white and has transperency

### ISSUE THREAD

**Issue by apelih24** [mob-sakai/ParticleEffectForUGUI#247]
Hi, i may be mistaken and this is correct behaviour but when i change shader to UI\Additive my material becomes more white and has transperency. This also can be seen in example materials. Is this correct behavior or it can be fixed? I just want to have 1 to 1 color from sprite
![image](https://user-images.githubusercontent.com/38560595/216258181-0ec1367f-b0c2-4393-a62a-7d3b5395c3ae.png)

**Comment by apelih24** [comment]
Reproduce on Unity 2021.3.9f1

**Comment by enpiech** [comment]
Reproduce on Unity 2022.3.5f1

**Comment by mob-sakai** [comment]
Yes, this is a Unity specification. For example, the `Mobile/Particles/Additive` shader looks the same.
