### ISSUE TITLE
URP--> Particles --> Unlit using this shader, and color becomes messed up.

### ISSUE THREAD

**Issue by darkdoom973** [mob-sakai/ParticleEffectForUGUI#248]
Lit simple lit works fine. These are the settings for the lit material which works.
![image](https://user-images.githubusercontent.com/100094370/216777365-e4246072-44f0-4eae-9377-4940f1e72521.png)

**Comment by wangshuNex** [comment]
try `UI/Default` instead? I think it's in the document that there are shader limitations for UI Particle
