### ISSUE TITLE
Is "UIParticleOverlayCamera" necessary for uiParticle?

### ISSUE THREAD

**Issue by MJ5353** [mob-sakai/ParticleEffectForUGUI#251]
**Describe what help do you need**
I'm using 4.1.7 version and have a question for UIParticle script. It is about "GetBakeCamera" method.
I found #35 , but prefab still create "UIParticleOverlayCamera".
This object does not show in inspector on runtime, and disabled always.
Is it nessassory for making makable particle?

**Comment by mob-sakai** [comment]
Yes
