### ISSUE TITLE
BROWN PARTICLE PROBLEM

### ISSUE THREAD

**Issue by furkanjss** [mob-sakai/ParticleEffectForUGUI#255]
Hey,Thanks for this package.I have an issue.All Cartoon Fx Particles is BROWN.My Project is URP and I using 2021.3.16f.
Do you have any solution?

**Comment by nzeman** [comment]
how did you fix this issue? I have the same problem

**Comment by mob-sakai** [comment]
@furkanjss @nzeman 
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by mob-sakai** [comment]
See https://github.com/mob-sakai/ParticleEffectForUGUI/issues/270

**Comment by mob-sakai** [comment]
Since there has been no new discussion for a long time, this issue was closed.
 If the same issue arises, please re-open this issue.
