### ISSUE TITLE
Scale error with ver4.1.7

### ISSUE THREAD

**Issue by gwc0111** [mob-sakai/ParticleEffectForUGUI#256]
I use Camera with this parameter, but some particle with scale > 1 isn't valid.
I try to locate in the error, and I found how it happens. When I scale the particle in Transform.scale or Particle System "Start Size", if the value >1, and the size of camera isn't the default value(5), the size of particle will be wrong in running(very small). Please fix it. Thank you!!
![image](https://user-images.githubusercontent.com/21290593/230303608-9d5a77b2-7ed1-4f9a-9de1-4993b7318b3e.png)
![image](https://user-images.githubusercontent.com/21290593/230304041-b3d94b85-1828-4e62-a7ac-8c0f62b62663.png)

**Comment by mob-sakai** [comment]
Please try v4.2.0
