### ISSUE TITLE
Works perfectly in editor, does not render in Android build

### ISSUE THREAD

**Issue by Robb1124** [mob-sakai/ParticleEffectForUGUI#257]
The plugin works perfectly in editor, but does not render in Android build most of the time. In my first scene, the particles can render the first time the prefab is loaded via Addressables, but simply does not render after being unloaded/reloaded. All other particles never render in other scenes. I can still see the profiler markers in the profiler, but the frame debugger shows nothing related to particles. I tried with a lot of different particles and they all produce the same behaviour, even the "default" one. By not rendering I mean I see absolutely nothing about the particles, not that it does not render correctly.

Could there be some weird interactions with the addressables system? 

**Environment (please complete the following information):**
 - Version: 4.1.7
 - Platform: Android
 - Unity version: 2021.3.0, URP
 - Build options: IL2CPP, OpenGL, Multithreaded rendering

**Comment by mofish9** [comment]
Hi,
Have you fixed this issue? The latest version doesn't render on iOS and Android build, but it works in the editor. The Unity version is 2021.3.25

**Comment by KeonyoungYang** [comment]
Might relatives here, the particles didn't render on several IOS devices. Unity version is 2021.3.16f1

**Comment by mob-sakai** [comment]
ref: #233 

Built-in shaders are no longer supported.
Use UI shaders instead.

In the next version, an error message will appear in the inspector when using the non-UI built-in shaders.
![](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/12690315/6239f5ab-a661-4500-973f-51e3266d7dd7)
