### ISSUE TITLE
NullReferenceException after copy-n-paste

### ISSUE THREAD

**Issue by Watcher3056** [mob-sakai/ParticleEffectForUGUI#258]
**Describe the bug**
Problem using copy-paste feature of gameobject with UI Particle component on it, constant null reference exceptions starts to appear - need to remove UI Particle component and destroy all UIParticleRenderer gameobjects and setup again in order to fix issue.

UPD: Problem appear when clicking on any UIParticleRenderer gameobject even after destroying them and UIParticle component and attach it back.
Log of error:

NullReferenceException: Object reference not set to an instance of an object
Coffee.UIExtensions.UIParticleRenderer.GetModifiedMaterial (UnityEngine.Material baseMaterial) (at Assets/3_ThirdParty/0_Source/ParticleEffectForUGUI-4.1.7/Scripts/UIParticleRenderer.cs:121)
UnityEngine.UI.Graphic.get_materialForRendering () (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Graphic.cs:497)
UnityEngine.UI.Graphic.UpdateMaterial () (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Graphic.cs:658)
UnityEngine.UI.Graphic.Rebuild (UnityEngine.UI.CanvasUpdate update) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Graphic.cs:636)
UnityEngine.UI.CanvasUpdateRegistry.PerformUpdate () (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/CanvasUpdateRegistry.cs:215)
UnityEngine.Camera:Render(Camera)
Kamgam.UIPreview.UIPreview:CreateAssetPreview(Object) (at Assets/3_ThirdParty/1_Tools/UIPreview/Editor/UIPreview.cs:447)
Kamgam.UIPreview.UIPreview:createPreviewTextureForTarget(Object) (at Assets/3_ThirdParty/1_Tools/UIPreview/Editor/UIPreview.cs:175)
Kamgam.UIPreview.UIPreview:Initialize(Object[]) (at Assets/3_ThirdParty/1_Tools/UIPreview/Editor/UIPreview.cs:139)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**To Reproduce**
Copy and paste Particle System in UI with UI Particle component on it

**Expected behavior**
No errors

**Environment (please complete the following information):**
 - Version latest(3.1.7)
 - Platform: Editor(Windows)
 - Unity version: 2021.3.13f1
 - Build options: IL2CPP, Android

**Comment by dkasenko** [comment]
Same?

* Version: 4.1.7
* Platform: Editor (Windows)
* Unity version: Unity 2022.3.4f1
* Build options: IL2CPP, Android

```NullReferenceException: Object reference not set to an instance of an object
Coffee.UIExtensions.UIParticleRenderer.GetModifiedMaterial (UnityEngine.Material baseMaterial) (at ./Library/PackageCache/com.coffee.ui-particle@a499f0c046/Scripts/UIParticleRenderer.cs:121)
UnityEngine.UI.Graphic.get_materialForRendering () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Graphic.cs:514)
UnityEngine.UI.Graphic.UpdateMaterial () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Graphic.cs:675)
UnityEngine.UI.Graphic.Rebuild (UnityEngine.UI.CanvasUpdate update) (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Graphic.cs:653)
UnityEngine.UI.CanvasUpdateRegistry.PerformUpdate () (at ./Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/CanvasUpdateRegistry.cs:215)
UnityEngine.Canvas:SendWillRenderCanvases()```
