### ISSUE TITLE
After using the UIParticle component, the particle effect plays faster than when it is not used

### ISSUE THREAD

**Issue by zhanghaigang666** [mob-sakai/ParticleEffectForUGUI#259]
After using the UIParticle component, we found that the playback speed of the particle effect will be accelerated, and the playback speed will be normal after the UIParticle component is removed.

**Comment by mob-sakai** [comment]
Thank you for your reporting!
I would like to know more about this issue.

Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by HeangHorn** [comment]
Any solution for this problem

**Comment by mob-sakai** [comment]
Since there has been no new discussion for a long time, this issue was closed.
 If the same issue arises, please re-open this issue.
