### ISSUE TITLE
Make particles visible outside mask?

### ISSUE THREAD

**Issue by di00b** [mob-sakai/ParticleEffectForUGUI#261]
I know it was asked [here](https://github.com/mob-sakai/ParticleEffectForUGUI/issues/178) but I still can not figure it out all by myself! 
I know I can make a mask with carved out parts but then I would have a problem with a screen on different resolutions.
Can someone help me figuring it out as well?
(lll￢ω￢)

**Comment by mob-sakai** [comment]
Please try [UnmaskForUGUI](https://github.com/mob-sakai/UnmaskForUGUI)
