### ISSUE TITLE
Version [3.3.13] Coffee.UIExtensions.UIParticle.InitializeIfNeeded () (at Assets/Dependencies/UIParticle/UIParticle.cs:483)

### ISSUE THREAD

**Issue by jimmmmmmmmmyfunnnnnnny** [mob-sakai/ParticleEffectForUGUI#264]
Environment 
 - Version [3.3.13]
 - Platform: [Windows]
 - Unity version: [2020.3.48f1]
 - Build options: [IL2CPP, .Net 4.x, LWRP]

NullReferenceException
Coffee.UIExtensions.UIParticle.InitializeIfNeeded () (at Assets/Dependencies/UIParticle/UIParticle.cs:483)
Coffee.UIExtensions.UIParticle.UnityEngine.ISerializationCallbackReceiver.OnBeforeSerialize () (at Assets/Dependencies/UIParticle/UIParticle.cs:521)

![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/26768352/460aabb7-052b-470b-a278-877bc47b4cc4)

when i save unity prefab or scene, this error information show up ,so what's going on? how to solve it? thanks

**Comment by Apoll0** [comment]
Same with 3.3.5 (Unity 2020.3.48)
