### ISSUE TITLE
Converting invalid MinMaxAABB

### ISSUE THREAD

**Issue by anhvuive** [mob-sakai/ParticleEffectForUGUI#266]
I am doing a project on unity 2021.3.28 and got this error.
![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/6092096/c611a634-7fa3-4009-be10-3ced1f193372)
![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/6092096/f76741b0-b750-4a67-b5dd-562c9f303249)

Converting invalid MinMaxAABB
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Coffee.UIExtensions.UIParticleUpdater:BakeMesh (Coffee.UIExtensions.UIParticle) (at Assets/com.coffee.ui-particle@69bde2cf3d/Scripts/UIParticleUpdater.cs:238)
Coffee.UIExtensions.UIParticleUpdater:Refresh (Coffee.UIExtensions.UIParticle) (at Assets/com.coffee.ui-particle@69bde2cf3d/Scripts/UIParticleUpdater.cs:74)
Coffee.UIExtensions.UIParticleUpdater:Refresh () (at Assets/com.coffee.ui-particle@69bde2cf3d/Scripts/UIParticleUpdater.cs:54)
UnityEngine.Canvas:SendWillRenderCanvases ()

Mesh '': abnormal mesh bounds - most likely it has some invalid vertices (+/-inifinity or NANs) due to errors exporting.
Mesh bounds min=(-nan(ind), -nan(ind), -nan(ind)), max=(-nan(ind), -nan(ind), -nan(ind)). Please make sure the mesh is exported without any errors.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Coffee.UIExtensions.UIParticleUpdater:BakeMesh (Coffee.UIExtensions.UIParticle) (at Assets/com.coffee.ui-particle@69bde2cf3d/Scripts/UIParticleUpdater.cs:238)
Coffee.UIExtensions.UIParticleUpdater:Refresh (Coffee.UIExtensions.UIParticle) (at Assets/com.coffee.ui-particle@69bde2cf3d/Scripts/UIParticleUpdater.cs:74)
Coffee.UIExtensions.UIParticleUpdater:Refresh () (at Assets/com.coffee.ui-particle@69bde2cf3d/Scripts/UIParticleUpdater.cs:54)
UnityEngine.Canvas:SendWillRenderCanvases ()

**Comment by mob-sakai** [comment]
Thank you for your reporting!
I would like to know more about this issue.

Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by mob-sakai** [comment]
Since there has been no new discussion for a long time, this issue was closed.
 If the same issue arises, please re-open this issue.
