### ISSUE TITLE
Sorting with layer and order

### ISSUE THREAD

**Issue by lucasmontec** [mob-sakai/ParticleEffectForUGUI#272]
**Describe what help do you need**
Is it possible to sort the particles using a canvas layer and a sorting order in that layer?
Like setting it to render in the UI layer at a sorting index.

**Comment by mob-sakai** [comment]
Press `Refresh` button in the inspector to change the rendering order according to the layer.
Or, you can change the rendering order manually.

![Oct-26-2023 02-16-01](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/12690315/a5387e9c-cc7e-4a0e-b816-a2fa65cc3392)
