### ISSUE TITLE
ParticleAttractor OnAttracted Callback Question.

### ISSUE THREAD

**Issue by StevenKim1994** [mob-sakai/ParticleEffectForUGUI#274]
Hello, thank you for providing. I am using this function very well.
There seems to be a phenomenon in which the OnAttracted Callback among the UIAttractor functions cannot be called when particle particles arrive at the Attracter at the same time. What should I do to prevent this?

Best Regards.

**Comment by mob-sakai** [comment]
Hi @StevenKim1994 ,
I would like to know more about this issue.
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by mob-sakai** [comment]
Since there has been no new discussion for a long time, this issue was closed.
 If the same issue arises, please re-open this issue.
