### ISSUE TITLE
[Worker0] Import Error Code:(4) Message, in unity 2022.3

### ISSUE THREAD

**Issue by alijomeiy** [mob-sakai/ParticleEffectForUGUI#276]
I have this error after I import package via git

[Worker0] Import Error Code:(4)
Message: Build asset version error: packages/com.coffee.ui-particle/scripts.meta in SourceAssetDB has modification time of '2023-11-03T13:29:14.522095Z' while content on disk has modification time of '2023-11-03T13:29:55.8906093Z'

0x00007ff749538e4d (Unity) StackWalker::GetCurrentCallstack
0x00007ff74953ddf9 (Unity) StackWalker::ShowCallstack
0x00007ff74a50b121 (Unity) GetStacktrace
0x00007ff74abcd922 (Unity) DebugStringToFile
0x00007ff74a82b9d3 (Unity) OnDemandScheduler::OnLogToConsoleEntry
0x00007ff74a91084a (Unity) ImportWorkerManager::OnMessageReceived
0x00007ff74a91135c (Unity) WorkerManagerASIO::OnMessageReceived
0x00007ff74a9196dd (Unity) MessageReader::ReadMessage
0x00007ff74a9194c4 (Unity) MessageReader::Read
0x00007ff74a91ac8b (Unity) TcpMessagingSession::OnReceiveCompleted
0x00007ff74a8df277 (Unity) asio::asio_handler_invoke<asio::detail::binder2<<lambda_7bb410c7c74bfc0040fa015a32e4550e>,std::error_code,unsigned __int64> >
0x00007ff74a8e1bfa (Unity) asio::detail::executor_function::complete<asio::detail::binder2<<lambda_7bb410c7c74bfc0040fa015a32e4550e>,std::error_code,unsigned __int64>,std::allocator<void> >
0x00007ff74a8d73b1 (Unity) asio::io_context::basic_executor_type<std::allocator<void>,4>::execute<asio::detail::executor_function>
0x00007ff74a8e3033 (Unity) asio::detail::handler_work_base<asio::any_io_executor,void,asio::io_context,asio::executor,void>::dispatch<asio::detail::binder2<<lambda_7bb410c7c74bfc0040fa015a32e4550e>,std::error_code,unsigned __int64>,<lambda_7bb410c7c74bfc0040fa015a32e4550e> >
0x00007ff74a8f0bd5 (Unity) asio::detail::win_iocp_socket_recv_op<asio::mutable_buffers_1,<lambda_7bb410c7c74bfc0040fa015a32e4550e>,asio::any_io_executor>::do_complete
0x00007ff74a8db17e (Unity) asio::detail::win_iocp_io_context::do_one
0x00007ff74a8dcde4 (Unity) asio::detail::win_iocp_io_context::run
0x00007ff74a8ed57c (Unity) IOService::Run
0x00007ff74a8ee52b (Unity) IOService::Impl::ThreadFunction
0x00007ff7492a89a7 (Unity) Thread::RunThreadWrapper
0x00007ff8c499257d (KERNEL32) BaseThreadInitThunk
0x00007ff8c560aa78 (ntdll) RtlUserThreadStart

**Comment by mob-sakai** [comment]
I would like to know more about this issue.
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by alijomeiy** [comment]
Hi again,
thank you for your fast reply,
my problem was solved by removing the package from the project with the package manager and reinstalling it with manifest.
