### ISSUE TITLE
Special effects display abnormal when upgrading from 3.x to 4.x

### ISSUE THREAD

**Issue by HFX-93** [mob-sakai/ParticleEffectForUGUI#277]
Special effects display abnormal when upgrading from 3.x to 4.x
https://github.com/HFX-93/ParticleEffectForUGUIDemo3.3.5/archive/refs/heads/main.zip
https://github.com/HFX-93/ParticleEffectForUGUIDemo4.2.1/archive/refs/heads/master.zip
3.3.5![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/22762295/bf9c1814-5016-4077-803b-3e896c4e1651)
4.2.1![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/22762295/467ecab7-3160-4db6-a827-d3b3172640c4)

**Comment by HFX-93** [comment]
@mob-sakai I have created the project link and you can test it @

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by HFX-93** [comment]
@mob-sakai  Hello. How's it going

**Comment by mob-sakai** [comment]
@HFX-93 
Currently in progress.
Try this.
[dev.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/13277289/dev.zip)

**Comment by HFX-93** [comment]
@mob-sakai   That's great! After using the AutoScalingMode UIParticle mode, a lot of special effects have turned to normal, but I also don't understand, the inside of the AutoScalingMode. What's the use of the Transform model, for the UI, as if this pattern will not need

**Comment by HFX-93** [comment]
> @HFX-93 Currently in progress. Try this. [dev.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/13277289/dev.zip)
I found an issue where I had to switch to Transform mode and then switch back to UIParticle mode for the effects to play properly. Download my 4.2.2-dev project for more details
https://github.com/HFX-93/4.2.2-dev/archive/refs/heads/master.zip
See the video for details
![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/22762295/9c99754c-b7ba-44e5-b15e-9b6684d67a26)

**Comment by mob-sakai** [comment]
:)

> What's the use of the Transform model, for the UI, as if this pattern will not need
`AutoScalingMode.Transform` is for compatibility purposes.
Old options (ignoreCanvasScaler, autoScaling) adjust Transform.localScale.
`AutoScalingMode.UIParticle` internally adjusts `UIParticle.scale`.

> I found an issue where I had to switch to Transform mode and then switch back to UIParticle mode for the effects to play properly.
Umm, The prefab's local scale is 0.

**Comment by mob-sakai** [comment]
Added to the FAQ: https://github.com/mob-sakai/ParticleEffectForUGUI/issues/270
>If Transform.localScale contains 0, rendering is skipped.

**Comment by HFX-93** [comment]
@mob-sakai  When will the new version be updated

**Comment by mob-sakai** [comment]
ASAP
