### ISSUE TITLE
Assertion failed on expression: 'ps->array_size()'

### ISSUE THREAD

**Issue by lfarkas73** [mob-sakai/ParticleEffectForUGUI#278]
**Describe the bug**

I get two errors when I exit play mode. 
I saw this problem has been fixed earlier, but it reoccur again in the latest version.

Assertion failed on expression: 'ps->array_size()'
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Coffee.UIExtensions.UIParticleRenderer:UpdateMesh (UnityEngine.Camera) (at ./Library/PackageCache/com.coffee.ui-particle@447996ce0f/Scripts/UIParticleRenderer.cs:330)
Coffee.UIExtensions.UIParticle:UpdateRenderers () (at ./Library/PackageCache/com.coffee.ui-particle@447996ce0f/Scripts/UIParticle.cs:503)
Coffee.UIExtensions.UIParticleUpdater:Refresh () (at ./Library/PackageCache/com.coffee.ui-particle@447996ce0f/Scripts/UIParticleUpdater.cs:80)
UnityEngine.UI.ScrollRect:LateUpdate ()

Mesh '[UIParticleRenderer] Combine Instance Mesh': abnormal mesh bounds - most likely it has some invalid vertices (+/-inifinity or NANs) due to errors exporting.
Mesh bounds min=(0.00, 0.00, 0.00), max=(16001069492125579151405399003889664.00, 79316175099297370989568178471829504.00, 308585124126850166435263369183232.00). Please make sure the mesh is exported without any errors.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Coffee.UIExtensions.UIParticleRenderer:UpdateMesh (UnityEngine.Camera) (at ./Library/PackageCache/com.coffee.ui-particle@447996ce0f/Scripts/UIParticleRenderer.cs:330)
Coffee.UIExtensions.UIParticle:UpdateRenderers () (at ./Library/PackageCache/com.coffee.ui-particle@447996ce0f/Scripts/UIParticle.cs:503)
Coffee.UIExtensions.UIParticleUpdater:Refresh () (at ./Library/PackageCache/com.coffee.ui-particle@447996ce0f/Scripts/UIParticleUpdater.cs:80)
UnityEngine.UI.ScrollRect:LateUpdate ()

**To Reproduce**

1. Create and open new empty default 3D project
2. Import latest GIT package
3. Import UIParticle_Demo
4. Press play in the editor.
5. Exit play mode.
6. See error.

**Expected behavior**

No errors in the console upon exiting play mode.

**Environment (please complete the following)**

- Package version 4.2.2
- Platform: Editor(Windows), IOS platform generates the same error
- Unity version: 2022.3.7f1
- Project options: Default project settings with built-in pipeline

**Comment by mob-sakai** [comment]
The issue is not reproduced on my environment...

**Environment**

- Package version 4.2.2 (latest)
- Platform: Editor(Windows 10)
- Unity version: 2022.3.7f1
- Project options: Default, built-in pipeline

I would like to know more about this issue.

**Comment by lfarkas73** [comment]
Hello,

I played a bit with this yesterday and found one interesting "solution".
I kept only one particle system in the project for this test.

1. play it in Editor
2. stop project
3. errors appear

However, if I do the following the error disappear:

1. play it in Editor
2. select game object stores the particle system
3. deactivate it
4. activate it again
5. stop project
6. errors are no longer there

It seems if I reinitiate the particle system in runtime it works fine
without errors.
Alternatively, if I switch off the Emission in design time, start the
project and switch on the Emission in Runtime the error is not appear.

Doing some more checks today.

Regards,
Lajos

mob-sakai ***@***.***> ezt írta (időpont: 2023. nov. 8., Sze,
3:55):

**Comment by raveneer** [comment]
I also have same problems.
while play, it is ok, but when end play, error happen. 

![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/19799411/48b3eeaa-4c5f-42a9-bc63-f9889c45982d)

**Comment by mitay-walle** [comment]
Bounds of mesh are 0.0.0, that cause this error, I've added this check:
 `if (!float.IsNaN(x) && !float.IsInfinity(x) && x > 0)`

 before `_renderer.BakeMesh()` and error disappeared

**Comment by mob-sakai** [comment]
@mitay-walle 
Thank you for your reporting! 👍

**Comment by mitay-walle** [comment]
@mob-sakai sorry for missleading.

 I've done more tests and find out that in my case reason was in Noise module.

No specific parameters, but module enabling itself.
only disabling it helps. 

Error appear when i restart scene with existing UIParticle and particleSystem emission / noise modules enabled
![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/5578552/aafdc342-7bc2-4c7d-ad57-48d0ae9d5514)

**Comment by mitay-walle** [comment]
[repro.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/15462300/repro.zip)

**Comment by mitay-walle** [comment]
[BugReport.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/15462302/BugReport.zip)
