### ISSUE TITLE
Rect Mask not working on Mobile Build but in Unity Editor

### ISSUE THREAD

**Issue by Luan12134** [mob-sakai/ParticleEffectForUGUI#279]
Good Evening,
I am having a bug where the particles are showing on mobile but they are not masked.

On Editor it is working perfect, but building the project for iOS does not work as it should.

On iOS Build, it seems that the Particles attach to the object are ignoring the Rect 2D Mask Property, whereas on the Editor everything is working fine.

Do you have an idea?

I am using UI/Additive and I am using AssetBundles to download the prefabs from a server.

**Comment by mob-sakai** [comment]
Thank you for your reporting!

1. If the prefab is built-in instead of in an AssetBundle, does UIParticle function correctly?
2. Do objects other than UIParticle ignore RectMask2D?
3. If using Mask instead of RectMask2D, does it function correctly?

Could you provide information on these questions?

**Comment by mob-sakai** [comment]
Since there has been no new discussion for a long time, this issue was closed.
 If the same issue arises, please re-open this issue.
