### ISSUE TITLE
Incorrect rendering of World-space simulated particles while animating scale

### ISSUE THREAD

**Issue by jakeoconnor-peoplefun** [mob-sakai/ParticleEffectForUGUI#285]
**Describe the bug**

When animating the scale of a UIParticle's parent, the behavior of the UIParticle is inconsistent with the behavior of a normal Unity ParticleSystem. This inconsistency prevents artists from cleanly using UIParticle in the way they would use ParticleSystem normally, such as adding a sparkle trail to a flying object. 
UIParticle tries to scale itself to account for the parent scale changing, but doing so causes stretching and flattening of the particles which should remain at a consistent scale and position in World-space.

**To Reproduce**

1. Create a ParticleSystem with World simulation space.
2. Add an empty GameObject parent to the ParticleSystem, then add the UIParticle component.
3. Add an empty GameObject parent to the UIParticle.
4. Animate the parent-most GameObject's position and scale (tween, update, animator, etc.)

**Expected behavior**

World-space simulation particles linger behind the animated object leaving a trail, as they do with normal ParticleSystems implemented the same way.

**Screenshots**

https://github.com/mob-sakai/ParticleEffectForUGUI/assets/131695969/a9a300e7-450d-4cbb-be46-c9ccce8c4880

**Environment**

- Package version 4.4.0
- Platform: Editor(Mac)
- Unity version: 2021.3.25f1
- Project options: IL2CPP, .Net Framework

**Additional context**

- Reproducible minimal project
[ParticleEffectForUGUI_WorldIssue.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/13721014/ParticleEffectForUGUI_WorldIssue.zip)

**Comment by mob-sakai** [comment]
Hi @jakeoconnor-peoplefun , thank you for your reporting!
I was able to reproduce this issue in my environment as well.
This issue is occurring due to `UIParticleRenderer.ResolveResolutionChange`.
This method prevents particles simulated in world space from moving when the canvas resolution changes, but it was causing the same behavior with scale animations.

**Comment by jakeoconnor-peoplefun** [comment]
Amazing! Thank you for looking into it so quickly. Our VFX artists will be happy to hear that there's progress.
