### ISSUE TITLE
ParticleUI component breaks with "Fix any compile errors"

### ISSUE THREAD

**Issue by APTEM591** [mob-sakai/ParticleEffectForUGUI#287]
**Describe the bug**

Some (or many, if lucky) of the scripts breaks for no reason at a random moment.

**To Reproduce**

1. Add a UIParticle object (or copy+paste a component, doesn't matter)
2. Do some things such as reopen editor, update script or something like that, i can't catch a consistency.
3. Component breaks like shown on the screenshot and particle system is now default, not as UGUI.

**Screenshots**

![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/71151134/59c8eaba-4be2-4012-99c3-d00ddb7569ac)

**Environment (please complete the following)**

- Package version 4.5.1
- Platform: Editor(Windows)
- Unity version: 2022.3.10f

**Additional context**
No compile errors, but inspector says this:
![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/71151134/4315111c-ab22-49c6-9e11-93bbd9531ab5)

**Comment by mob-sakai** [comment]
@APTEM591 
Thank you for your reporting!
I would like to know more about this issue.

1. How did you install ParticleEffectForUGUI?
   - gitURL
   - OpenUPM
   - into `Packages`
   - into `Assets`

2. Open the problematic prefab or scene in a text editor, search for `m_AnimatableProperties`, and find the `m_Script` that is above it. Does the GUID for that script match `16f0b0b6d0b7542bfbd20a3e05b04ff1`?

3. Open `UIParticle.cs.meta` in a text editor and find the GUID. Does the GUID match `16f0b0b6d0b7542bfbd20a3e05b04ff1`?

**Comment by APTEM591** [comment]
> @APTEM591 Thank you for your reporting! I would like to know more about this issue.
> 
> 1. How did you install ParticleEffectForUGUI?
>    
>    * gitURL
>    * OpenUPM
>    * into `Packages`
>    * into `Assets`
> 2. Open the problematic prefab or scene in a text editor, search for `m_AnimatableProperties`, and find the `m_Script` that is above it. Does the GUID for that script match `16f0b0b6d0b7542bfbd20a3e05b04ff1`?
> 3. Open `UIParticle.cs.meta` in a text editor and find the GUID. Does the GUID match `16f0b0b6d0b7542bfbd20a3e05b04ff1`?

1. I installed this plugin with default UPM (into Packages folder).

2. On the scene the is the only object with this GUID (when the ParticleUIs are >=5), but there is another problem now because I reimported this plugin. If i add a UIParticle to any prefab, it becomes null when i reopen prefab. Also 3 of 4 new UIParticle components on the main scene sending this, which causes domain reload on every exit of play mode: 
![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/71151134/70c64d31-6d6b-4bc5-b9d0-18bd7dac3095)

**Comment by APTEM591** [comment]
Forgot to mention, these problems appeared in the latest version of a plugin. They worked absolutely fine except a bug with particles' trails, that's why I updated.

**Comment by APTEM591** [comment]
I've found a fix. I just needed to Assets/Reimport All. Weird solution, because reimporting single plugin doesn't help. But it works fine now (At least so far).
