### ISSUE TITLE
Max particle size is limited to camera's orthographic size halved in Screen Space - Camera

### ISSUE THREAD

**Issue by MaxMaletin** [mob-sakai/ParticleEffectForUGUI#291]
Reproduced with version 4.5.2 in unity 2021.3.11f1 and with version 4.6.0-preview.1 in unity 2021.3.34f1.

Steps:
1. Set canvas render mode to screen space - camera, selected camera to orthographic and camera size to something small, let's say 5
2. Create a simple particle system with size over lifetime curve. Curve's max value multiplied by initial particle size should be higher than camera's orthographic size halved.
3. Create an empty object inside of canvas, make particle system a child of the object. Add UIParticle component. Set material to UI/Default.

Expected behaviour:
Particles constantly change their size during their lifetime according to the curve. Their size is not limited.

Observed behaviour:
Size of particles increases over time until maximum is reached, then they stay at maximum size until the curve multiplied by initial size dips below camera's orthographic size halved.

![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/60336795/66d27aeb-63a8-446e-8be5-16f3bc642fd0)

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by mob-sakai** [comment]
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by MaxMaletin** [comment]
[MaxParticleSizeRepro.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/14064174/MaxParticleSizeRepro.zip)

**Comment by mob-sakai** [comment]
The issue can be resolved through two solutions:
## Solution 1: (ParticleSystem) Increase the 'Max Particle Size' in the Render module.
<img width="382" alt="image" src="https://github.com/mob-sakai/ParticleEffectForUGUI/assets/12690315/3a607ffd-dae9-47c0-bcf2-e7835aa3db14">

## Solution 2: (UIParticle) Set 'AutoScalingMode' to 'UIParticle'.
<img width="400" alt="image" src="https://github.com/mob-sakai/ParticleEffectForUGUI/assets/12690315/9c0806a4-a625-4450-bbdd-c480096d1ad2">

**Comment by mob-sakai** [comment]
By the way, I noticed that unintended scaling occurs when `AutoScalingMode=UIParticle` and `ScalingMode=Local`.
It's a bug. 😇
