### ISSUE TITLE
If only Trail Material is used, it will not be displayed

### ISSUE THREAD

**Issue by datsuya** [mob-sakai/ParticleEffectForUGUI#294]
I just wanted to use it as a UI trailer, so I set the [Renderer--Render Mode] to [None] and found that the uiParticle was not displayed. But I remember the old version I used a long time ago could be used this way.

![1868283A-C1FF-482c-90E6-CF44970B5DCB](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/11382721/58ea5419-abe0-4e25-877f-0fc9d17c1055)

**Comment by mob-sakai** [comment]
Thank you for your reporting!
