### ISSUE TITLE
Particle size too small due to auto scaling

### ISSUE THREAD

**Issue by AlmarM36** [mob-sakai/ParticleEffectForUGUI#295]
Hi,

After updating to 4.6.2 from 3.3.14, all particle sizes are too small and I've been browsing the issues page for people with similar issues. Some of our particles are correctly sized due to the GameObject Transform having a certain scale. I understand some changes were made related to scaling, causing the scaling option to be disabled under certain Auto Scaling Modes.

I've noticed that setting Auto Scaling Mode to None will enable the Transform scale again, but manually setting this back to it's original value doesn't work, because after deserialization it will still reset the scale back to (1, 1, 1). I believe this is due to auto scaling being true (even with Auto Scaling Mode to None), but there doesn't seem to be an option to turn this off entirely. Is this intended?

Thanks!

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by mob-sakai** [comment]
Please try `develop-295-disable-auto-scaling` branch.

```json
"com.coffee.ui-particle": "https://github.com/mob-sakai/ParticleEffectForUGUI.git?path=Packages/src#develop-295-disable-auto-scaling",
```

**Comment by AlmarM36** [comment]
Hi,

That allows me to change the scale again, so that's perfect. I did notice however that it still doesn't reproduce the exact same particle size as before the upgrade to version 4. It's somewhat smaller.

After version update
- Transform.localScale = (1, 1, 1)
- UIParticle.Scale = 1
![after-update](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/138454086/2f3a13ca-31e4-4732-b114-426b390a4400)

After version update with UIParticle auto scale mode and original transform scale
- Transform.localScale = (25, 25, 25)
- UIParticle.Scale = 1
- Auto Scale Mode = UIParticle
![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/138454086/169c8bf1-68da-4d9b-9066-6200bff15e1c)

Original correct size
- No version update
![original](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/138454086/e5a5df71-6c77-49ff-b982-c470f36840f7)

I can fix this myself by copying the value that UIParticle sets to the transform scale automatically into UIParticle.Scale and resetting the transform scale back to it's original size with Auto Scale Mode set to None or UIParticle.

Manual fix
- Transform.localScale = (25, 25, 25)
- UIParticle.Scale = 4.971429 (automatically calculated by UIParticle after version update)
- Auto Scale Mode = UIParticle
- Latest v4 version
![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/138454086/eb4401dc-ca4d-4295-905d-6ba847d9b13c)

Is this the intended behaviour?

On a side note, sometimes I get the following exception, but I'm unsure how to reproduce it:
```
NullReferenceException: Object reference not set to an instance of an object
Coffee.UIExtensions.UIParticleRenderer.GetWorldScale () (at Library/PackageCache/com.coffee.ui-particle@692c3e8798/Runtime/UIParticleRenderer.cs:522)
Coffee.UIExtensions.UIParticleRenderer.Set (Coffee.UIExtensions.UIParticle parent, UnityEngine.ParticleSystem ps, System.Boolean isTrail) (at Library/PackageCache/com.coffee.ui-particle@692c3e8798/Runtime/UIParticleRenderer.cs:252)
Coffee.UIExtensions.UIParticle.RefreshParticles (System.Collections.Generic.List`1[T] particles) (at Library/PackageCache/com.coffee.ui-particle@692c3e8798/Runtime/UIParticle.cs:475)
Coffee.UIExtensions.UIParticle.OnEnable () (at Library/PackageCache/com.coffee.ui-particle@692c3e8798/Runtime/UIParticle.cs:289)
```

Thanks!
