### ISSUE TITLE
Play on awake checkbox doesn't work

### ISSUE THREAD

**Issue by MaxMaletin** [mob-sakai/ParticleEffectForUGUI#296]
Tested with version 4.6.2, unity versions 2021.3.11f1 and 2021.3.34f1.

Open demo scene. Uncheck play on awake on any particle system. Expected result: when you hit play, there are no particles. Observed result: checkbox doesn't do anything, particle systems start emitting on awake.

There are obvious workarounds to this, like calling Stop or disabling the gameobject, but I thought I should report it anyways.

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by mob-sakai** [comment]
The issue is not reproduced on my environment.
 If the same issue arises, please re-open this issue.
