### ISSUE TITLE
Some UIParticleRenderer HideFlags were set to None but some were set to HideAndDontSave

### ISSUE THREAD

**Issue by OYMQKUX** [mob-sakai/ParticleEffectForUGUI#297]
Tested with version 4.6.2, unity versions 2020.3.39f1.
I was testing UIParticle in my project. When I tried to find the UIParticle renderer, some renderers cannot be found in hierarchy. So I read the source code and figure out that all renderers' hideFlags are set to HideAndDontSave, but what's weird is that in my project, some renderers' hideFlags are still set to None. I wonder that when and where the hideFlags are set None. Thank you very much.

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by mob-sakai** [comment]
It is likely an older version of the object.
If you're concerned, deleting the GameObject will regenerate the UIParticleRenderer that was set to HideAndDontSave.
