### ISSUE TITLE
Particles Issue IOS 

### ISSUE THREAD

**Issue by aneeb111** [mob-sakai/ParticleEffectForUGUI#298]
Hello, I am experiencing an issue on iOS devices where the UI Particles load normally on the first launch, but after relaunching or restarting the application, the UI particles do not show up or render. No errors are displayed. However, it is working fine on Android devices. Kindly help.

**Comment by mob-sakai** [comment]
Thank you for your reporting!
I would like to know more about this issue.

**Comment by mob-sakai** [comment]
Since there has been no new discussion for a long time, this issue was closed.
 If the same issue arises, please re-open this issue.
