### ISSUE TITLE
Can't not revert to origin position after simulate

### ISSUE THREAD

**Issue by hmkc** [mob-sakai/ParticleEffectForUGUI#299]
In UIParticleRenderer.Simulate() , after move to scaled position, simulate, the particle system transform can not revert to origin position.
When isLocalSpace is true, scaledPos equals originWorldPosition.when execute move to scaled position, the psTransform's position is still the same, but its localPosition is changed.So psTransform can not revert to origin position.
In my project, it is avaliable to use SetLocalPositionAndRotation to revert to origin position.
![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/43198537/7d997096-7866-4506-9dec-cb491a22ddb8)

**Comment by HotChocoTea** [comment]
oh, i met this question too! my device type is fold phone. sometimes the effect will far from origin pos

**Comment by HotChocoTea** [comment]
Unfortunately, I used your code and my situation has worsened. My effect is in local space, and it occasionally drifts away slowly from its original position

**Comment by mob-sakai** [comment]
Thank you for your reporting!
I would like to know more about this issue.
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)
