### ISSUE TITLE
Reset previous position on start play for Simulation space World

### ISSUE THREAD

**Issue by PragmaGame** [mob-sakai/ParticleEffectForUGUI#303]
I have a particle that looks like a "Trail" [Simulation space World, Emission Rate over Distance]. I also have a particle pool. Taking a uiparticle from the pool, I change its position (game object was active), then turn on the effect and the particle leaves a trace equal to the distance between the spawn position and the current one, since the renderer will save the previous position of the particle. The problem was solved by setting the current position to the previous one.

**Comment by mob-sakai** [comment]
Thank you for your reporting!
I would like to know more about this issue.
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)
