### ISSUE TITLE
Unity2021.3.23，例子特效调整HDR，没有效果

### ISSUE THREAD

**Issue by smclhy** [mob-sakai/ParticleEffectForUGUI#307]
I tried to adjust the HDR of the effect, but there was no change in performance

**Comment by mob-sakai** [comment]
Thank you for your reporting!
I would like to know more about this issue.
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by mob-sakai** [comment]
Since there has been no new discussion for a long time, this issue was closed.
 If the same issue arises, please re-open this issue.
