### ISSUE TITLE
Resource ID out of range in GetResource: 1048576 (max is 1048575)

### ISSUE THREAD

**Issue by SAMYTHEBIGJUICY** [mob-sakai/ParticleEffectForUGUI#308]
I'm 100% sure that this package is the cause of the issue in the title as it stopped when I removed the UI particle system. Unfortunately unity's error messaging here gives almost nothing to go on.

**Comment by mob-sakai** [comment]
I would like to know more about this issue.
Tell me about your develop/build environment.
 - version [e.g. 3.3.10]
 - Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL]
 - Unity version: [e.g. 2022.2.0f1]
 - Build options: [e.g. IL2CPP, .Net 4.x, URP/HDRP]

**Comment by SAMYTHEBIGJUICY** [comment]
Heya sorry I do really love this git and I thank you for sharing it but yes this almost impossible to get info on error seems related to this asset being in my scene. 

version [4.2.1]
Platform: [it's happening in my editor after I leave it running for about 45mins - I'm on windows]
Unity version: [2022.3.22f1]
Build options: [built in editor]

**Comment by SAMYTHEBIGJUICY** [comment]
Doing a bit more digging with the memory profiler... will close this issue until I can categorically say this is from this asset. Sorry mob, don't want to falsely accuse.

**Comment by SAMYTHEBIGJUICY** [comment]
I figured this out.. it is due to this asset for certain and I know why now. So I have some particle system under a new PB UI element. But I keep it disabled. Here you can see that after some time no camera or UI auto generated particle elements exist. 
![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/139700621/f6a411f7-8e2a-4f1b-85bc-834a6a82ce4a)
 When I reactive this object the camera comes back but the settings are Clear Flags: "skybox", culling mask "Everything"
![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/139700621/e68b0fcf-ca9b-42c5-9082-4698736fe417)
![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/139700621/4627e86f-2b0c-4e7c-b8c9-40afa4ef965f)
These settings are what generate the error. Can't the new camera be instantiated without these settings - clear flags set to Depth Only and Culling mask set to Nothing? Also why does the camera get destroyed after some time if the object is disabled? This is definitely the issue.

**Comment by SAMYTHEBIGJUICY** [comment]
![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/139700621/a872b70c-0514-4451-a427-f3aa7caa0163)
This starts spamming if the camera has these settings. But if I change the settings back to what they should be and then disable my UI, eventually the camera will get destroyed and re-instantiated with the default settings.

**Comment by SAMYTHEBIGJUICY** [comment]
hehe I added this to the GetBakeCamera() method:            

 // Set the camera properties
            _orthoCamera.clearFlags = CameraClearFlags.Depth;
            _orthoCamera.cullingMask = 0; // Nothing
            _orthoCamera.allowHDR = false;
            _orthoCamera.allowMSAA = false;
            _orthoCamera.renderingPath = RenderingPath.Forward;

**Comment by SAMYTHEBIGJUICY** [comment]
++ _orthoCamera.useOcclusionCulling = false; // Disable occlusion culling

**Comment by mob-sakai** [comment]
@SAMYTHEBIGJUICY 
Thanks for your great cooperation! 👍 

Your excellent research will fix a major glitch!
If you don't mind, I would like to add you as a collaborator.
May I treat you as an AUTHOR when I commit these changes?
(or create a new pull request to the develop branch)

**Comment by SAMYTHEBIGJUICY** [comment]
ohh that's so nice of you of course! thank you! Perhaps my scenario is not common but with a large game scene with the second camera this definitely shows this unity leak more easily. I worked through the issue with some helpful people in this thread: https://forum.unity.com/threads/resource-id-out-of-range-in-getresource-1048576-max-is-1048575-on-linux.993201/#post-9875301

Anyway two cameras with an "Everything" culling mask is definitely the culprit, and if we don't need it better to set it to Nothing. I switched everything else off just in case as above. 

Upgraded my sponsorship so you can have whipped cream and coffee from me hehe.

**Comment by mob-sakai** [comment]
> Upgraded my sponsorship so you can have whipped cream and coffee from me hehe.

Oh, thank you!
And cheers to one new contributor! :coffee:

![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/12690315/78d1ee87-a151-475f-bb2d-adf71b14bd3b)
