### ISSUE TITLE
"Is there a way for me to display a trail on the UI that follows the position of a particle without moving the particle?"

### ISSUE THREAD

**Issue by thanhloccc** [mob-sakai/ParticleEffectForUGUI#309]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Describe what help do you need**
A description of the question.

**Additional context**
Add any other context or screenshots about the question here.

**Comment by mob-sakai** [comment]
Since there has been no new discussion for a long time, this issue was closed.
 If the same issue arises, please re-open this issue.
