### ISSUE TITLE
Particle not showing on Android, while on editor it works 

### ISSUE THREAD

**Issue by ColorTwist** [mob-sakai/ParticleEffectForUGUI#31]
I am using Canvas with Render mode- `Screen Space - Overlay`
I also have a camera set to Solid Color (black) and Culling Mask is Everything, if that matters.
Added a particle into the Canvas as a child, and added UIPartcile and pressed FIX to update Particle Children, everything works perfectly in Editor, while on Android i do not see the particle.
![untitled-4](https://user-images.githubusercontent.com/23701561/50514673-6bbf6680-0aa8-11e9-973d-97b5ca57ffd6.png)

There are no LOG errors - which means it's not shaders or material missing.
I guess it just shows up but hidden for some reason.

**Comment by mob-sakai** [comment]
I would like to know more information on this issue.
* Please tell me the version of Unity you are using. [e.g. 2018.2.8f1]
* Can you submit a reproducible minimum project for this issue?

**Comment by ColorTwist** [comment]
Version 1.3.1 (downloaded yesterday)
Version 2018.2.18f.

I can try to make a new project with same canvas settings/camera and assuming it will replicate.
I tried to use different particle and and still same result (not showing up on android)
In general you have tested it on Android with ParticleEffectForUGUI  1.3.1?

**Comment by mob-sakai** [comment]
>In general you have tested it on Android with ParticleEffectForUGUI 1.3.1?
No. I tested it in the previous version...

**Comment by ColorTwist** [comment]
Ok, i'll try to do a simple test. hopefully it will replicate..  Where do i sent it to in case it works?

**Comment by ColorTwist** [comment]
ok, i have a simple test with default particle not showing on android but showing on editor.
Here it is: 
[ParticleEffectForUGUI_android_bug.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/2714979/ParticleEffectForUGUI_android_bug.zip)

Load: SampleScene

**Comment by mob-sakai** [comment]
Thanks a lot!
I am sorry that I can not test right away.

**Comment by ColorTwist** [comment]
Sure.  Try it when you can, hope it is something simple 👍

**Comment by dvillaseca** [comment]
We had a similar problem
Seem like the UIParticle Graphic is not setting itself dirty sometimes on android, by forcing setdirty on the UpdateMesh function everything works fine, but idk if what is the performance impact

**Comment by ColorTwist** [comment]
> We had a similar problem
> Seem like the UIParticle Graphic is not setting itself dirty sometimes on android, by forcing setdirty on the UpdateMesh function everything works fine, but idk what is the performance impact
> 
> edit: don't do this, it generates tons of garbage

Thanks for the update. How did you end up displaying particles in Canvas on android ?

**Comment by mob-sakai** [comment]
I tested demo scenes on Android.
It worked well with `Screen Space - Overlay`.
Unity 2018.2.14f1

**Comment by mob-sakai** [comment]
* The script execution order is `-100`  
![](https://user-images.githubusercontent.com/12690315/50531211-b2b16880-0b49-11e9-9c0a-1e97cc0a2a0f.png)
* Used shaders are `UI/Additive` and `Mobile/Particle/Additive`
![](https://user-images.githubusercontent.com/12690315/50531236-16d42c80-0b4a-11e9-9350-b6d9a87084b0.png)

**Comment by ColorTwist** [comment]
Hey, 
Thanks for the reply.

The ZIP file i provided contains, _unitypackage_. I could not upload .unitypackage TO Git, as it says it's an unsupported format, that is why i zipped it.

Your test result is from my unitypackage demo?

**Comment by mob-sakai** [comment]
I got it!
Mac's archive utility does not seem to be able to decompress it correctly.
Using `unzip` command generated unitypackage.

**Comment by ColorTwist** [comment]
> I got it!
> Mac's archive utility does not seem to be able to decompress it correctly.
> Using `unzip` command generated unitypackage.

Great! Hope you will see it now as i see it.

**Comment by mob-sakai** [comment]
I tested as following:
* Create a new project
* Import @ColorTwist 's test package
* Add "Sample Scene" to scenes in built
* Build & run

**>>>> Result: Particles are not displayed**

<br><br>
Oddly enough, the following steps will **work correctly.**
* Turn off ParticleSystem.Renderer  
![](https://user-images.githubusercontent.com/12690315/50537876-7150a580-0ba9-11e9-93fd-311e42dac160.png)
* Save the scene
* Build & run

**Comment by mob-sakai** [comment]
Probably I found a way to fix the issue 👍

**Comment by mob-sakai** [comment]
Please try this:
https://raw.githubusercontent.com/mob-sakai/ParticleEffectForUGUI/develop/Assets/Coffee/UIExtensions/UIParticle/UIParticle.cs

**Comment by ColorTwist** [comment]
Here are the results:
**Before using your fix:**
1. With project i sent you, it did fix it by disabling ParticleSystem.Renderer
2. With my project that has more complex particle with children, it partly fixed, some showed, some didn't.
**After updating UIParticles fix:**
It worked with my project and the more complex particle (with children)! You are genius  :)

Will do more tests soon.

**Comment by mob-sakai** [comment]
Fixed version has been released :)

**Comment by ColorTwist** [comment]
Great, seems to be fine now! 
Thanks.
