### ISSUE TITLE
Particle's localPosition drifts at certain scales due to floating-point precision issues

### ISSUE THREAD

**Issue by Wheresmykeyboard** [mob-sakai/ParticleEffectForUGUI#312]
**Describe the bug**
The localPosition of UIParticle unexpectedly changes/moves.

**To Reproduce**
1. Open 'Demo.scene'.
2. Play the scene.
3. The particle named 'Par_Moving' is moving slowly.

**Expected behavior**
The UIParticle's position should not change.

**Environment (please complete the following information):**
 - Version [4.6.6]
 - Platform: [Any]
 - Unity version: [2022.3.13f1]

**Additional context**

The psTransform.position changes after calling SetPositionAndRotation(origPos, origRot). We suspect this behavior is due to floating-point precision issues. By recording the original localPosition and setting it back after Simulate(), it appears possible to avoid this change.

```csharp
    private void Simulate(Vector3 scale, bool paused)
    {
        ...
        var originWorldPosition = psTransform.position;
        var originWorldRotation = psTransform.rotation;
        ...
        psTransform.SetPositionAndRotation(originWorldPosition, originWorldRotation);   // after this line, psTransform.position changed
    }

**Comment by Wheresmykeyboard** [comment]
[Demo0524.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/15428617/Demo0524.zip)
here‘s the demo

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by mob-sakai** [comment]
ref #299
