### ISSUE TITLE
When Canvas Scalar working, UIParticleAttractor 's calculated position is wrong

### ISSUE THREAD

**Issue by msyzzm** [mob-sakai/ParticleEffectForUGUI#314]
**Describe the bug**
When Canvas Scalar working (game resolution not equal to Canvas Scalar Reference Resolution), UIParticleAttractor 's calculated position is wrong. Partical System Simulation Space is Local.

**Environment (please complete the following information):**
 - Version 4.2.1
 - Platform: Editor(Windows)
 - Unity version: 2022.3.28f1
 - Build options: IL2CPP, .Net Standard 2.1, HDRP

**Comment by mob-sakai** [comment]
Thank you for your reporting!
The issue is reproduced on my environment.

Set Simulation Space to world as a workaround.

**Comment by msyzzm** [comment]
> Thank you for your reporting! The issue is reproduced on my environment.
> 
> Set Simulation Space to world as a workaround.

If set Simulation Space to world, there is another porblem.
When the Scale is 1 in *UIParticle* component and *Partical System*'s position is (0,0,0), it's ok. But, for example, if change the scale to 2, and Partical System's position to (0,1,0), partical will start at (0,2,0).

**Comment by mob-sakai** [comment]
- Try using the `Absolute Mode` option.
- Try placing the ParticleSystem under the UIParticle in hierarchy view.
  ![](https://user-images.githubusercontent.com/12690315/95007356-c6a4cb00-0649-11eb-9316-562f4bce3f31.png)
- Try upgrading UIParticle to v4.7.0

Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by msyzzm** [comment]
[UIPartical.zip](https://github.com/user-attachments/files/15907873/UIPartical.zip)
Enter Play Mode to reproduce.

**Comment by mob-sakai** [comment]
I played the project, but nothing happened.
Therefore, I made the following changes:

- Score (UIParticleAttractor)
  - Add Image component
  - Add UIElementDragger component. (Drag object to move in game view)
- UIBurstPoint (ParticleSystem)
  - Looping = true
  - PlayOnAwake = true
- Canvas (CanvasScaler)
  - UIScaleMode = ScaleWithScreenSize
  - ReferenceResolution = 800x600

I tested it with several resolutions, but the issue did not reproduce...

https://github.com/mob-sakai/ParticleEffectForUGUI/assets/12690315/30d176d9-ef7f-40ae-af1a-2cddba6ddfc7

**Comment by msyzzm** [comment]
You can select these UIParticals in Hierachy, then click the Play button in Scene view.

https://github.com/mob-sakai/ParticleEffectForUGUI/assets/11918719/579f5046-6413-499a-aab2-e107001335ef

**Comment by mob-sakai** [comment]
Try using `Simulation Space` to `Local` with v4.7.0

**Comment by msyzzm** [comment]
Local is good. But the first bug is refer to Simulation Space Local.

**Comment by mob-sakai** [comment]
> Environment (please complete the following information):
> Version 4.2.1

Perhaps upgrading to v4.7.0 fixed that.

**Comment by msyzzm** [comment]
> > Environment (please complete the following information):
> > Version 4.2.1
> 
> Perhaps upgrading to v4.7.0 fixed that.

Tried. Not fixed.

**Comment by mob-sakai** [comment]
?
Sorry if my English is incorrect, but I want to clarify the situation:

- What problem were you trying to solve? Was it resolved?
- What does this mean?
  - > Local is good. But the first bug is refer to Simulation Space Local.
- Your uploaded project used `ParticleSystem.simulationSpace=World`. Should this be treated as a separate issue?

**Comment by msyzzm** [comment]
My goal is that CanvasScaler and UIPairtcleAtracter can work properly at the same time. So I raised the first bug, and after you responded with a solution（*Set Simulation Space to world as a workaround*）, I raised the second bug. 
These are really two questions. Solving any one of them will allow me to achieve my goal.

**Comment by mob-sakai** [comment]
I see.

**Comment by mob-sakai** [comment]
From here, [UIPartical.zip](https://github.com/user-attachments/files/15909759/UIPartical.zip)

- Add CanvasScaler  
  ![](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/12690315/874c0e79-07ca-49a4-a776-7aa44b534538)
- UIParticle.autoScalingMode=UIParticle  
  ![](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/12690315/bb99c9d2-2100-4b34-bf6e-25f0dd094733)
- ParticleSystem.simulationSpace=Local  
  ![](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/12690315/c4bd8e6f-3dad-4e06-86e2-601caeb81a9c)
- Transform.Scale=(1,1,1)  
  ![tr](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/12690315/5d113ace-bb42-4b9b-8e39-206f4f2dab9c)

![](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/12690315/f720942e-3c2f-493f-a48e-1cc301488fe0)
[UIPartical_fixed.zip](https://github.com/user-attachments/files/15934752/UIPartical_fixed.zip)

**Comment by msyzzm** [comment]
That works!
Thank you.
