### ISSUE TITLE
UIParticles disappear abruptly on Game view

### ISSUE THREAD

**Issue by jfez** [mob-sakai/ParticleEffectForUGUI#315]
Hey! I've found something weird since I got my UIParticles working flawless on the Editor view, disappearing with a fade done by the Color over Lifetime property after the Start Lifetime has passed, however, the exact same particles on the Game view are disappearing abruptly way before the Start Lifetime is done. 

Does this issue sound familiar to you? Am I doing something wrong? Thanks!
![UIParticlesIssue](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/44475543/e038cf1f-cbd8-431e-b235-4069232bb343)

**Comment by mob-sakai** [comment]
Thank you for your reporting!
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by jfez** [comment]
Yeah, of course, here you go! Thanks!
[TestUIParticles.zip](https://github.com/user-attachments/files/15901526/TestUIParticles.zip)

**Comment by mob-sakai** [comment]
It appears that the Noise module is causing particles to move out of bounds.
Setting `ParticleSystem.transform.localScale.z = 0` fixed the issue, and the particles are displayed correctly.
![](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/12690315/3fcceda2-5498-4cf8-9530-5f14e4f68264)
![](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/12690315/b591bc23-7a1b-4ba6-bc24-85f83f53eb65)

**Comment by jfez** [comment]
Hey! That approach almost fixed it, however I was getting these errors:
![Errors](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/44475543/d5afdc1d-441c-46f9-829d-197ed10ef4d2)
Also, `ParticleSystem.transform.localScale.z = 0` is not valid to me since when using actual seagulls, they rotate based on Z axis; so what I've done to make it finally work is to use a extremely low value, something like `ParticleSystem.transform.localScale.z = 1e-10` and now it works like a charm.

Thank you so much for your help!
