### ISSUE TITLE
Particles spawn too close to the camera

### ISSUE THREAD

**Issue by MihaMarkovi** [mob-sakai/ParticleEffectForUGUI#319]
Unity version: 2021.2.20f1
Package version: 4.9.0

Hello! I have encountered the problem with particles spawning too close to the camera as shown on the picture below. In this example, Auto Scaling mode is set to "UI Particle".
![particles](https://github.com/user-attachments/assets/0cb71357-2497-48b5-84d1-67a8a327dc53)

When I set Auto Scaling Mode to "None", that seems to fix the issue, but particles are now way too large.
![particles2](https://github.com/user-attachments/assets/10aa173a-6268-4caf-a628-60186a0d4ca0)

Am I doing something wrong? Thanks in advance.

**Comment by mob-sakai** [comment]
Thank you for your reporting!
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by MihaMarkovi** [comment]
[ParticlesBug.zip](https://github.com/user-attachments/files/16311540/ParticlesBug.zip)

**Comment by mob-sakai** [comment]
@MihaMarkovi 
In haste, here is the workaround:

```csharp
// Assets/Games/Test/Scripts/LuckyChip.cs (178)
// _particles2DCircle.Play();
// _particles2DStars.Play();
var uip = GetComponentInChildren<UIParticle>();
uip.enabled = false;
uip.enabled = true;
_particles2DCircle.Simulate(0);
_particles2DStars.Simulate(0);
await MoveChipToPosition(_initialPosition, playPlaceAnimation);
...
```

**Comment by mob-sakai** [comment]
https://github.com/user-attachments/assets/6ef399a1-6399-4087-beed-1e6f0238abe

**Comment by mob-sakai** [comment]
[fixed.webm](https://github.com/user-attachments/assets/4948656e-3f53-485b-967b-dbd9bb001c1b)

**Comment by MihaMarkovi** [comment]
Thanks for fix @mob-sakai !
I have implemented your solution, but Simulate method resets particles when you call it multiple times, which I don't want, so I replaced it with Play. When using Play method, particles are still drawn in front of the camera, but no I at least dont see them, so that works fine for me.
Do you by any chance know when this will be fixed?

**Comment by mob-sakai** [comment]
Unfortunately, a fundamental fix is hard to find.
A better solution is to control emissions with `ParticleSystem.emission.enabled=true/false` instead of `ParticleSystem.Play()/Stop()`.

```csharp
ParticleSystem.main.looping = true;
ParticleSystem.main.playOnAwake = true;
ParticleSystem.emmision.enabled = false;
```

![](https://github.com/user-attachments/assets/0db21212-941b-4b6c-af1c-10a933d5918d)

```csharp
// _particles2DCircle.Play();
// _particles2DStars.Play();
GetComponentInChildren<UIParticle>().StartEmission();
await MoveChipToPosition(_initialPosition, playPlaceAnimation);
GetComponentInChildren<UIParticle>().StopEmission();
// _particles2DCircle.Stop();
// _particles2DStars.Stop();
...
```
