### ISSUE TITLE
Particles are not active in pause game state.

### ISSUE THREAD

**Issue by redeye001** [mob-sakai/ParticleEffectForUGUI#325]
Hello bro,
- I am very grateful for the system you shared, it works very well and is very useful for me, however I am having a problem with pausing the game and your effects are also stopped and not working.
- I am making a window in the game pause screen that shows an effect using particles. However the particles are not working with your plugin.

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by mob-sakai** [comment]
Set `ParticleSystem.deltaTime` to `Unscaled`.

[](https://github.com/user-attachments/assets/52283f23-ce9f-4c59-bd68-922ba6666254)

**Comment by redeye001** [comment]
Oh, great, thank you so much, I did it. 🤩🤩🥰🥰


Vào Th 4, 14 thg 8, 2024 vào lúc 19:03 mob-sakai ***@***.***>
đã viết:
