### ISSUE TITLE
How to use Material Property Block with ParticleUI?

### ISSUE THREAD

**Issue by AlirezaF80** [mob-sakai/ParticleEffectForUGUI#328]
I have several Particle Systems managed by a UIParticle component. I want to set textures on some of the materials using Material Property Blocks (MPBs).
Applying MPBs to particle system materials not managed by UIParticle works as expected.
However, when a particle system is managed by UIParticle, applying MPBs directly to it, it doesn't work.
Additionally, I haven't found any way of setting a custom MPB for each material, using UIParticle itself.

**Comment by mob-sakai** [comment]
Try setting the property name of the texture in `Animatable Properties`.

**Comment by mob-sakai** [comment]
@AlirezaF80 
Has that been fixed??
