### ISSUE TITLE
particleSystem with trail display with offset, the farther away from the center, the greater the offset.

### ISSUE THREAD

**Issue by wyjxp** [mob-sakai/ParticleEffectForUGUI#329]
particleSystem with trail display with offset, the farther away from the center, the greater the offset.

**Screenshots**
![560967d22c70505804b2143f72d18a85](https://github.com/user-attachments/assets/1b630af7-df86-4813-9f31-ecc36c53f681)
![b7b6d051b7c4d071df968b1113991f79](https://github.com/user-attachments/assets/c078afd3-8172-46e3-aee5-af2c7cef2cbf)
https://github.com/user-attachments/assets/94e58bce-cedc-4b71-bd9e-d476b5295eca

**Environment (please complete the following information):**
 - Version [4.9.1]
 - Platform: [Editor(Windows)]
 - Unity version: [e.g. 2021.3.14f1]

**Comment by mob-sakai** [comment]
Thank you for your reporting!
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?
Of course, you don't need to include any secret assets from your project. Feel free to use free assets instead.

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by mob-sakai** [comment]
Please try `PositionMode=Absolute`.
![](https://github.com/user-attachments/assets/7594ed57-da94-4c28-8fe0-32371e39df57)
