### ISSUE TITLE
How to resize particles to fit UI container

### ISSUE THREAD

**Issue by jgib332** [mob-sakai/ParticleEffectForUGUI#332]
Unity Version: 2022.3.20f1
ParticleEffectForUGUI Version: 4.9.1

I am unsure if I'm using the wrong UI Particle settings or if Auto Scaling Mode is not working correctly.

1. Create a Canvas
2. Create an empty container object under the Canvas, set anchor to stretch, set Left, Right, Top and Bottom to 0.
3. Create a Particle System under the container object (**Effects > Particle System**).  _NOTE_ I am NOT using (UI > Particle System).
4. Set the anchor of the Particle System to stretch, set Left, Right, Top and Bottom to 0.
5. Set the Scaling Mode of the Particle System to "Hierarchy".
6. Select the container object, add a UI Particle component.  Set the Auto Scaling Mode to "UI Particle", set the UI Particle component Scale to 1.
7. Select the Particle System and set the emitter shape to "Edge", edit the emitter to span the width of the canvas, increase the Start Size so particles are visible.
8.  Open the Simulation tab and change the device to something with a different aspect ratio. 

You will see that the particles do not stretch to fit the width of the canvas.  If the system is created on iphone ratio it will be too small after switching tp an ipad ratio.  If the system is created on an ipad ratio it will be too big after switching to an iphone ratio.

How can I get my particles to resize correctly under the Canvas or under a container that changes size under different aspect ratios?

**Comment by mob-sakai** [comment]
Please try to change the `UIScaleMode` of the root `CanvasScaler` to `Scale With Screen Size`.
![](https://github.com/user-attachments/assets/2ce44fac-0ce4-4120-b7a4-c5eaae189939)

Here’s an example with a slightly different setup.  
The anchor of the `ParticleSystem` was set to bottom = 0.

[2024-09-21 20.40.15.webm](https://github.com/user-attachments/assets/eb522437-8825-4164-9cf9-84037f5a7288)

You may notice that as the resolution increases, the particle density decreases.  
By using `AutoScalingMode=Transform`, it will automatically scale based on the canvas scale.
(This option is optimal for hierarchy scaling.)

[2024-09-21 20.49.56.webm](https://github.com/user-attachments/assets/d29cf895-2c83-43b3-9f5d-18c5c941f600)
