### ISSUE TITLE
trail incorrect offset

### ISSUE THREAD

**Issue by fghj0810** [mob-sakai/ParticleEffectForUGUI#335]
**Describe the bug**
![图片](https://github.com/user-attachments/assets/0f9dc286-11c3-48ec-bf1c-0792f974e6f3)

**To Reproduce**
1. Set Scale 0.5
![图片](https://github.com/user-attachments/assets/beb8d330-3005-4b5f-ba80-8eeadabd11d5)
2. Set PositionMode. set auto scaling mode.
![图片](https://github.com/user-attachments/assets/5b451fad-83db-41bc-950b-6ba63035eedc)
3. check world space
![图片](https://github.com/user-attachments/assets/4993b1a0-6ab3-455e-9252-4136818bc4be)

**Expected behavior**
trail follow patricles

**Environment (please complete the following information):**
 - Version [4.9.1]

**Additional context**
I want to control the position of the UIParticle through code, so that the particle can follow the position I set and have the correct Trail effect. For example, a coin moves from one position on the screen to another position with a trailing effect. If the Scale of the Layout node is 1, then the behavior is correct. I suspect there is an issue with the handling in this area.

**Comment by mob-sakai** [comment]
Thank you for your reporting!
