### ISSUE TITLE
UIParticle.asset Will generate a new one,when I open unity every time

### ISSUE THREAD

**Issue by h824612113** [mob-sakai/ParticleEffectForUGUI#342]
Unity Version:2022.3.47f1
UIParticle.asset Will generate a new one,when I open unity every time.
![image](https://github.com/user-attachments/assets/bef0c8b2-787e-4d0e-9fb7-eb7922bfacfb)

After I launched Unity,I got two error.
![image](https://github.com/user-attachments/assets/0f236016-bf12-437b-983b-b155658fd2a7)

Below is error stack
![image](https://github.com/user-attachments/assets/7279b33c-ebe1-44e2-99ae-d8548a09e737)

Error Two:
![image](https://github.com/user-attachments/assets/1b9c9067-f220-443f-9f35-5748f35494f2)

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by promiselonely** [comment]
The generated directory is also incorrect. It will be generated under Asset instead of ProjectSettings, which is the same level directory as Asset

**Comment by mob-sakai** [comment]
UIEffect and SoftMaskForUGUI had the same problem.

This problem will be fixed soon. 👍
