### ISSUE TITLE
Serializing 3D Scaling to Prefabs

### ISSUE THREAD

**Issue by skyewontmiss** [mob-sakai/ParticleEffectForUGUI#346]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Describe what help do you need**
I want to toggle 3D scaling in a prefab, then have it retroactively apply to all prefabs, so that i can set all of their 3D values inside of a script they all have.

They apply, but not during playmode. They appear to reset to uniform scaling.

**Comment by mob-sakai** [comment]
Thank you for your reporting!
Tell me about your develop/build environment.
 - version [e.g. 4.10.0]
 - Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL]
 - Unity version: [e.g. 2022.2.0f1]
 - Build options: [e.g. IL2CPP, .Net 4.x, URP/HDRP]

Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?
Of course, you don't need to include any secret assets from your project. Feel free to use free assets instead.

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by skyewontmiss** [comment]
Hi! Thanks so much for the swift reply.

version 4.10.4
Platform: Windows - Unity Editor
Unity version: 2021.3.12f1
Build options: .Net 4.x

_really hoping this isn't broken_
Project File: https://filetransfer.io/data-package/UUz7bCxq#link

Open scene "Button Test" to see the issue.

If you search "Button" in the Project panel, click this prefab:
![image](https://github.com/user-attachments/assets/5ddfa124-1495-4281-8a6c-25e3fda2fd11)

And you can edit the UIParticle via:
![image](https://github.com/user-attachments/assets/e9e63724-a744-45d2-b337-a1c4cce497df)

Do tell me if there are any issues with my files. Thanks!

**Comment by mob-sakai** [comment]
Thank you.
