### ISSUE TITLE
When moving the transform in world simulation mode, particles don't behave as expected

### ISSUE THREAD

**Issue by crmagicxxx** [mob-sakai/ParticleEffectForUGUI#37]
First, thanks for this great plugin :)

I found 2 issues, when using particles in World Simulation Space:

1) If your canvas is in Screen Space Camera, moving particles around works as expected. But as soon as you increase the UI Particle Scale, world simulated particles don't behave as expected anymore
2) If your canvas is in Screen Space Overlay, then no matter what's UI Particle Scale, particles transform don't work. Just try moving particles (in Simulation Space World) around and you'll see

All of this happens in Unity 2018.3.* - didn't test in older versions

**Comment by mob-sakai** [comment]
Hi @crmagicxxx 
Thank you for your reporting!

I would like to know more information on this issue.
Can you submit a reproducible project for this issue?

**Comment by crmagicxxx** [comment]
I am out right now, will try during the day
In the meantime, it's easy to reproduce really. Just make a simplest particle, make it world simulation space. Put inside Screen Space Overlay and try to move it around. Similar thing happens even in Screen Space Camera if you adjust the UI Particle Scale property

**Comment by mob-sakai** [comment]
Bug 1: This bug has been reproduced. `UIParticle.scale = 1` on the left side and `UIParticle.scale = 2` on the right side.
![](https://user-images.githubusercontent.com/12690315/52271654-a1008380-2987-11e9-8afc-51bfe634d78e.gif)

Bug 2: Does this bug behave the same as bug 1...?

**Comment by crmagicxxx** [comment]
2) Maybe it's the same bug, but when you're in Screen Space Overlay, even if you set particle scale to 1, you can't adjust the transform of the world simulated particles without visible glitches

**Comment by mob-sakai** [comment]
I have good news for you, @crmagicxxx !
I found a way to fix bug 1! :+1:
![](https://user-images.githubusercontent.com/12690315/52338840-d2905200-2a4e-11e9-8e53-14b39808ecad.gif)

Please test whether bug 2 is reproduced using the unitypackage. ;)
[fixed.unitypackage.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/2836189/fixed.unitypackage.zip)

**Comment by crmagicxxx** [comment]
Tested and confirming that everything works as expected - bug 1 & bug 2 fixed :)
Can you please update the package manager version to reflect this change?

Thank you very much for prompt reaction!
Best :)

**Comment by mob-sakai** [comment]
Thank you for your testing!
I'll release it later!
