### ISSUE TITLE
UIParticle.Scale - Rendering Order Issue

### ISSUE THREAD

**Issue by RyouBakura** [mob-sakai/ParticleEffectForUGUI#39]
Hey, 

on the pictures below you see a particle behind a blue box.

![observation](https://user-images.githubusercontent.com/26061253/52643195-cc7df380-2edc-11e9-97f4-23751cc33b34.png)

Picture 1: A particle is scaled by 200. Particle size: 1. Doesn't respect render order.
Picture 2: Another particle is scaled by 1 but the particle size is set to 200. Works nicely.
Picture 3: Both particles are enabled and both are working nicely(?!).
Picture 4: That's the canvas that was used.

Honestly, this is not a big issue since everything works fine as long the particle scale is left untouched. Thank you for making this amazing plugin~ ^__^

**Comment by mob-sakai** [comment]
Hi @RyouBakura 
Thank you for your reporting.

I understand what you mean.
It is strange...

**Comment by mob-sakai** [comment]
I would like to know more information on this issue.
Can you submit a reproducible project for this issue?

**Comment by mob-sakai** [comment]
This issue is similar to #34.

**Comment by RyouBakura** [comment]
Thanks, that fixed it. :) 

It must be some weird Unity bug because if I set the value back to `0.00` it keeps working temporarily until Unity restarts.
