### ISSUE TITLE
Particles are generated twice.

### ISSUE THREAD

**Issue by Accky** [mob-sakai/ParticleEffectForUGUI#40]
Applying the UI particle component to the ParticleSystem will result in two same particles.
Is there a way to avoid it?
ParticleSystemにUI Particleコンポーネントを適用すると、パーティクルが2重に発生します。
回避する方法はありませんか？

env: Unity 2018.3.5f1 / UI Particle v2.1.1

**Comment by mob-sakai** [comment]
Hi @Accky 
Thank you for reporting.

In edit mode, disable the Renderer module.
![](https://user-images.githubusercontent.com/12690315/53057022-d44b2280-34f0-11e9-98db-516ae16dfd85.png)

Editモードにおいては、 Rendererモジュールをdisableにしてください。

**Comment by Accky** [comment]
Hi, @mob-sakai.
Sorry, I didn't understand the basic about UI Particle.
Thank you for telling me how to use!
