### ISSUE TITLE
UV Animation is not work.

### ISSUE THREAD

**Issue by Accky** [mob-sakai/ParticleEffectForUGUI#41]
I add UI Particle component to ParticleSystem, And set UV animation by AnimationClip.
But Animation is not reflected.
Please tell me how to reflect material animation.

like this.
![image 1](https://user-images.githubusercontent.com/43546359/53068063-5439b280-351a-11e9-98f2-9638571403b8.png)

env: Unity 2018.3.5f1 / UI Particle v2.1.1

**Comment by mob-sakai** [comment]
Hi @Accky 
Thank you for reporting.

Can you submit a reproducible project for this issue?

**Comment by Accky** [comment]
Thank you for waiting!
Please receive a reproducible project.

[Test Project.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/2883264/Test.Project.zip)

**Comment by mob-sakai** [comment]
Thank you, the issue is reproduced on my environment.

**Comment by mob-sakai** [comment]
[WIP]
I found a way to fix the issue!
![feb-20-2019 21-49-35](https://user-images.githubusercontent.com/12690315/53092979-77378700-3559-11e9-82d0-19628973e539.gif)

**Comment by Accky** [comment]
Amazing!
I can't wait to release fixed UI Particle!

**Comment by mob-sakai** [comment]
The animation modifies the ParticleSystemRenderer's MaterialPropertyBlock.
MaterialPropertyBlock changes the material properties without changing shared material itself.
However, CanvasRenderer can not use MaterialPropertyBlock...
Therefore, copy the value from MaterialPropertyBlock to CanvasRenderer as follows:

```cs
MaterialPropertyBlock mpb = new MaterialPropertyBlock ();
_particleSystemRenderer.GetPropertyBlock (mpb);
_canvasRenderer.GetMaterial (0).SetVector ("_MainTex_ST", mpb.GetVector ("_MainTex_ST"));
```

**Comment by mob-sakai** [comment]
The problem here is that **any property in the shader can be changed** by animation.
It may be difficult to support all properties...

**Comment by Accky** [comment]
Thank you for telling me the solution!
I will create and use a component that copies  MaterialPropertyBlock to CanvasRenderer for test.

Is it correct to write this program in Update function?

**Comment by Accky** [comment]
I understand that it is difficult to support all the properties.
I thought it would be better to make each component as needed.

**Comment by mob-sakai** [comment]
>Is it correct to write this program in Update function?
No, insert it at the end of the `UpdateMesh` method.

And now, there is hope for the issue.
I can see the light at the end of the tunnel!

**Comment by Accky** [comment]
Great!
I'm looking forward to it!

**Comment by mob-sakai** [comment]
[WIP] **Animatable Property** supports all properties in shader!
![](https://user-images.githubusercontent.com/12690315/53185782-0a98b700-3643-11e9-9262-feee3d7cfeb6.gif)

Can I publish your assets as a demo?

**Comment by Accky** [comment]
@mob-sakai, Of course!
but, please replace fbx file to this.
Old fbx include private information in file path...
[test_00_model.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/2891972/test_00_model.zip)

**Comment by mob-sakai** [comment]
Thanks a lot!

**Comment by mob-sakai** [comment]
[WIP] Support changing material property by AnimationClip
![](https://user-images.githubusercontent.com/12690315/53243774-463b8b80-36ec-11e9-9e71-44571cd05a64.gif)
