### ISSUE TITLE
v2.2.0 has 2 warnings

### ISSUE THREAD

**Issue by crmagicxxx** [mob-sakai/ParticleEffectForUGUI#44]
- UIParticle.cs(59,23): warning CS0649: Field 'UIParticle.AnimatableProperty.m_Type' is never assigned to, and will always have its default value 
- UIParticle.cs(57,11): warning CS0649: Field 'UIParticle.AnimatableProperty.m_Name' is never assigned to, and will always have its default value null

When serializing private fields, Unity will throw a warning about default values. So there should be:

`string m_Name = null;`
`ShaderPropertyType m_Type = ShaderPropertyType.Color; // or any other default one`

Or `#pragma` to suppress those warnings...

**Comment by mob-sakai** [comment]
Hi @crmagicxxx 
Thank you for reporting!
