### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by pimpace** [mob-sakai/ParticleEffectForUGUI#46]
Unity 2018.3.7f1
UIParticle 2.2.1

![ui_particle_report](https://user-images.githubusercontent.com/18311524/53780001-b2936780-3f02-11e9-86c6-065f10410175.jpg)

When attached UIParticle to my particle system, it will disable the rendering in all layer below. 
And, as you can see in the pic, when I set Animatable Properties, it will add ANOTHER shader component above the existed one.... is this as intended?

**Comment by mob-sakai** [comment]
Hi @pimpace 
Thank you for reporting.

>When attached UIParticle to my particle system, it will disable the rendering in all layer below.

Sorry, I don't understand what you meen...
About ParticleSystem.'s Renderer module?
UIParticle disable it on attached or on playing.

>And, as you can see in the pic, when I set Animatable Properties, it will add ANOTHER shader component above the existed one.... is this as intended?

Yes.
When using "Animatable Properties", the material is instantiated newly.
I recommend that you do not use it except when necessary.

**Comment by pimpace** [comment]
"UIParticle disable it on attached or on playing."

???

Then what renderer will render my particles on screen? Because of this, on play there is no particles. UIParticle  disables all particles render in hierarchy chain. I don't get it. 
When I read all of your setting manual, it was logical, but now I can't get this to work.

**Comment by mob-sakai** [comment]
CanvasRenderer renders it. (This expression is **not accurate.**)

I would like to know more information on this issue.
Can you submit a reproducible project for this issue?

**Comment by pimpace** [comment]
Oh got it. Sorry Mate, seems, my hierarchy struct wasn't correct. And your manual not exactly points out to that root object (a transfrom) needs canvas renderer component. So that's was the problem.
Everything works great!
You know when you create an empty object to be a root, Unity wont add CR component by default even if you created it as a child of a canvas. So I suggest you add this to your manual: "make sure your root object HAS a canvas renderer component" or something like this. :)

However, scaling is a bit odd. I have some particles when I needed to set ignore parents option, and set scaling up to 300+ (even over 600) to see my particle. Moreover the root transform object also has about 75. 

Maybe it's ok, due to what if if you have very large scale of particle by default.... I don't know.

Anyway, Dude, this is an amazing job, keep it up and thanks!

**Comment by mob-sakai** [comment]
Ohh that makes sense!
You added UIParticle component to ParticleSystem in play mode, right?

About scaling ...
Certainly, it is strange.
I will check it later.
