### ISSUE TITLE
Not working on latest Unity version (2019.3.0a5)

### ISSUE THREAD

**Issue by pabloleban** [mob-sakai/ParticleEffectForUGUI#50]
Some imports such as `UnityEditor.UI` and `UnityEngine.UI` are not being found.

![image](https://user-images.githubusercontent.com/13904174/59139822-5e1ddf00-896c-11e9-9f3b-967d69107c2b.png)

**Comment by mob-sakai** [comment]
Hi @pabloleban 
Thank you for reporting!

**Comment by mob-sakai** [comment]
The same thing is reported here.
Unity UI Lead Developer is working on this issue.
https://forum.unity.com/threads/ui.673504/

Let's wait his working and a good news. :)
