### ISSUE TITLE
If ParticleSystem.Shape is set to Edge, an exception will be thrown.

### ISSUE THREAD

**Issue by hitsuji-dev** [mob-sakai/ParticleEffectForUGUI#51]
#### Steps to reproduce the issue

1.  Use Unity2019.1 and ParticleEffectForUGUI2.3.0
2.  Create a Canvas in Scene.
3.  Create a empty GameObject in Canvas.
4.  Add a ParticleSystem component.
5.  Add a UI-Particle component.
6.  Set the ParticleSystem.Shape to Edge.

#### How to fix it.

Scripts\Editor\UIParticleEditor.cs :602
`#if UNITY_2019_1_OR_NEWER`
        `float radius = Call<float> (typeof (Handles), "DoSimpleEdgeHandle", Quaternion.identity, Vector3.zero, shapeModule.radius, true);`
`#else`
        `float radius = Call<float> (typeof (Handles), "DoSimpleEdgeHandle", Quaternion.identity, Vector3.zero, shapeModule.radius);`
`#endif`

References
https://github.com/Unity-Technologies/UnityCsReference/blame/master/Editor/Mono/EditorHandles/SimpleRadiusHandle.cs#L12

Thank you.

**Comment by mob-sakai** [comment]
Hi @hitsuji-dev 
Thank you for your reporting.
Can you create a pull request to fix it?
I will merge and release it ASAP! :)

**Comment by hitsuji-dev** [comment]
Thank you for your support.
I created a pull request. Please review it. Thank you.
--
I created a pull request for the first time, so I'm sorry if I make a mistake.

**Comment by mob-sakai** [comment]
@hitsuji-dev 
Many thanks! 👍
