### ISSUE TITLE
v2.3.0 Setting position of particles in script doesn't work well

### ISSUE THREAD

**Issue by aurnut** [mob-sakai/ParticleEffectForUGUI#53]
Hello,

I have an issue when I try to change the position of the UI particles in script (to move them towards a RectTransform target).

Basically, here is what I do:
`particles[i].position = Vector3.LerpUnclamped(particles[i].position, target.position, step);`
(I tried with Vector3.MoveTowards and the issue is the same)

I have the same problem in Local space and World space.

The position where the particles go seem to depend on the ParticleSystem position (I can see that easily when I move the emitter while the particles are moving).

I use Unity 2018.4.1f1 and v2.3.0 of ParticleEffectForUGUI.

Do you think the issue can come from this plugin? Or am I doing something wrong?

**Comment by mob-sakai** [comment]
Hi @aurnut 
I would like to know more information on this issue.
Can you attach the script?

**Comment by aurnut** [comment]
Sure, here it is:
[ParticlesDirection.txt](https://github.com/mob-sakai/ParticleEffectForUGUI/files/3501260/ParticlesDirection.txt)

**Comment by mob-sakai** [comment]
In my environment, it works.
* Set `ParticleSystem.SimulationSpace` to `World`
* If `UIParticle.scale` is large, decrease `ParticlesDirection.speed`

![Aug-15-2019 00-24-07](https://user-images.githubusercontent.com/12690315/63033716-0adb8600-bef3-11e9-8836-de4701a31730.gif)

**Comment by aurnut** [comment]
Here the target is the black square and you can see that the end destination of the particles is not the same as the position of the target.

I first move the ParticleSystem and the particles end destination moves (but it shouldn't because the target doesn't move). Then I move the target and the end destination moves (which is ok but it's still not on the target).

I may misunderstand how all that works so I'll clarify what I want to achieve: I want the red particles to end on the black square. How can I do this?

Also, I've found out that when I change the value of UIParticle.scale, it changes the end destination.

![particle issue](https://user-images.githubusercontent.com/38286447/63040601-0d73b680-bec6-11e9-87bb-4f2cd8ebfd57.gif)

**Comment by mob-sakai** [comment]
I see.
Probably the effect of the TRS matrix transform.

**Comment by bsymon** [comment]
Hi ! Is there any news on this issue ? I have the exact same problem.
I've set Simulation Space to World, and I set the position the particles manually in a Job (IJobParticleSystemParallelFor). My code works when the component UIParticle is disabled. But when it's enabled, the position is wrong. And it's depend on the resolution too.

**Comment by aurnut** [comment]
Hello, this doesn't answer the question, but it can help you. I've solved my issue by using another plugin: https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/wiki/Controls/UIParticleSystem
