### ISSUE TITLE
Is IL2CPP builds supported ? 

### ISSUE THREAD

**Issue by Otd2** [mob-sakai/ParticleEffectForUGUI#54]
It is working on editor smoothly but not quite sure how to use it in my builds. When I try this on Android, it crashed with this error log : 

```
10-04 01:26:02.381 22282 22304 E Unity   : NullReferenceException: Object reference not set to an instance of an object.
10-04 01:26:02.381 22282 22304 E Unity   :   at Coffee.UIExtensions.UIParticle.UpdateMesh () [0x00000] in <00000000000000000000000000000000>:0
10-04 01:26:02.381 22282 22304 E Unity   :   at Coffee.UIExtensions.UIParticle.UpdateMeshes () [0x00000] in <00000000000000000000000000000000>:0
10-04 01:26:02.381 22282 22304 E Unity   :   at UnityEngine.Canvas+WillRenderCanvases.Invoke () [0x00000] in <00000000000000000000000000000000>:0
10-04 01:26:02.381 22282 22304 E Unity   : Coffee.UIExtensions.UIParticle:UpdateMesh()
10-04 01:26:02.381 22282 22304 E Unity   : Coffee.UIExtensions.UIParticle:UpdateMeshes()
10-04 01:26:02.381 22282 22304 E Unity   : UnityEngine.WillRenderCanvases:Invoke()
10-04 01:26:02.381 22282 22304 E Unity   :
10-04 01:26:02.381 22282 22304 E Unity   : (Filename: currently not available on il2cpp Line: -1)
```

**Comment by mob-sakai** [comment]
Hi @Otd2 

I would like to know more information on this issue.

**Environment (please complete the following information):**

Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac)]
Unity: [e.g. 2018.3.0f1]
ParticleEffectForUGUI: [e.g. v2.3.0]

**Comment by Otd2** [comment]
Hey there,
**Platform** 
- Editor : Windows
- Build Target : Android with il2cpp

**Versions**
-Unity : 2019.1.4f1
-ParticleEffectForUGUI : 2.3.0

**Comment by mob-sakai** [comment]
Thank you!

**Comment by mob-sakai** [comment]
@Otd2 Can you submit/attach a minimal repro project for this issue?

**Comment by ColorTwist** [comment]
For me it works fine with IL2CPP, maybe you forget to refresh some object.
