### ISSUE TITLE
Rotate the particle rect  ,May cause out of bounds 

### ISSUE THREAD

**Issue by Liiiz** [mob-sakai/ParticleEffectForUGUI#55]
Particle not use shape, mode is billboard.
I Rotate the rect to (90, 0 , 0), some paticle the render will no work.

i try this to solve：
if (0 < m_ParticleSystem.particleCount)
  {
   ....
    _mesh.SetVertices(s_Vertices);
   //Recalculate the bounds
   _mesh.RecalculateBounds();
   ....
 }

**Comment by Liiiz** [comment]
#

**Comment by mob-sakai** [comment]
Hi @Liiiz 

Thank you for your reporting!
