### ISSUE TITLE
Particles appear correctly in scene view, but turn black in game view

### ISSUE THREAD

**Issue by suryaonthenet** [mob-sakai/ParticleEffectForUGUI#56]
Created a particle system in my canvas and attached UIParticle to it. The particles appear perfectly in scene view, but turn completely black in game view. Anyone else facing this too?

**Comment by mob-sakai** [comment]
Hi @suryaonthenet 

I would like to know more information on this issue.
Can you attach a minimal repro project for this issue?

**Comment by suryaonthenet** [comment]
Okay this issue does NOT seem to affect the Play Mode and the build. But it happens in the game view when not in play. So not really critical, but an issue nevertheless.

**Repro:**
New Scene > Create Canvas > Create Particle System under Canvas > Attach UI Particle to Particle System

**Result:**
Particles render in Scene view, but appear black in Game view.

**Comment by mob-sakai** [comment]
This only happens when `Canvas.RenderMode = Screen Space - Overlay`.
Maybe, `Default-ParticleSystem` material and `Particle/Standard Unlit` shader do not support `Screen Space - Overlay`.
