### ISSUE TITLE
UI darker than normal when change to linear color space

### ISSUE THREAD

**Issue by PZZZB** [mob-sakai/ParticleEffectForUGUI#57]
In gamma space,there is no issue.
but when change color space from gamma to Linear.
The UIParticle become darker than normal.

![image](https://user-images.githubusercontent.com/7671107/67396604-753b3180-f5da-11e9-8b99-ec7005c0654d.png)

same params:
![image](https://user-images.githubusercontent.com/7671107/67396828-d82cc880-f5da-11e9-8d95-687aeb9b2caf.png)

**Comment by mob-sakai** [comment]
Hi @PuzzledBoy 

Thank you for your feedback.
I would like to know more information on this issue.

Can you attach a minimal repro project for this issue?

**Comment by PuzzledBoy** [comment]
Hi,@mob-sakai ,thanks your reply.
Here is a small package that reproduce the issue:
[Issue57.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/3766248/Issue57.zip)
Export from Unity 2019.3,default render pipeline,inside has a preset file make sure both normal particle and ui particles has same params.
And don't forget change color space to linear.

Thanks again.

**Comment by mob-sakai** [comment]
WIP

![Unity_2018_3_11f1_Personal_-_Issue_57_unity_-_ParticleForUGUI_-_PC__Mac___Linux_Standalone__Personal___Metal_](https://user-images.githubusercontent.com/12690315/74329992-32dd7080-4dd4-11ea-8561-5b162a3501e4.png)

![Unity_2018_3_11f1_Personal_-_Issue_57_unity_-_ParticleForUGUI_-_PC__Mac___Linux_Standalone__Personal___Metal_-2](https://user-images.githubusercontent.com/12690315/74330004-37a22480-4dd4-11ea-8208-f20fa91a7e87.png)
