### ISSUE TITLE
[Question] Performance

### ISSUE THREAD

**Issue by MartinGonzalez** [mob-sakai/ParticleEffectForUGUI#58]
Hey, first of all this looks really promising so thanks for sharing it!
This is not an issue, iI would like to know if you did any performance test on devices (mobile perhaps) and see if it's to heavy or not.

Thanks again!

**Comment by mob-sakai** [comment]
Hi @MartinGonzalez 

Sorry, I didn't test detail performance.
However, it is lighter than traditional solution ([UIParticleSystem](https://forum.unity.com/threads/free-script-particle-systems-in-ui-screen-space-overlay.406862/), using extra Canvas or Camera. See [description](https://github.com/mob-sakai/ParticleEffectForUGUI#description)).
