### ISSUE TITLE
how to use custom Vertex Streams in particlesystem with uiparticle

### ISSUE THREAD

**Issue by tongbenchuan** [mob-sakai/ParticleEffectForUGUI#59]
our particle use the feature of custom Vertex Streams in particle then i find that it doesnt work, can you give me an idea of how to solve it? thanks

**Comment by mob-sakai** [comment]
Hi @tongbenchuan 

Sorry, custom vertex stream is not supported. #49 
I'm not familiar with Custom vertex stream.
I think that custom vertex stream is just a "data projection", so you can create a shader without CVS.

**Comment by tongbenchuan** [comment]
thanks alot ill try it
