### ISSUE TITLE
Children inherit parent Particle effect

### ISSUE THREAD

**Issue by ColorTwist** [mob-sakai/ParticleEffectForUGUI#60]
I was wondering, I want to use ParticleEffectForUGI for screens transaction, but since my screen contains also UI elements (As children), the effect won't include the UI elements, but just the image the effect is within.

I know you plan to release a feature that does that, meanwhile, is there a workaround you know?

by the way, this is a great asset!

**Comment by mob-sakai** [comment]
Hi @ColorTwist 

I’m happy to hear that. :)
Can you attach a screenshot about this issue?

**Comment by ColorTwist** [comment]
Hey
Example:
Parent -> Has Dissolve Effect
      UI Text (Child, doesn't have dissolve effect)  
      UI Text (Child, doesn't have dissolve effect)  
      .....

If I place Dissolve effect on Parent I would like it to also affect its Children without placing Dissolve effects on all the children since I have many (since it's the main menu).

**Comment by mob-sakai** [comment]
???
I don’t know what you’re talking about...
Is it UIEffect?

**Comment by ColorTwist** [comment]
yea sorry, I meant for UIEffect.
Wrong git :\

**Comment by mob-sakai** [comment]
OK, I would like to know more information on this issue.
Can you attach a screenshot or gif animation about this issue?

**Comment by ColorTwist** [comment]
Hey, thanks for your assistance.
I already wrote about it once here: (see feature request)
https://github.com/mob-sakai/UIEffect/issues/188
