### ISSUE TITLE
Abnormal Mesh Bounds with Particle Trails.

### ISSUE THREAD

**Issue by PaulRdi** [mob-sakai/ParticleEffectForUGUI#61]
When I try to play a particle system with trails I get this error:
![image](https://user-images.githubusercontent.com/8560641/70392877-6d95e780-19e4-11ea-8e5b-151f99d440b4.png)

It uses a combination of noise and velocity over lifetime to move the particle for which rendering is disabled. Only the trials should get rendered. I'm using a mobile particle material on this element for better performance. I'm fine with the particle not supporting masking.

I am editing the particle system inside a prefab.

![image](https://user-images.githubusercontent.com/8560641/70392868-6078f880-19e4-11ea-9943-13412f955620.png)

**Comment by mob-sakai** [comment]
Hi @PaulRdi 

I would like to know more information on this issue.
Can you attach a minimal repro project?

Or, Is #55 related to your issue?

**Comment by PaulRdi** [comment]
Heya sorry for the late answer, there was alot of stuff happening and I forgot.
I don't think the issue is related to #55 :/ And unfortunately we now switched to a screenspace camera. I'm afraid I can't really help. We just switched the canvas to camera space and used the regular particle systems.

Here's the particle systems settings. I can check if I can reproduce this tomorrow.

![image](https://user-images.githubusercontent.com/8560641/71315816-f6d9ff00-2465-11ea-9c10-fa5b36ac9d34.png)

![image](https://user-images.githubusercontent.com/8560641/71315826-1b35db80-2466-11ea-9255-724135621324.png)

![image](https://user-images.githubusercontent.com/8560641/71315831-2b4dbb00-2466-11ea-92fd-d79cba19d6ac.png)

**Comment by mob-sakai** [comment]
@PaulRdi 

Thank you for your information.

Can you attach a minimal repro project for this issue?
It will help to solve the issue.

**Comment by maxvinters** [comment]
Got the same issue.  A minimal repro attached. I tested it importing to the new project.
https://www.sendspace.com/file/org45i

**Comment by mob-sakai** [comment]
Hi @maxvinters 

I imported your unitypackage but it didn't work...
Can you zip only the following directories and attach it here?

- Assets
- ProjectSettings
- Packages

**Comment by maxvinters** [comment]
Hello) @mob-sakai 
Here you go)
https://www.sendspace.com/file/yzps3q

**Comment by mob-sakai** [comment]
Thank you @maxvinters 

If the rendering mode is AAA, it seems to be happening.

![image](https://user-images.githubusercontent.com/12690315/75760814-3f256f80-5d7b-11ea-9921-9544304a2635.png)

**Comment by maxvinters** [comment]
@mob-sakai Any thoughts how to fix this?)
P.S. Noticed that frequency of issue appearence deopends on lifetime, emission rate and other attributes that makes particle system bigger)

**Comment by mob-sakai** [comment]
No problem, the issue is similar to #69. :)

**Comment by maxvinters** [comment]
@mob-sakai thanks. I'll update) 
BTW cool package, bro! Thanks for it

**Comment by PaulRdi** [comment]
Oh fuck! So sorry :( I shoud have contributed more but it was a hustle because the project is nda'd and there was alot happening etc. etc. Thanks @maxvinters and cool package and maitenance indeed @mob-sakai !

**Comment by WeslomPo** [comment]
Hi in preview.8, when you set RenderMode == None, trails will disappear with regular particles as well.
I need render only trails :(.

**Comment by WeslomPo** [comment]
Hi again. After I commented hotfix 
``` if (_renderer.renderMode == ParticleSystemRenderMode.None) return; ```

I placed similiar check before
```_renderer.BakeMesh(_mesh, cam, true);```

And error is disappear.

```
Profiler.BeginSample("Bake Mesh");
var cam = rootCanvas.renderMode == RenderMode.ScreenSpaceOverlay
    ? UIParticleOverlayCamera.GetCameraForOvrelay(rootCanvas)
    : canvas.worldCamera ?? Camera.main;

if (!cam)
{
    return;
}
if (m_IsTrail)
{
    _renderer.BakeTrailsMesh(_mesh, cam, true);
}
else {
    // #61: When ParticleSystem.RenderMode=None, an error occurs
    if (_renderer.renderMode != ParticleSystemRenderMode.None)
        _renderer.BakeMesh(_mesh, cam, true);
}
Profiler.EndSample();
```

**Comment by mob-sakai** [comment]
@WeslomPo 
Thanks!
