### ISSUE TITLE
Big performance hit when no particles are played

### ISSUE THREAD

**Issue by Necka44** [mob-sakai/ParticleEffectForUGUI#62]
Hello there,

I'm having an issue. I basically have an inventory with around 30 slots. Each slot has two particles. All the particles are not playing on awake and only called to be played or stopped via script. 

Example: Player drag and drop an item in one of these slots: particles play and don't loop.

I've been very careful for any kind of particles system to be completely stopped. So if I open the inventory nothing is playing at all and only certain actions will play 1 particle system at a time.

Example of one slot: 
![UI_Particles_Perf_2](https://user-images.githubusercontent.com/39954105/70559326-ba192880-1b86-11ea-8a74-cb7876878e90.jpg)

My UI has some scripts that I need to access even when the UI is not shown. So I don't disable the UI but hide it with a canvas group.

When Disabling the Inventory UI game object that has the slots with particles I have around 350 fps (for reference)
When the Inventory is enabled on screen or not (canvas group) it drops to 160-200 fps.

The profiler shows a lot happening with UIEvents.WillRenderCanvases every frames

![UI_Particles_Perf](https://user-images.githubusercontent.com/39954105/70559083-5abb1880-1b86-11ea-9b6e-a1086423836c.jpg)

Is there any solution that doesn't involve disabling the game objects to help with that issue?

**Comment by mob-sakai** [comment]
Hi @Necka44 

I would like to know more information on this issue.
Can you attach a minimal repro project for this issue?

>So I don't disable the UI but hide it with a canvas group.

Which do you mean?
1. Enable/disable Canvas component
2. Fading with CanvasGroup.alpha

**Comment by Necka44** [comment]
Hello,

Our project is quite.. huge and some assets especially from the UI are not allowed to be shared.. I can try to make something up but I thought the description would be enough with the profiler info

I meant CanvasGroup.alpha. Disabling the Canvas component doesn't change the issue, the UI Particles component keep running in the background, which is my issue

When I meant I don't disable the UI I meant I don't disable the GameObject, this is a pre-requirement. 

Also the main point is, hidden or not the performances impact is really huge and I narrowed it down with the profiler that the culprit is the UI Particles component :(

I thought it would be "active" only when actually playing particles

**Comment by mob-sakai** [comment]
I see.
Does it mean that "UIParticles that shouldn't work" are working?

Please know that English is not my native language, and I may make some confusing mistakes.

**Comment by mob-sakai** [comment]
If you want to use the same particle effect in each slot, there is a solution using RenderTexture, Camera and RawImage.

**Comment by Necka44** [comment]
[UIParticlesTroubleshooting.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/3950041/UIParticlesTroubleshooting.zip)

Hello, here is a very small repro project

I understand that language can be confusing if you are not a native speaker, I have been to Japan several times and nobody understood my Japanese :)

So the problem:
UiParticle component is working all the time even when there are no particles playing
This result in a huge performance impact as the components are in multiple objects

The test project:
-It has multiple slots with particles that will only enable when your pointer enter the slot and when you click in the slot
-If you don't hover or click anything: no particles are playing, but if you check the Profiler, the UiParticle components are very intensive on performance
-I added 2 buttons to enable and disable all UiParticle Components at once to see the performance difference

Conclusion: If it is possible, the UiParticle component should sleep when not being active

The test project was created in Unity 2019.2.13 with the latest UiParticle package from GitHub

Thank you very very much by advance for your support

**Comment by mob-sakai** [comment]
@Necka44 
Thank you for your cooperation.
Try to add the following code to UIParticle.cs(line 361).
```cs
if (m_ParticleSystem && 0 == m_ParticleSystem.particleCount)
{
	if(0 < _mesh.vertexCount)
	{
		Profiler.BeginSample("Skip Rendering");
		_mesh.Clear();
		canvasRenderer.SetMesh(_mesh);
		Profiler.EndSample();
	}
	return;
}
```

It seems a great improvement! 😄 

Before:
![](https://user-images.githubusercontent.com/12690315/70620854-a4c1fe00-1c5b-11ea-8147-0942348f3279.png)

After:
![](https://user-images.githubusercontent.com/12690315/70620768-717f6f00-1c5b-11ea-8212-f6178fc89dd6.png)

**Comment by Necka44** [comment]
Thanks for the update, yes it's way better now :)

Great support!
