### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by Kill-Console** [mob-sakai/ParticleEffectForUGUI#63]
As the BakeMesh API changes the mesh of the canvasRenderer, the canvas contains the UIParticle component will rebuild every frame. 
My experiment: I compare 10000 ParticleSystems and 10000 UIParticles, the FPS are both about 10. But when I create 5000 other Texts and Images in the same canvas, the ParticleSystems remains 10 FPS, the UIParticles decreases to 2 FPS. The reason is the canvas will reorder the 20000+ elements and batch their meshes before rendering.
It seems if the UI is complicated, we need to create specific canvas for the UIParticles component to seperate with other components.

**Comment by mob-sakai** [comment]
Hi @Kill-Console 

Thank you for your reporting!
Can you submit a minimal repro project for this issue?

In general, separating moving UI elements on a separate canvas improves performance.
Or, there is another solution that uses Camera and RenderTexture.
![](https://user-images.githubusercontent.com/12690315/41765085-0291b3e2-763e-11e8-827b-72e5ee9bc556.gif)

**Comment by fadedFantastic** [comment]
BakeMesh API changes the mesh of the canvasRenderer, that make the whole canvas which include UIParticle component will rebuild every frame. You can see Canvas.SendWillRenderCanvas be invoked every frame. So for performance reason, UIParticle should separated on a separate canvas? Is this better than other approaches in performance?

**Comment by mob-sakai** [comment]
@fadedFantastic 
Sorry for my late reply.
Could you please attach a minimal project that reproduces the issue?

UIParticle will not call `SetLayoutDirty` or `SetMaterialDirty` for each frame.
However, when there are UI elements to be animated in the same canvas, the separation of the canvases can improve performance.
