### ISSUE TITLE
Not supported gravity

### ISSUE THREAD

**Issue by eonyanov** [mob-sakai/ParticleEffectForUGUI#65]
Can you add support GravityModifier?

**Comment by eonyanov** [comment]
I found temp solution - using "Velocity over Lifetime" module.

**Comment by mob-sakai** [comment]
@eonyanov 
Sorry for my late reply.
In my environment, UIParticle using GravityModifier seems to be working fine.
- v1.0.0-preview.9
- Unity 2018.3.14f1
- Mac

![Apr-30-2020 11-43-00](https://user-images.githubusercontent.com/12690315/80666744-2534ae80-8ad8-11ea-8c46-d3e51d4122dd.gif)

Could you please attach a minimal project that reproduces the issue?

**Comment by eonyanov** [comment]
Yes, it's working fine. Before I used old version. )
