### ISSUE TITLE
particle render  in running mode the render tab will be uncheck and then no particle render

### ISSUE THREAD

**Issue by xiangyuan** [mob-sakai/ParticleEffectForUGUI#66]
![image](https://user-images.githubusercontent.com/914843/72243748-b0705e00-3627-11ea-8677-785d8dc23e8e.png)

the top picture is editor mode

the picture bellow show in running mode
![image](https://user-images.githubusercontent.com/914843/72243913-0c3ae700-3628-11ea-925a-c69578cac4b1.png)

unity version 2019.2.17f

**Comment by leehans** [comment]
I'm experiencing an issue where a particle system with child particle systems only render the root. Not sure if the issue posted here is the cause of it. 

I tried commenting out the lines that disable the renderers, but then it just shows an unscaled version of the child particle systems. 

The root plays (and is scaled) properly, fyi.

Awesome library by the way!!!

**Comment by mob-sakai** [comment]
Hi @xiangyuan ,

Thank you for your information.

Can you attach a minimal repro project for this issue?
It will help to solve the issue.

**Comment by xiangyuan** [comment]
@mob-sakai  sorry for late response 
here the example project download , i don't know whether you can download. waiting your response
link: https://pan.baidu.com/s/1CBriegEVr7dp0-vRABkahQ code: 56jb

Awesome library by the way!!! thank you

**Comment by mob-sakai** [comment]
@xiangyuan 
Sorry for the late reply.

I do not know how to use baido...
Can I share in other ways?

Or can you zip only the following directories and attach it here?

- Assets
- ProjectSettings
- Packages

Thanks

**Comment by xiangyuan** [comment]
[Packages.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/4178630/Packages.zip)
[ProjectSettings.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/4178631/ProjectSettings.zip)
[Assets.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/4178633/Assets.zip)

@mob-sakai    i upload the directories

**Comment by mob-sakai** [comment]
@xiangyuan 

Thank you again!

**Comment by mob-sakai** [comment]
@leehans 
Attach UIParticles to child particle systems as well as the root particle system. :)
![](https://user-images.githubusercontent.com/12690315/74122811-d3cefe80-4c0f-11ea-9fbf-c5c7a9cf23d4.png)

@xiangyuan 
This behavior is **"by design."**
UIParticles disable the Render module at runtime, to prevent double rendering.
I will change the text in the inspector to make it more understandable. :)
![](https://user-images.githubusercontent.com/12690315/74122986-79826d80-4c10-11ea-98ed-762844048e7d.png)

**Comment by xiangyuan** [comment]
> @leehans
> Attach UIParticles to child particle systems as well as the root particle system. :)
> ![](https://user-images.githubusercontent.com/12690315/74122811-d3cefe80-4c0f-11ea-9fbf-c5c7a9cf23d4.png)
> 
> @xiangyuan
> This behavior is **"by design."**
> UIParticles disable the Render module at runtime, to prevent double rendering.
> I will change the text in the inspector to make it more understandable. :)
> ![](https://user-images.githubusercontent.com/12690315/74122986-79826d80-4c10-11ea-98ed-762844048e7d.png)

@mob-sakai  in the project when uiparticle attached or not   the particle are different why?

**Comment by mob-sakai** [comment]
@xiangyuan 
UIParticle disables the render module when:
* Attach UIParticle to GameObject
* Click `Reset` from the context menu
* At running

**Comment by xiangyuan** [comment]
thank you @mob-sakai i know
