### ISSUE TITLE
Editor crashes when Mesh is set to none when ParticleSystem.RenderMode=Mesh

### ISSUE THREAD

**Issue by mob-sakai** [mob-sakai/ParticleEffectForUGUI#69]
* v2.3.0
* Unity 2019.3.0f6

**Comment by mob-sakai** [comment]
Editor crashes when Mesh is set to none when Render Mode is Mesh.
![](https://user-images.githubusercontent.com/12690315/74121680-e2b3b200-4c0b-11ea-9968-e050d1668537.png)

**Comment by xiangyuan** [comment]
attach uiparticle script. then click fix button  the editor crash .
is this problem?
@mob-sakai

**Comment by mob-sakai** [comment]
@xiangyuan 
Yes, it happened in the project you attached.
Thanks!

**Comment by xiangyuan** [comment]
> 🎉 This issue has been resolved in version 3.0.0-preview.1 🎉
> 
> The release is available on:
> 
> * [GitHub release](https://github.com/mob-sakai/ParticleEffectForUGUI/releases/tag/v3.0.0-preview.1)
> * `v3.0.0-preview.1`
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot 📦🚀

I have a problem, and i need your help.  i open the preview project compiled raise an error.
`Cannot access internal class 'ShapeModuleUI' here` 
i use rider as my IDE , i don't know why

**Comment by mob-sakai** [comment]
@xiangyuan 

Oh, sorry.
Please tell us your development environment.

**Comment by xiangyuan** [comment]
> @xiangyuan
> 
> Oh, sorry.
> Please tell us your development environment.

Unity 2019.3.0f6

**Comment by mob-sakai** [comment]
Windows? .Net framework 4.x or .Net standard 2.0?

**Comment by xiangyuan** [comment]
> .Net framework 4.x

.Net framework 4.x   macos

**Comment by xiangyuan** [comment]
> Windows? .Net framework 4.x or .Net standard 2.0?

![image](https://user-images.githubusercontent.com/914843/74422888-4e0ab780-4e8a-11ea-8c83-4cd64481d6ad.png)

**Comment by mob-sakai** [comment]
Thanks!
It was reproduced in my environment.

**Comment by mob-sakai** [comment]
https://github.com/mob-sakai/OpenSesameCompilerForUnity/issues/14

**Comment by mob-sakai** [comment]
ref #70

**Comment by mob-sakai** [comment]
Ref #71
