### ISSUE TITLE
Severe GC Allocations when using particles

### ISSUE THREAD

**Issue by KumoKairo** [mob-sakai/ParticleEffectForUGUI#7]
See attached screenshot. 11.8 Kb for particle meshes alone. It's just too much allocations which will incur hiccups and frame skips spent on GC Collect every now and then (it's every ~10 frames on my desktop target - see the second screenshot). GC Collect is much heavier in real cases with actual gameplay stuff going on as the heap is bigger both in terms of memory and objects count, not to mention mobile targets.
Is there a way to **completely** remove these allocations?

![image](https://user-images.githubusercontent.com/2943071/44136746-9b43bb82-a076-11e8-80a6-414e24a19962.png)
![image](https://user-images.githubusercontent.com/2943071/44136900-2bf8f0b6-a077-11e8-9850-5ae4df23f9e9.png)

**Comment by mob-sakai** [comment]
Hi @KumoKairo
Oh, I'm sorry I confused you.

Demo scene is for comparing the "Bake mesh (UIParticle)" approach and the conventional approaches.
UIParticleSystem(_Demo) is a component for the demo and is **NOT** an important component for this package.

UIParticleSystem is published in the following forum.
https://forum.unity.com/threads/free-script-particle-systems-in-ui-screen-space-overlay.406862/
As you say, UIParticleSystem generates GC (PreLateUpdate: 11.8 KB, PostLateUpdate: 4.0 KB) every frame.
Disabling UIParticleSystem component will completely remove these allocations.

Therefore, I want you to use the UIParticle component.
UIParticle component does not generate GC every frame.

![](https://user-images.githubusercontent.com/12690315/44138595-5f8a3b1e-a0af-11e8-96cb-18e2c228651b.png)
