### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by MartinGonzalez** [mob-sakai/ParticleEffectForUGUI#72]
Hey! Great tool!

We're considering to use it in productive games, do you have any roadmap of what's coming or even if you know some issues it has to evaluate. We would like to know if it's stable.

In anything we can contribute we will!

**Comment by mob-sakai** [comment]
Hi @MartinGonzalez 

v3.0.0 (in preview) is *almost* stable version. :)
It will be released soon.

No new features are planned.

**Comment by MartinGonzalez** [comment]
Nice!

Does it work on Mobile? 
I've tested quickly and seems to work but I guess has some glitches, I attached a screen recording.


[RPReplay_Final1582850437.MP4.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/4264775/RPReplay_Final1582850437.MP4.zip)

It can be seen that is like masked, but there is no mask in the scene

**Comment by mob-sakai** [comment]
I would like to know more information on the issue.
Can you attach a minimal repro project for this issue?
It will help to solve the issue.

**Comment by mob-sakai** [comment]
> Does it work on Mobile?

Yes!

**Comment by mob-sakai** [comment]
@MartinGonzalez 
Do you need any help?

**Comment by MartinGonzalez** [comment]
It worked! It was something related to saving the project before pushing my changes to the repo. everything seems to be working fine, I would love to see some performance stress or benchmark. It would give more confidence to new users of this component
If you need any help or feedback feel free to send me emails or messages :) and great work!
