### ISSUE TITLE
Multiple UIParticleOverlayCamera in scene.

### ISSUE THREAD

**Issue by as3mbus** [mob-sakai/ParticleEffectForUGUI#73]
**Describe what help do you need**
Is there any limitation on using multiple ui particle on scene with overlay camera canvas ?
there are warning that pops out that gets me worried if i use stuff wrong.

**Additional context**
would love a help to either fix / ignore this warning according to the previous question answer. 

thank you

**Comment by mob-sakai** [comment]
@as3mbus 
Probably, UIParticleOverlayCamera exists in multiple scenes in your project.
I will use `GameObject.hideFlag` to prevent this issue.

**Comment by as3mbus** [comment]
ah yes. i used some RuntimeInitializeOnLoadMethod to always load setup scene before starting actual scene. 

so most likely scenario is overlay camera might not be fully initialized before changing scene to setup scene, and when going back to actual scene where particle ui reside it'll try to setup init itself one more time. (idk if this actually happen, but reading the code lead me to such assumption)

**Comment by as3mbus** [comment]
somewhat solved it with workaround by moving overlay camera into my setup scene. 

i believe warning is somewhat not necessary for this case as you will always destroy the camera if one already exist.

**Comment by mob-sakai** [comment]
Please try to use `v3.0.0-preview.8` :)

**Comment by as3mbus** [comment]
tested, and it worked fine thanks for your fast response 👍
