### ISSUE TITLE
No meta file for folder Samples

### ISSUE THREAD

**Issue by Kilosoft** [mob-sakai/ParticleEffectForUGUI#74]
**Describe the bug**
No meta file for folder Samples

**To Reproduce**
1. use openupm add com.coffee.ui-particle
2. Reopen Unity

**Comment by mob-sakai** [comment]
openupm seems to pack using the `v3.0.0-preview.x` tag.
I made a pull request to fix it.

https://github.com/openupm/openupm/pull/94

**Comment by mob-sakai** [comment]
`3.0.0-preview.9` works well! :)
