### ISSUE TITLE
Optimization for vertices transforms and adding node for trails

### ISSUE THREAD

**Issue by ken48** [mob-sakai/ParticleEffectForUGUI#75]
You can use CombineInstance class for it.
It allows to combinig as submeshes with different materials and apply some transforming matrix for mesh (not just to single vertex).
Just look at my solution:
https://github.com/ken48/UnityUiParticles

**Comment by mob-sakai** [comment]
@ken48 
Awesome!

**Comment by mob-sakai** [comment]
NOTE: This will be supported in the next version.

**Comment by mob-sakai** [comment]
**Unsolvable technical problems:**
The plugin supports Sprite by overriding the `mainTexture` property.
However, `CanvasRenderer` cannot support multiple textures.
If the trail material contained the `_MainTex` property, the texture will be overwritten.

**Comment by ken48** [comment]
Yes, but CanvasRenderer supports multiple submeshes. And each submesh has its own material.

**Comment by mob-sakai** [comment]
OK, I will update it as follows:

- For `Sprites` mode, use an additional UIParticle for trail (as usual).
  - The performance may be improved by using `CombineInstance`.
- For other cases, use `CombineInstance` to merge trail particle.

**Comment by mob-sakai** [comment]
**Next**

For Sprites mode, generate a new material for main particle and assign sprite’s texture to it.

The additional UIParticle for trail is no longer needed.

**Comment by mob-sakai** [comment]
Note: Mesh.CombineMeshes ignores meshes with vertexCount=0.
For example, if I bake and combine a particle that only shows trails, submeshCount is 1.

**Comment by mob-sakai** [comment]
Ref: `3.0.0-preview.22`
