### ISSUE TITLE
Exception: [OpenSesameCompiler] Open Sesame compiler is not found

### ISSUE THREAD

**Issue by danilavanilla** [mob-sakai/ParticleEffectForUGUI#76]
I am using ParticleEffectForUgui in my project, on my Windows PC is fine, but on my Mac i am getting error:
`Exception: <color=#c34062><b>[OpenSesameCompiler]</b></color> Open Sesame compiler is not found at Library/OpenSesameCompiler.3.4.0/tools/csc.exe`
I need to make build on IOS. How to fix this issue?

**Comment by mob-sakai** [comment]
@danilavanilla 
I'm using Mac too, and I've never seen that error...
I'm guessing that it failed to download OpenSesameCompiler package.

- OpenSesameCompiler is hosted here.  
https://www.nuget.org/packages/OpenSesameCompiler/
  - Do you have access to this page?
- You can download the package directly.  
https://www.nuget.org/api/v2/package/OpenSesameCompiler/3.4.0
  - Have you downloaded opensesamecompiler.3.4.0.nupkg?

**Comment by danilavanilla** [comment]
> @danilavanilla
> I'm using Mac too, and I've never seen that error...
> I'm guessing that it failed to download OpenSesameCompiler package.
> 
> * OpenSesameCompiler is hosted here.
>   https://www.nuget.org/packages/OpenSesameCompiler/
>   
>   * Do you have access to this page?
> * You can download the package directly.
>   https://www.nuget.org/api/v2/package/OpenSesameCompiler/3.4.0
>   
>   * Have you downloaded opensesamecompiler.3.4.0.nupkg?

Yes, i have access to this page. 
I need to put this .nupkg file directly into Library/OpenSesameCompiler.3.4.0/ or something else?

**Comment by mob-sakai** [comment]
As a workaround, run the following command in the terminal:

```sh
cd {your_project_directory}/Library
unzip -d OpenSesameCompiler.3.4.0 opensesamecompiler.3.4.0.nupkg
```

**Comment by danilavanilla** [comment]
> As a workaround, run the following command in the terminal:
> 
> ```shell
> cd {your_project_directory}/Library
> unzip -d OpenSesameCompiler.3.4.0 opensesamecompiler.3.4.0.nupkg
> ```
I unzipped OpenSesameCompiler, and i am getting error (Unity 2018.3.0f2):
![Снимок экрана 2020-05-13 в 14 43 29](https://user-images.githubusercontent.com/23268636/81803447-c08e4080-9528-11ea-8781-d34e4094f16c.png)

**Comment by danilavanilla** [comment]
I decrease version to 2.3.0, and error has gone.

**Comment by mob-sakai** [comment]
Could you please attach a minimal project that reproduces the issue?
