### ISSUE TITLE
Texture sheet animation module Sprite mode not working

### ISSUE THREAD

**Issue by soimy** [mob-sakai/ParticleEffectForUGUI#79]
**Describe the bug**
Texture sheet animation module Sprite mode not working, hole texture of a multi-packed sprite is shown.

**To Reproduce**
1. Set particle system sheet animation module on, mode to `sprite`
2. Assign several sprites from a multi-packed spritesheet.
3. UI particle set animatable properties to `_MainTex_ST`
3. Playback, whole spritesheet shown instead of sprite.

**Environment (please complete the following information):**
 - Version [3.0.0-preview.11]
 - Platform: [e.g. Editor(Windows)]
 - Unity version: [e.g. 2020.1.0b8]

**Additional context**
Digging through the code, I found that `UIParticle.cs` will set `textureSheet.uvChannelMask`
https://github.com/mob-sakai/ParticleEffectForUGUI/blob/b0e2688c38a695c301be85ce9542d154a94627a2/Scripts/UIParticle.cs#L93
comment out this line works for me.

**Comment by mob-sakai** [comment]
@soimy 
Sorry for my late reply.
I would like to know more about this issue.
Could you please attach a minimal project that reproduces the issue?

**Comment by soimy** [comment]
I will.
Can you tell me why `textureSheet.uvchannelMask` is set to `-1` when using multi packed sprite?
It works when `uvChannelMask` is untouched(UV0)

**Comment by mob-sakai** [comment]
@soimy 
Sorry for my late reply.
The issue is reproduced in my environment.

![](https://user-images.githubusercontent.com/12690315/89994087-99c7dd80-dcc2-11ea-9d66-eb1e44070f3d.png)

> Can you tell me why `textureSheet.uvchannelMask` is set to `-1` when using multi packed sprite?

To support the Sprite Atlas.

**Comment by soimy** [comment]
`uvChannelMask` is usually handled by the user via the dropdown menu. Multi-packed sprite sheet won't work when `uvChannelMask` is set to `Nothing`(-1)

**Comment by mob-sakai** [comment]
Yes, you are right.
I should not have used it as a workaround of any kind.

The problem to begin with was that I couldn't get the actual texture from the sprite.
The sprites in the Sprite Atlas do not return a packed texture **in editor mode.**

I just found a non-public API that gets the packed textures from sprites.
I'll test it later.

**Comment by mob-sakai** [comment]
I did it! :+1:
[This API](https://github.com/Unity-Technologies/UnityCsReference/blob/master/Editor/Mono/2D/Common/ScriptBindings/SpriteEditorExtension.bindings.cs#L26) solves the issue!

**Before:**
![Aug-12-2020 21-07-44](https://user-images.githubusercontent.com/12690315/90013617-94798b80-dce0-11ea-880e-dbe8f825c0c1.gif)
**After:**
![Aug-12-2020 21-08-41](https://user-images.githubusercontent.com/12690315/90013625-96dbe580-dce0-11ea-88a1-3084ce7db40f.gif)

**Comment by soimy** [comment]
Thank you!
