### ISSUE TITLE
Try to change size of particles

### ISSUE THREAD

**Issue by bqcuong** [mob-sakai/ParticleEffectForUGUI#8]
Hi, I get trouble with particle system but luckily I found your awesome repo.
But I'm now stuck with the particle size (like below image).
I tried increase Start size but the particles won't be bigger.

My Unity version: 2018.2.1f1
Canvas Render mode: Screen Space - Overlay

Hope to find the solution soon.

![image](https://user-images.githubusercontent.com/13081254/47501926-ce219e00-d890-11e8-923a-7f046698b4de.png)

**Comment by mob-sakai** [comment]
Hi @bqcuong 

Thank you for using this plugin.
Hmm, I will try to test it later.

Can you submit a reproducible project for this issue?

**Comment by mob-sakai** [comment]
I tested this issue, but it did not reproduce.
Particle size could be changed by "Start Size" and "Transform's scale".
Please attach a reproducible project for this issue.

### Test Environment
* Unity version: 2018.2.1f1(Mac)
* Plugin version: v1.0.0
* Canvas Render mode: Screen Space - Overlay
* I tested in edit mode and in play mode.  
![](https://user-images.githubusercontent.com/12690315/47506143-77c15900-d8aa-11e8-893a-76b255f94b2e.gif)
* Scene file used for testing: [test.unitypackage.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/2515242/test.unitypackage.zip)

**Comment by bqcuong** [comment]
Thank you very much.
I found that I have to change transform's scale too, not only change start size.
