### ISSUE TITLE
Particles not visible in android build on some devices. Universal Render Pipeline

### ISSUE THREAD

**Issue by Watcher3056** [mob-sakai/ParticleEffectForUGUI#80]
**Describe the bug**
Particles not visible in android build ON arm64(V8) architectures, using Universal Render Pipeline, but okay on V7 architecture and in editor.

**To Reproduce**
1. Create android project with URP(make sure you are using 2D Renderer Experimental pipeline)
2. Add particles with Baking mesh(UIParticle)
3. Make build for arm64(V8) architecture
4. Test it on V8 phone
5. Did you see particles on screen? Any workaround with it if yes?

**Environment (please complete the following information):**
 - Version 3.0.0-preview.11
 - Platform: Android
 - Unity version: 2019.3.0f6
 - Build options: IL2CPP, .Net4.x, ARM64

**Additional context**
Need your responce and help asap, please. This problem stop us from publish our game...
I will try to find anything wrong in logs today

Thanks. Regards.

**Comment by Watcher3056** [comment]
Sorry. I tried to reproduce issue in empty project following to my steps, but not successfuly. I dont know what is reason to this behaviour may be. Any suggestions?

**Comment by mob-sakai** [comment]
@Watcher3056 
Sorry for the late reply.
* What shader are you using?
* Show me a screenshot of the ParticleSystem inspector

**Comment by Watcher3056** [comment]
Hi, thanks for your reply.
Hope thats you requested:

![Unity_LxTt4R1fFA](https://user-images.githubusercontent.com/53340768/87927351-c3a72f00-ca8b-11ea-849a-dc95cfcdf6c5.png)
![Unity_TuGPqRKy56](https://user-images.githubusercontent.com/53340768/87927366-c6a21f80-ca8b-11ea-9971-85972209430f.png)

As you can see particles (Star) visible in editor, and i can say again, that it visible on old v7 phone...
Also there is no difference between Mono or IL2CPP Builds.

Thanks. Regards.

**Comment by Watcher3056** [comment]
Also i got exactly same issue with this particles: https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/wiki/Controls/UIParticleSystem

**Comment by mob-sakai** [comment]
@Watcher3056 
* Show me a screenshot of the "Renderer" module in ParticleSystem inspector.
![image](https://user-images.githubusercontent.com/12690315/87941267-d9d9dd00-cad5-11ea-9076-9b636df1fc7d.png)
* Does the ParticleSystem (without UIParticle) show particles?
* If you update the editor to 2019.3.15f1, will the issue be resolved?
https://issuetracker.unity3d.com/issues/uwp-arm64-the-particles-in-particle-system-flickers-on-arm64-devices

**Comment by Watcher3056** [comment]
![Unity_aSkRNdTfe3](https://user-images.githubusercontent.com/53340768/87971327-d4789480-cacd-11ea-8a49-e625d0759422.png)
![Unity_QtP3Zj9qGO](https://user-images.githubusercontent.com/53340768/87971331-d6daee80-cacd-11ea-8dce-3e0b6c4980a2.png)

Particles not shown when i disable/remove UIParticles component, because of disabled renderer. But its okay, when i enable renderer.

I will try to expirement more after a couple of days, cant check it now.

**Comment by mob-sakai** [comment]
Thanks.

>Sorry. I tried to reproduce issue in empty project following to my steps, but not successfuly. I dont know what is reason to this behaviour may be. Any suggestions?

Look at these settings in your project:
* Graphic API and other graphic's setting
* Canvas render mode (overlay/camera)

**Comment by Nanryung** [comment]
I have similar issue too, so i wirte my test cases

All test case using canvas overlay

1. OpenGLES & Graphic Tier Settings Using HDR
Editor : Fine
Build : Not Showing

2. OpenGLES & Not Using HDR or Default
Editor : Fine
Build : Showing But some particles can't show

3. Vulkan & Using HDR
Editor : Fine
Build : Showing but flick repeat, almost particles looks fine

Test Editor Version Unity 2019.3, 2019 LTS 4.4

--

I don't kwno why graphics api affect this plugin

**Comment by Watcher3056** [comment]
Hi.

Graphics api is set on auto.
Canvas render in overlay mode

Texture Import Settings of mat:
![image](https://user-images.githubusercontent.com/53340768/88051258-fcfd9e80-cb60-11ea-900e-d3fcee10f051.png)

**Comment by mob-sakai** [comment]
@Nanryung @Watcher3056 
Thanks.
It could be the graphics api, architecture, or rendering pipeline.
Or, if you enable **multithreaded rendering**, the BakeMesh API may not be able to render in time for the drawing process.

Please show me `Edit > Project Settings > Player > Other Settings`
![image](https://user-images.githubusercontent.com/12690315/88052648-829b4180-cb95-11ea-93b8-ae9055b4654f.png)

**Comment by Watcher3056** [comment]
Yes, im using multithreaded rendering here:

![NQ6XShqpfB](https://user-images.githubusercontent.com/53340768/88056880-ef004b80-cb69-11ea-958b-871f0f59fa48.png)
![uYUcT0exgt](https://user-images.githubusercontent.com/53340768/88056886-f0317880-cb69-11ea-806e-31f4130b6f5b.png)
![BBeByHsnMV](https://user-images.githubusercontent.com/53340768/88056891-f1fb3c00-cb69-11ea-8def-ca34e081afde.png)

**Comment by Watcher3056** [comment]
But i builded your test project with exacly same settings in "other" and UIParticles(bake mesh) works properly on V8 with URP

**Comment by mob-sakai** [comment]
@Watcher3056 
If the project is "light" enough, the BakeMesh API may not cause any problems.
Otherwise, rendering and the BakeMesh API may be processed in parallel.

**Comment by Watcher3056** [comment]
> @Watcher3056
> If the project is "light" enough, the BakeMesh API may not cause any problems.
> Otherwise, rendering and the BakeMesh API may be processed in parallel.
> 
> NOTE: This is just my prediction.

Well... really interesting opinion. I will test it too as soon, as i can.

**Comment by mob-sakai** [comment]
If the above predictions are correct, then calling the BakeMesh API in UIParticle.Update may work correctly.

**Comment by Watcher3056** [comment]
Hi. I just tested build with DISABLED multithreaded rendering, but still see no particles...

**Comment by Watcher3056** [comment]
Okay, looks like problem was solved by update to Unity 2019.3.15f1, as you said.
Im very grateful to you!

Thanks. Regards.

**Comment by mob-sakai** [comment]
@Watcher3056 
Thanks for testing.
Hmm, what the hell is going on...?

**Comment by Watcher3056** [comment]
Updated URP from 7.3.1 to 7.4.1 and now my scene view is fully black(but not UI space)
This problem appears only on my old Galaxy Prime
Logcat full of errors:
```
07.23 13:07:10.401 12773 12793 Error Unity: Texture creation failed. 'R8G8B8A8_SRGB' is not supported for Sample usage on this platform. Use 'SystemInfo.IsFormatSupported' C# API to check format support.
```

**Comment by mob-sakai** [comment]
@Watcher3056 
Sorry for the delay in replying.
What version of the Universal Render Pipeline are you using?

**Comment by mob-sakai** [comment]
I found a change log that caught my eye.

https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@10.0/changelog/CHANGELOG.html

> ### Fixed
> Fixed an issue where linear to sRGB conversion occurred twice on certain Android devices.
> Fixed user LUT sampling being done in Linear instead of sRGB.
> Fixed an issue when Linear -> sRGB conversion would not happen on some Android devices. case 1226208
> Fixed an issue that caused Android GLES to render blank screen when Depth texture was enabled without Opaque texture case 1219325

If you're using an old version Universal Render Pipeline, try updating it. 👍
