### ISSUE TITLE
The type or namespace name 'U2D' does not exist in the namespace 'UnityEditor.Experimental'

### ISSUE THREAD

**Issue by AGeorgy** [mob-sakai/ParticleEffectForUGUI#82]
Library\PackageCache\com.coffee.ui-particle@f2034e27b7\Scripts\UIParticle.cs(646,93): error CS0234: The type or namespace name 'U2D' does not exist in the namespace 'UnityEditor.Experimental' (are you missing an assembly reference?)

v3.0.0-preview.16

**Comment by mob-sakai** [comment]
@AGeorgy 
Thank you for your reporting!
I will fix it ASAP.
