### ISSUE TITLE
Particles with shape on and stretched billboard renderer not showing

### ISSUE THREAD

**Issue by mr-tm** [mob-sakai/ParticleEffectForUGUI#84]
**Describe the bug**
Particle System with shape on and stretched billboard renderer not showing.

**To Reproduce**
1. Create Particle System with stretched billboard renderer
2. Press Play
4. Check Result in Editor

**Expected behavior**
Particles are visible

**Actual behavior**
Particles are not visible

**Screenshots**
Not working particle example
![image](https://user-images.githubusercontent.com/34609827/91070113-fde18e80-e63e-11ea-8ad4-4327a5ea576c.png)

Working particle example
![image](https://user-images.githubusercontent.com/34609827/91070169-16ea3f80-e63f-11ea-8529-bfbb1d5ec1bf.png)

**Environment:**
 - Version 3.0.0-preview.18
 - Platform: Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL
 - Unity version: 2020.1.1f1
 - Build options: .Net 4.x, Built In Render Pipeline

**Additional context**
Tried to change ordering, layers, scaling. Still nothing.

**Comment by mr-tm** [comment]
Ok. It seems to be working fine in different scene. I'll do some more investigation and report back.

**Comment by mob-sakai** [comment]
@mr-tm 
Thank you for your reporting!

**Comment by mob-sakai** [comment]
@mr-tm 
Try to use `3.0.0-preview.22`

**Comment by mr-tm** [comment]
THANK YOU! I tried 3.3.0 and all the issues seems to be fixed! 👍
