### ISSUE TITLE
[Android] - Build for Android fails

### ISSUE THREAD

**Issue by Eatos** [mob-sakai/ParticleEffectForUGUI#85]
When trying to export project for android with the plugin enabled, it fails because ISerializationCallbackReceiver is not handled due to #if UNITY_EDITOR

Unity Version: 2019.3.15f1 
Plugin Version: 3.0.0-preview21

Fix in UIParticle.cs
![fix](https://user-images.githubusercontent.com/3318097/91626360-bfd1cb00-e9ae-11ea-977b-9cd734b20b0d.PNG)

**Comment by mob-sakai** [comment]
@Eatos 
Thank you for your reporting!
