### ISSUE TITLE
Particle scaling issues when changing Canvas RenderMode

### ISSUE THREAD

**Issue by theKin** [mob-sakai/ParticleEffectForUGUI#9]
Hi

Thank you for releasing the awesome UI Particle plug-in,
and please understand that my English is awkward.

There is something that seems to be a bit of a problem when I test it.

I opened the project that I uploaded as an example to Unity (2018.2.5f1) and it worked without any problem.  However, changing the Canvas's RenderMode to ScreenSpace-Overlay did not seem to work.

I thought it was a problem in the UIParticle.cs to call the BakeMesh function with the Camera as an argument even though it was not based on CameraRenderMode.  In fact, it was too small to render.

To make it work as intended, I need to raise the Scale of the RectTransform to 60, as in the example in ConvertParticlesToUIVertex.

I wonder if the intended behavior is correct.

**Comment by mob-sakai** [comment]
Hi @theKin 

Thank you for using this plugin.

I have heard of this issue before.
I hope #8 will be of help to you.

Can you submit a reproducible project for this issue?

**Comment by theKin** [comment]
I tested it in the example scene included in the plug-in that you uploaded to gitHub.

So if it's an issue like # 8,
When I change the RenderMode of Canvas to ScreenSpace-Overlay, do I understand that I am directly changing the scale of the RectTransform?

**Comment by mob-sakai** [comment]
Oh, I get it.
As you say, the particles are so small that they can not be seen.
It looks like a bug.

**Comment by mob-sakai** [comment]
Umm, It is difficult issue...

**Comment by mob-sakai** [comment]
Most particle effects consist of multiple ParticleSystems.
Changing the all Transform.localScale for scaling particles is a bother, and may not result in correct results.

I think that it is necessary to have a "scale" independent from ParticleSystem.StartSize and Transform.localScale.

**Comment by mob-sakai** [comment]
[WIP] Scaling by transform vs scaling by post scale

![](https://user-images.githubusercontent.com/12690315/49070695-a8acf900-f26f-11e8-8ca1-195f1b42a07e.gif)  
Smoke trails are incorrect.

![](https://user-images.githubusercontent.com/12690315/49070689-a5b20880-f26f-11e8-81d9-b15656736625.gif)  
Good scaling!

**Comment by theKin** [comment]
So cool!
I'll wait for post scale version. :)

**Comment by mob-sakai** [comment]
v1.1.0 has been released!
[Release page](https://github.com/mob-sakai/ParticleEffectForUGUI/releases/tag/v1.1.0)
