### ISSUE TITLE
When Use Resources.UnloadUnusedAssets, material is released

### ISSUE THREAD

**Issue by wonseoblim** [mob-sakai/ParticleEffectForUGUI#90]
When `Resources.UnloadUnusedAssets` is called, 
the material is released that returned from
`public override Material GetModifiedMaterial(Material baseMaterial) `

It seems that the ReferenceCount is not set for the material that return the **GetModifiedMaterial** method.
This is solved by having a material in the UIParticle.

Version: 3.0.0 [ce6478cf1f2103542a860e256ef7fc2535f47c13]
Platform: Editor Mac
Unity version: 2019.3.15f

**Comment by mob-sakai** [comment]
Please try to use `v3.0.0-preview.28`

**Comment by wonseoblim** [comment]
oh! It works well.
thank you!!
