### ISSUE TITLE
Combine Instances error

### ISSUE THREAD

**Issue by cfoulston** [mob-sakai/ParticleEffectForUGUI#91]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Describe the bug**

Cannot combine into a mesh that is also in the CombineInstances input: 
0x00007FF63A50A14C (Unity) StackWalker::GetCurrentCallstack
0x00007FF63A50E171 (Unity) StackWalker::ShowCallstack
0x00007FF63B777A05 (Unity) GetStacktrace
0x00007FF63C60771E (Unity) DebugStringToFile
0x00007FF639B4974A (Unity) CombineMeshes
0x00007FF639B49B2E (Unity) MeshScripting::CombineMeshes
0x00007FF63A5EB90A (Unity) Mesh_CUSTOM_CombineMeshesImpl
0x000002A2B440E6A0 (Mono JIT Code) (wrapper managed-to-native) UnityEngine.Mesh:CombineMeshesImpl (UnityEngine.Mesh,UnityEngine.CombineInstance[],bool,bool,bool)
0x000002A2B440E5B3 (Mono JIT Code) UnityEngine.Mesh:CombineMeshes (UnityEngine.CombineInstance[],bool,bool)
0x000002A2B440DC6B (Mono JIT Code) [MeshHelper.cs:95] Coffee.UIExtensions.MeshHelper:CombineMesh (UnityEngine.Mesh) 
0x000002A2B4403213 (Mono JIT Code) [UIParticleUpdater.cs:241] Coffee.UIExtensions.UIParticleUpdater:BakeMesh (Coffee.UIExtensions.UIParticle) 
0x000002A2B43FFB53 (Mono JIT Code) [UIParticleUpdater.cs:66] Coffee.UIExtensions.UIParticleUpdater:Refresh (Coffee.UIExtensions.UIParticle) 
0x000002A2A7F0A6BB (Mono JIT Code) [UIParticleUpdater.cs:48] Coffee.UIExtensions.UIParticleUpdater:Refresh () 
0x000002A2A7ED1EB2 (Mono JIT Code) (wrapper delegate-invoke) <Module>:invoke_void ()
0x000002A2A7ED1CCC (Mono JIT Code) UnityEngine.Canvas:SendWillRenderCanvases ()
0x000002A2A7ED1D6D (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void (object,intptr,intptr,intptr)
0x00007FF9C10ED8A0 (mono-2.0-bdwgc) [mini-runtime.c:2809] mono_jit_runtime_invoke 
0x00007FF9C1072912 (mono-2.0-bdwgc) [object.c:2921] do_runtime_invoke 
0x00007FF9C107B96F (mono-2.0-bdwgc) [object.c:2968] mono_runtime_invoke 
0x00007FF63A3AAA24 (Unity) scripting_method_invoke
0x00007FF63A3A455B (Unity) ScriptingInvocation::Invoke
0x00007FF638FF9896 (Unity) `UI::InitializeCanvasManager'::`2'::UIEventsWillRenderCanvasesRegistrator::Forward
0x00007FF639D28E41 (Unity) `InitPlayerLoopCallbacks'::`2'::PostLateUpdatePlayerUpdateCanvasesRegistrator::Forward
0x00007FF639D11BD9 (Unity) ExecutePlayerLoop
0x00007FF639D11CB0 (Unity) ExecutePlayerLoop
0x00007FF639D16F0C (Unity) PlayerLoop
0x00007FF63AFA4EEE (Unity) PlayerLoopController::UpdateScene
0x00007FF63AFA40E0 (Unity) Application::TickTimer
0x00007FF63B79E8E3 (Unity) MainMessageLoop
0x00007FF63B7A7C4E (Unity) WinMain
0x00007FF63D410556 (Unity) __scrt_common_main_seh
0x00007FFA4AED7BD4 (KERNEL32) BaseThreadInitThunk
0x00007FFA4CB2CE51 (ntdll) RtlUserThreadStart

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Version [e.g. 1.0.0]
 - Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL]
 - Unity version: [e.g. 2020.1.2f1]
 - Build options: [e.g. IL2CPP, .Net 4.x, LWRP]

**Additional context**

**Comment by mob-sakai** [comment]
@cfoulston 
What version of ParticleEffectForUGUI and what version of Unity are you using?

**Comment by cfoulston** [comment]
Unity 2020.1.2f1
Particle UI 3.0.0-preview 30

I'll try creating a simple repo tomorrow. But my current setup is having multiple particles in a scroll rect, and when disabling and enabling parents the issue occurs.

It does not occur on first play. Only after second play

**Comment by mob-sakai** [comment]
@cfoulston 
Thank you for your cooperation.

**Comment by mob-sakai** [comment]
@cfoulston 
It is reproduced in my environment.
