### ISSUE TITLE
Unity animator not working with UIParticle

### ISSUE THREAD

**Issue by wonseoblim** [mob-sakai/ParticleEffectForUGUI#95]
I have set up animatable property, but not working with animator and no changed particle object

so I checked that changed the material value , but not called `UpdateMaterialProperties` in UIParticle

Unity Version: 2019.3.15f
UIParticle Version: Preview31

**Comment by mob-sakai** [comment]
@wonseoblim 
Thank you for your reporting.
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

**Comment by wonseoblim** [comment]
[UIParticle.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/5216610/UIParticle.zip)
It's minimal project
I hope it helps you

**Comment by mob-sakai** [comment]
@wonseoblim 
Thanks for the reply!

**Comment by mob-sakai** [comment]
![Sep-14-2020 17-22-06](https://user-images.githubusercontent.com/12690315/93061691-dfefd280-f6ae-11ea-99bf-a0ad4a318e64.gif)
The issue has been reproduced. 👍

**Comment by mob-sakai** [comment]
@wonseoblim 
It is fixed in v 3.0.0-preview.32

**Comment by wonseoblim** [comment]
thank you!!
