### ISSUE TITLE
Simulation Space : World" not working as expected

### ISSUE THREAD

**Issue by ooyun0** [mob-sakai/ParticleEffectForUGUI#97]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Version [e.g. 1.0.0]
 - Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL]
 - Unity version: [e.g. 2018.2.8f1]
 - Build options: [e.g. IL2CPP, .Net 4.x, LWRP]

**Additional context**

**Comment by mob-sakai** [comment]
@ooyun0 
I would like to know more about this issue.
- Fill in the issue template
- Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

**Comment by ooyun0** [comment]
@mob-sakai 
sorry for wrong issue...
I recreated it. https://github.com/mob-sakai/ParticleEffectForUGUI/issues/98
Can you see it?

**Comment by mob-sakai** [comment]
OK
