### ISSUE TITLE
Simulation Space : "World" not working as expected

### ISSUE THREAD

**Issue by ooyun0** [mob-sakai/ParticleEffectForUGUI#98]
**Describe the bug**
Particle follows root transform when i set Simulation Space to **World**

**To Reproduce**
1. Add UI Particle Script to particle system
2. Change Simulation Space to **World**

**Expected behavior**
Particle stays at emitted position

**Screenshots (click to see gif)**
![ezgif-5-c641cc235bb1](https://user-images.githubusercontent.com/20644690/93188296-c8325000-f77b-11ea-9485-b0cdd56bbb9a.gif)

**Environment**
 - Version 3.0.0-preview.33
 - Platform: Editor(Windows)
 - Unity version: 2018.4.12f1 [e.g. 2018.2.8f1]

**Comment by mob-sakai** [comment]
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

**Comment by ooyun0** [comment]
@mob-sakai 
[New Unity Project.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/5223797/New.Unity.Project.zip)

**Comment by mob-sakai** [comment]
@ooyun0 
Thanks!

**Comment by mob-sakai** [comment]
The issue has been reproduced. 👍

**Comment by mob-sakai** [comment]
Perhaps it is a problem with the extra world simulation correction in UIParticleUpdater.

**Comment by mob-sakai** [comment]
WIP: The issue is fixed.
![Sep-15-2020 21-03-29](https://user-images.githubusercontent.com/12690315/93208116-012bee00-f797-11ea-98d8-a6b4ad1924ac.gif)

**Comment by mob-sakai** [comment]
@ooyun0 
It is fixed.
Thank you for your help! 👍

**Comment by ooyun0** [comment]
👍
