### ISSUE TITLE
Unable to use sprites to animate a vfx object

### ISSUE THREAD

**Issue by jamiltron** [mob-sakai/ParticleEffectForUGUI#99]
Hello, I am currently having an issue where I am trying to animate a particle system using a sprite. The Texture Sheet Animation module of Particle System doesn't appear to work in Sprite mode with your script.  Instead of showing multiple frames over time (or randomly or a single frame or whatever), the entire texture is displayed at all times.  Am I doing something wrong?

**To Reproduce**
1. Create particle system
2. Attach UIParticles component
3. Toggle Texture Sheet Animation module "on"
4. Set Mode to "Sprites"
5. Add multiple sprites from the same texture to the provided array
6. Look at particles and they will display the entire texture as opposed to individual sprites

**Expected behavior**
Particle system animates sprites based on a texture sheet over time.

**Comment by mob-sakai** [comment]
@jamiltron 
Thank you for your reporting!
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

**Comment by mob-sakai** [comment]
https://docs.unity3d.com/Manual/PartSysTexSheetAnimModule.html
Do you set up `Affected/Enable UV Channels` in texture sheet animation module?

**Comment by mob-sakai** [comment]
@jamiltron 
I think you need at least `UV0` channel.

**Comment by jamiltron** [comment]
Got it, thanks!
